<?php
namespace CloudHost247\CartRecovery;
use WHMCS\Database\Capsule;
final class RecoveryService {
    public static function log($level,$event,$context=array()) { if(class_exists('CloudHost247\Foundation\Support\Logger')) \CloudHost247\Foundation\Support\Logger::write('cloudhost247_cart_recovery',$level,$event,$context); }
    public static function capture($cart,$clientId=0,$email='',$first='',$last='',$currency='',$session='') {
        if(!is_array($cart)||!count($cart)||(!($clientId||$email))) return null; $now=date('Y-m-d H:i:s'); $snap=CartSnapshot::capture($cart,$currency); $json=json_encode($snap,JSON_UNESCAPED_SLASHES); $q=Capsule::table('mod_cloudhost247_cart_recovery_recoveries');
        $row=$clientId?$q->where('client_id',(int)$clientId)->whereIn('status',array('active','abandoned','recovered'))->orderBy('id','desc')->first():$q->where('session_key',substr($session,0,128))->whereIn('status',array('active','abandoned','recovered'))->orderBy('id','desc')->first();
        if($row && in_array($row->status,array('active','abandoned'),true)) { $q->where('id',$row->id)->update(array('email'=>substr($email,0,254),'first_name'=>substr($first,0,100),'last_name'=>substr($last,0,100),'currency'=>substr($currency,0,8),'cart_snapshot'=>$json,'cart_total'=>CartSnapshot::total($json),'status'=>'active','last_activity_at'=>$now,'abandoned_at'=>null,'next_reminder_at'=>null,'updated_at'=>$now)); return $row->id; }
        $raw=TokenService::generate(); $id=$q->insertGetId(array('client_id'=>$clientId?:null,'session_key'=>$session?substr($session,0,128):null,'email'=>$email?substr($email,0,254):null,'first_name'=>substr($first,0,100),'last_name'=>substr($last,0,100),'currency'=>substr($currency,0,8),'cart_snapshot'=>$json,'cart_total'=>CartSnapshot::total($json),'status'=>'active','token_hash'=>TokenService::hash($raw),'token_ciphertext'=>TokenService::seal($raw),'token_expires_at'=>date('Y-m-d H:i:s',time()+(int)SettingsRepository::get('token_lifetime')),'first_seen_at'=>$now,'last_activity_at'=>$now,'created_at'=>$now,'updated_at'=>$now)); self::log('info','cart.captured',array('recovery_id'=>$id)); return $id;
    }
    public static function markDue($limit=50) { $threshold=(int)SettingsRepository::get('abandonment_threshold'); $cut=date('Y-m-d H:i:s',time()-$threshold); $q=Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('status','active')->where('last_activity_at','<=',$cut)->whereNull('abandoned_at')->limit($limit); foreach($q->get() as $r) Capsule::table($q->getQuery()->from)->where('id',$r->id)->update(array('status'=>'abandoned','abandoned_at'=>date('Y-m-d H:i:s'),'next_reminder_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s'))); }
    public static function recover($token) { if(!TokenService::valid($token)) return false; $r=Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('token_hash',TokenService::hash($token))->first(); if(!$r||$r->token_expires_at<date('Y-m-d H:i:s')||in_array($r->status,array('converted','expired','closed','unsubscribed'),true))return false; $_SESSION['cart']=CartSnapshot::restore($r->cart_snapshot); Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('id',$r->id)->update(array('status'=>'recovered','recovered_at'=>date('Y-m-d H:i:s'),'last_activity_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s'),'next_reminder_at'=>null)); self::log('info','cart.recovered',array('recovery_id'=>$r->id)); return true; }
    public static function unsubscribe($token) { if(!TokenService::valid($token)) return false; $r=Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('token_hash',TokenService::hash($token))->first(); if(!$r)return false; $now=date('Y-m-d H:i:s'); Capsule::table('mod_cloudhost247_cart_recovery_suppressions')->updateOrInsert(array('email'=>$r->email,'client_id'=>$r->client_id),array('reason'=>'unsubscribe','created_at'=>$now,'updated_at'=>$now)); Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('id',$r->id)->update(array('status'=>'unsubscribed','unsubscribed_at'=>$now,'next_reminder_at'=>null,'updated_at'=>$now)); return true; }
}
