<?php
namespace CloudHost247\CartRecovery;
use WHMCS\Database\Capsule;
final class ReminderService {
    public static function process($limit=50) {
        if(SettingsRepository::get('enabled')!=='1') return array('sent'=>0,'failed'=>0,'skipped'=>0);
        RecoveryService::markDue($limit); $out=array('sent'=>0,'failed'=>0,'skipped'=>0); $now=date('Y-m-d H:i:s');
        $rows=Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('status','abandoned')->whereNotNull('next_reminder_at')->where('next_reminder_at','<=',$now)->where('token_expires_at','>',$now)->orderBy('id')->limit($limit)->get();
        foreach($rows as $r) { $n=(int)$r->last_reminder_number+1; if($n>(int)SettingsRepository::get('maximum_reminders')||SettingsRepository::get('enable_reminder_'.$n)!=='1'||!filter_var($r->email,FILTER_VALIDATE_EMAIL)||Capsule::table('mod_cloudhost247_cart_recovery_suppressions')->where(function($q)use($r){$q->where('email',$r->email);if($r->client_id)$q->orWhere('client_id',$r->client_id);})->exists()){ $out['skipped']++; Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('id',$r->id)->update(array('next_reminder_at'=>null,'status'=>'unsubscribed'===($r->status??'')?'unsubscribed':'expired','updated_at'=>$now)); continue; }
            // Atomic claim: unique recovery/reminder key makes duplicate cron execution harmless.
            $prior=Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->where('recovery_id',$r->id)->where('reminder_number',$n)->first(); if($prior && $prior->status==='sent'){ $out['skipped']++; continue; } try { if($prior) Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->where('id',$prior->id)->update(array('status'=>'pending','updated_at'=>$now)); else Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->insert(array('recovery_id'=>$r->id,'reminder_number'=>$n,'email'=>$r->email,'template_name'=>EmailService::template($n),'status'=>'pending','created_at'=>$now,'updated_at'=>$now)); } catch(\Throwable $e) { $out['skipped']++; continue; } $claimed=Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->where('recovery_id',$r->id)->where('reminder_number',$n)->whereIn('status',array('pending','failed'))->update(array('status'=>'sending','updated_at'=>$now)); if(!$claimed){$out['skipped']++;continue;}
            try { $token=TokenService::open($r->token_ciphertext); $base=defined('CONFIG_SystemURL')?rtrim(CONFIG_SystemURL,'/'):(isset($_SERVER['HTTP_HOST'])?'https://'.$_SERVER['HTTP_HOST']:''); $url=$base.'/modules/addons/cloudhost247_cart_recovery/recover.php?token='.rawurlencode($token); $unsub=$url.'&action=unsubscribe'; EmailService::send($r,$n,$url,$unsub); Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->where('recovery_id',$r->id)->where('reminder_number',$n)->update(array('status'=>'sent','sent_at'=>$now,'updated_at'=>$now)); $next=$n<(int)SettingsRepository::get('maximum_reminders')?date('Y-m-d H:i:s',time()+(int)SettingsRepository::get('reminder_'.$n.'_delay')):null; Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('id',$r->id)->update(array('last_reminder_number'=>$n,'last_reminder_at'=>$now,'next_reminder_at'=>$next,'updated_at'=>$now)); $out['sent']++; } catch(\Throwable $e) { Capsule::table('mod_cloudhost247_cart_recovery_reminder_logs')->where('recovery_id',$r->id)->where('reminder_number',$n)->update(array('status'=>'failed','failed_at'=>$now,'error_message'=>substr($e->getMessage(),0,500),'updated_at'=>$now)); Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->where('id',$r->id)->update(array('next_reminder_at'=>date('Y-m-d H:i:s',time()+3600),'updated_at'=>$now)); $out['failed']++; }
        }
        Capsule::table('mod_cloudhost247_cart_recovery_recoveries')->whereIn('status',array('abandoned','recovered'))->where('token_expires_at','<=',$now)->update(array('status'=>'expired','next_reminder_at'=>null,'updated_at'=>$now)); return $out;
    }
}
