<?php
namespace CloudHost247\NetworkTools\Core\Registry\Catalog;

use CloudHost247\NetworkTools\Core\Registry\ToolDefinition;
use CloudHost247\NetworkTools\Core\Registry\ToolField;

/**
 * DNS tools (docs sections 4-15, 49).
 */
final class DnsCatalog
{
    public static function definitions()
    {
        $recordTypes = array(
            'A' => 'A', 'AAAA' => 'AAAA', 'CNAME' => 'CNAME', 'MX' => 'MX', 'NS' => 'NS', 'PTR' => 'PTR',
            'SRV' => 'SRV', 'SOA' => 'SOA', 'TXT' => 'TXT', 'CAA' => 'CAA', 'DS' => 'DS', 'DNSKEY' => 'DNSKEY',
        );

        return array(
            'dns/lookup' => array(
                'name' => 'DNS Lookup',
                'category' => 'dns',
                'icon' => 'search',
                'summary' => 'Inspect the DNS records a domain publishes, through a resolver you choose.',
                'description' => 'Queries one record type for a name and shows the raw records, TTLs and the resolver that answered. Every value is the answer the resolver actually returned.',
                'explanation' => 'Records are the authoritative data for a name. TTL is how long a resolver may cache the answer, so a recent change can take up to one TTL to become visible everywhere.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'placeholder' => 'example.com', 'target' => true, 'maxlength' => 253),
                    array('name' => 'type', 'type' => 'select', 'label' => 'Record type', 'required' => true, 'default' => 'A', 'options' => $recordTypes),
                    array('name' => 'resolver', 'type' => 'select', 'label' => 'Resolver', 'required' => false, 'default' => '', 'options' => array('' => 'CloudHost247 default (system resolver)'), 'help' => 'Additional resolvers are listed when the registered resolver set is available.'),
                    array('name' => 'include_authority', 'type' => 'checkbox', 'label' => 'Include authority section', 'default' => false),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\LookupService',
                'target_field' => 'domain',
                'cache_seconds' => 120,
                'exports' => array('json', 'csv', 'pdf', 'png'),
                'result_view' => 'records',
                'notes' => array('Do not store sensitive data in TXT records and expect it to stay private: DNS is public by design.'),
            ),
            'dns/propagation' => array(
                'name' => 'DNS Propagation Checker',
                'category' => 'dns',
                'icon' => 'globe',
                'summary' => 'Check a record from several independent public resolvers and compare the answers.',
                'description' => 'Queries the same record from each resolver in the CloudHost247 resolver registry and reports what each one returned, how long it took and whether it matches your expected value.',
                'explanation' => 'This shows what the resolvers CloudHost247 queried are returning right now. It is not a claim about the whole internet: other resolvers, caches and network paths can still hold an older answer until its TTL expires.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'placeholder' => 'example.com', 'target' => true),
                    array('name' => 'type', 'type' => 'select', 'label' => 'Record type', 'required' => true, 'default' => 'A', 'options' => $recordTypes),
                    array('name' => 'expected', 'type' => 'text', 'label' => 'Expected value', 'required' => false, 'help' => 'Optional. Used to classify each answer as propagated, mismatched or missing.', 'maxlength' => 255),
                    array('name' => 'match_mode', 'type' => 'select', 'label' => 'Match mode', 'required' => false, 'default' => 'exact', 'options' => array('exact' => 'Exact match', 'contains' => 'Contains', 'regex' => 'Regular expression')),
                    array('name' => 'ip_family', 'type' => 'select', 'label' => 'Resolver family', 'required' => false, 'default' => 'all', 'options' => array('all' => 'IPv4 and IPv6', 'v4' => 'IPv4 only', 'v6' => 'IPv6 only')),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\PropagationService',
                'target_field' => 'domain',
                'rate_tier' => 'standard',
                'timeout_seconds' => 30,
                'cache_seconds' => 60,
                'exports' => array('json', 'csv', 'pdf', 'png', 'svg'),
                'result_view' => 'propagation',
                'notes' => array(
                    'Results describe the resolvers queried, not every resolver on the internet.',
                    'Resolver locations are anycast points of presence and are approximate.',
                ),
            ),
            'dns/health' => array(
                'name' => 'DNS Health Checker',
                'category' => 'dns',
                'icon' => 'heart',
                'summary' => 'Run a structured DNS diagnostic: delegation, records, DNSSEC and TTL consistency.',
                'description' => 'Checks nameservers, delegation, A/AAAA/CNAME, MX, SPF, DKIM (when a selector is supplied), DMARC, CAA, DNSSEC, SOA and TTL consistency, then reports PASS/WARNING/ERROR per check with an explanation.',
                'explanation' => 'Each check is reported separately with the evidence that produced it. A domain is never labelled "secure" because records merely exist — DNSSEC, TLS and email authentication are judged on their own evidence.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'dkim_selector', 'type' => 'dkim_selector', 'label' => 'DKIM selector', 'required' => false, 'placeholder' => 'default'),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\HealthService',
                'target_field' => 'domain',
                'timeout_seconds' => 30,
                'cache_seconds' => 180,
                'exports' => array('json', 'csv', 'pdf', 'png'),
                'result_view' => 'checks',
            ),
            'dns/mx' => array(
                'name' => 'MX Lookup',
                'category' => 'dns',
                'icon' => 'mail',
                'summary' => 'List mail exchangers with priority, addresses, reverse DNS and reachability.',
                'description' => 'Resolves MX records, then each exchanger host to IPv4/IPv6, checks reverse DNS and tests whether the mail service answers on port 25.',
                'explanation' => 'Lower priority numbers are tried first. A hostname without a forward-confirmed reverse entry is more likely to be rejected by receiving mail servers.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'check_reachability', 'type' => 'checkbox', 'label' => 'Test port 25 reachability', 'default' => true, 'help' => 'Outbound port 25 is blocked by many hosting providers; when it is, the check reports that rather than a failure.'),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\MxService',
                'target_field' => 'domain',
                'cache_seconds' => 300,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'records',
            ),
            'dns/spf' => array(
                'name' => 'SPF Checker',
                'category' => 'dns',
                'icon' => 'shield',
                'summary' => 'Parse and validate a domain\'s SPF policy, including the DNS lookup count.',
                'description' => 'Validates SPF syntax, detects multiple SPF records, expands include/redirect chains, counts the DNS lookups the RFC 7208 limit applies to and explains each mechanism.',
                'explanation' => 'SPF tells receivers which hosts may send mail for a domain. More than ten DNS-lookup mechanisms, or more than one SPF record, causes a permanent error at many receivers.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'expand', 'type' => 'checkbox', 'label' => 'Expand include chains', 'default' => true, 'help' => 'Counts the lookups each include adds and reports which ones failed.'),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\SpfService',
                'target_field' => 'domain',
                'cache_seconds' => 300,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'checks',
            ),
            'dns/dmarc' => array(
                'name' => 'DMARC Checker',
                'category' => 'dns',
                'icon' => 'shield',
                'summary' => 'Inspect and validate the DMARC policy published at _dmarc.',
                'description' => 'Reads the DMARC record, validates every tag, explains the policy in plain language and reports alignment/reporting configuration problems.',
                'explanation' => 'DMARC combines SPF and DKIM results with alignment and tells receivers what to do when both fail. A policy of p=none only asks for reports; it does not block anything.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\DmarcService',
                'target_field' => 'domain',
                'cache_seconds' => 300,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'checks',
            ),
            'dns/dkim' => array(
                'name' => 'DKIM Checker',
                'category' => 'dns',
                'icon' => 'key',
                'summary' => 'Check the DKIM public key published for one or more selectors.',
                'description' => 'Looks up selector._domainkey.domain, validates the DKIM key record syntax, decodes the public key and reports the key type, flags and any syntax problems.',
                'explanation' => 'A published key proves that whoever holds the matching private key can sign mail for that selector. A missing or revoked key (p= empty) is reported as such rather than as valid.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'selectors', 'type' => 'text', 'label' => 'Selectors', 'required' => true, 'default' => 'default', 'placeholder' => 'default, google, selector1', 'help' => 'Comma-separated. Each selector is checked independently.', 'maxlength' => 255),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\DkimService',
                'target_field' => 'domain',
                'cache_seconds' => 300,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'checks',
            ),
            'dns/dmarc-generator' => array(
                'name' => 'DMARC Record Generator',
                'category' => 'dns',
                'icon' => 'wand',
                'summary' => 'Build a valid DMARC TXT record from a guided form.',
                'description' => 'Produces the DMARC record value and the host it must be published at. Validation happens locally: nothing is queried and nothing is stored.',
                'explanation' => 'The generated record is a suggestion built from the options you chose. Review the reporting addresses before you publish it.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'policy', 'type' => 'select', 'label' => 'Policy (p)', 'required' => true, 'default' => 'none', 'options' => array('none' => 'none — monitor only', 'quarantine' => 'quarantine — treat as suspicious', 'reject' => 'reject — refuse the message')),
                    array('name' => 'subdomain_policy', 'type' => 'select', 'label' => 'Subdomain policy (sp)', 'required' => false, 'default' => '', 'options' => array('' => 'Inherit from p', 'none' => 'none', 'quarantine' => 'quarantine', 'reject' => 'reject')),
                    array('name' => 'percentage', 'type' => 'number', 'label' => 'Percentage (pct)', 'required' => false, 'default' => 100, 'min' => 0, 'max' => 100),
                    array('name' => 'rua', 'type' => 'text', 'label' => 'Aggregate report address (rua)', 'required' => false, 'placeholder' => 'mailto:dmarc@example.com', 'maxlength' => 255),
                    array('name' => 'ruf', 'type' => 'text', 'label' => 'Forensic report address (ruf)', 'required' => false, 'placeholder' => 'mailto:forensic@example.com', 'maxlength' => 255),
                    array('name' => 'adkim', 'type' => 'select', 'label' => 'DKIM alignment (adkim)', 'required' => false, 'default' => 'r', 'options' => array('r' => 'relaxed', 's' => 'strict')),
                    array('name' => 'aspf', 'type' => 'select', 'label' => 'SPF alignment (aspf)', 'required' => false, 'default' => 'r', 'options' => array('r' => 'relaxed', 's' => 'strict')),
                    array('name' => 'fo', 'type' => 'select', 'label' => 'Failure reporting (fo)', 'required' => false, 'default' => '0', 'options' => array('0' => '0 — both SPF and DKIM fail', '1' => '1 — either fails', 'd' => 'd — DKIM fails', 's' => 's — SPF fails')),
                    array('name' => 'ri', 'type' => 'number', 'label' => 'Report interval (ri)', 'required' => false, 'default' => 86400, 'min' => 0, 'max' => 604800, 'help' => 'Seconds between aggregate reports. 86400 is the default receivers assume.'),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\DmarcGeneratorService',
                'target_field' => 'domain',
                'rate_tier' => 'local',
                'cache_seconds' => 0,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'generated',
            ),
            'dns/dnskey' => array(
                'name' => 'DNSKEY Lookup',
                'category' => 'dns',
                'icon' => 'key',
                'summary' => 'Show the DNSSEC keys published for a zone.',
                'description' => 'Returns every DNSKEY with its key tag, algorithm, flags, protocol and Base64 public key, and reports whether a validating resolver accepts the zone.',
                'explanation' => 'The key tag identifies a key; flags bit 256 marks a zone-signing key and 257 a key-signing key. A published key alone does not prove the chain of trust — the DS record at the parent must match it.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\DnssecService',
                'method' => 'dnskey',
                'target_field' => 'domain',
                'cache_seconds' => 600,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'records',
            ),
            'dns/ds' => array(
                'name' => 'DS Lookup',
                'category' => 'dns',
                'icon' => 'lock',
                'summary' => 'Show the delegation signer records and the DNSSEC chain state.',
                'description' => 'Reads the DS records published by the parent zone, matches them against the child zone keys and reports whether the chain of trust is complete.',
                'explanation' => 'DS records publish a hash of the child\'s key-signing key. If the DS digest does not match a DNSKEY in the child zone, validating resolvers consider the zone bogus.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\DnssecService',
                'method' => 'ds',
                'target_field' => 'domain',
                'cache_seconds' => 600,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'records',
            ),
            'dns/reverse' => array(
                'name' => 'Reverse DNS (PTR) Lookup',
                'category' => 'dns',
                'icon' => 'refresh',
                'summary' => 'Find the hostname published for an IPv4 or IPv6 address.',
                'description' => 'Builds the in-addr.arpa / ip6.arpa name for the address, reads the PTR record and, where a forward record exists, confirms it points back to the same address.',
                'explanation' => 'Reverse DNS is configured by whoever owns the address block, not by the domain owner. Forward-confirmed reverse DNS (FCrDNS) means the PTR name resolves back to the same IP.',
                'fields' => array(
                    array('name' => 'ip', 'type' => 'ip', 'label' => 'IP address', 'required' => true, 'placeholder' => '192.0.2.10 or 2001:db8::10', 'target' => true),
                    array('name' => 'confirm_forward', 'type' => 'checkbox', 'label' => 'Confirm forward DNS', 'default' => true),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\ReverseService',
                'method' => 'ptr',
                'target_field' => 'ip',
                'cache_seconds' => 300,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'records',
            ),
            'dns/reverse-ip' => array(
                'name' => 'Reverse IP Lookup',
                'category' => 'dns',
                'icon' => 'exchange',
                'summary' => 'Show hostnames that the configured data sources associate with an IP address.',
                'description' => 'Uses the reverse-DNS name, the resolver\'s own PTR data and, when a passive-DNS provider is configured in API & Integrations, that provider\'s observed associations.',
                'explanation' => 'There is no DNS mechanism that lists every domain on an IP address. This tool reports only what a supported source actually returns, and says so when that source is not configured.',
                'fields' => array(
                    array('name' => 'ip', 'type' => 'public_ip', 'label' => 'IP address', 'required' => true, 'placeholder' => '192.0.2.10', 'target' => true),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\ReverseService',
                'method' => 'reverseIp',
                'target_field' => 'ip',
                'providers' => array('ipinfo', 'ipwhoapi'),
                'cache_seconds' => 600,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'records',
                'notes' => array('A reverse-IP listing can never be complete: only sources that publish passive-DNS observations can answer it.'),
            ),
            'dns/bimi' => array(
                'name' => 'BIMI Checker',
                'category' => 'dns',
                'icon' => 'image',
                'summary' => 'Check the BIMI record and the logo it points at.',
                'description' => 'Reads the BIMI TXT record at default._bimi, validates the version/logo/certificate tags, explains the DMARC and VMC requirements, and verifies that the logo URL is reachable over HTTPS.',
                'explanation' => 'BIMI makes a verified logo appear next to authenticated mail. Receivers require DMARC enforcement (p=quarantine or p=reject) and, for most mailbox providers, a Verified Mark Certificate.',
                'fields' => array(
                    array('name' => 'domain', 'type' => 'domain', 'label' => 'Domain', 'required' => true, 'target' => true),
                    array('name' => 'selector', 'type' => 'selector', 'label' => 'BIMI selector', 'required' => false, 'default' => 'default'),
                ),
                'handler' => 'CloudHost247\\NetworkTools\\Services\\Dns\\BimiService',
                'target_field' => 'domain',
                'cache_seconds' => 600,
                'exports' => array('json', 'csv', 'pdf'),
                'result_view' => 'checks',
            ),
        );
    }
}
