<?php
namespace CloudHost247\Ovh\Migrations;use CloudHost247\Foundation\Contracts\Migration;use WHMCS\Database\Capsule;
final class OvhOperationalMigration implements Migration
{public function version(){return'1.1.0';}public function description(){return'Create OVH catalog, product, service, operation, audit and lock tables';}public function up(){
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_catalog'))Capsule::schema()->create('mod_cloudhost247_ovh_catalog',function($t){$t->bigIncrements('id');$t->unsignedBigInteger('endpoint_id');$t->string('family',32);$t->string('plan_code',191);$t->string('invoice_name',255)->nullable();$t->string('currency',3)->nullable();$t->text('catalog_json');$t->boolean('available')->default(true);$t->dateTime('last_seen_at');$t->unique(array('endpoint_id','family','plan_code'),'ch247_ovh_catalog_unique');});
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_product_mappings'))Capsule::schema()->create('mod_cloudhost247_ovh_product_mappings',function($t){$t->bigIncrements('id');$t->unsignedInteger('whmcs_product_id')->unique();$t->unsignedBigInteger('endpoint_id');$t->string('family',32);$t->string('plan_code',191);$t->string('subsidiary',16);$t->text('configuration_json')->nullable();$t->boolean('active')->default(false);$t->decimal('margin_percent',10,4)->default(0);$t->dateTime('updated_at');});
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_services'))Capsule::schema()->create('mod_cloudhost247_ovh_services',function($t){$t->bigIncrements('id');$t->unsignedInteger('whmcs_service_id')->unique();$t->unsignedBigInteger('endpoint_id');$t->string('family',32);$t->string('remote_service_name',191)->nullable()->index();$t->string('remote_order_id',191)->nullable()->index();$t->string('status',64)->default('pending');$t->text('details_json')->nullable();$t->dateTime('last_synced_at')->nullable();$t->dateTime('updated_at');});
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_operations'))Capsule::schema()->create('mod_cloudhost247_ovh_operations',function($t){$t->bigIncrements('id');$t->unsignedInteger('whmcs_service_id')->nullable()->index();$t->string('operation',64);$t->string('idempotency_key',64)->unique();$t->string('status',32)->index();$t->string('remote_id',191)->nullable();$t->text('request_json')->nullable();$t->text('response_json')->nullable();$t->text('error_message')->nullable();$t->unsignedInteger('attempts')->default(0);$t->dateTime('created_at');$t->dateTime('updated_at');});
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_sync_runs'))Capsule::schema()->create('mod_cloudhost247_ovh_sync_runs',function($t){$t->bigIncrements('id');$t->string('sync_type',32);$t->string('status',24);$t->unsignedInteger('created_count')->default(0);$t->unsignedInteger('updated_count')->default(0);$t->unsignedInteger('unchanged_count')->default(0);$t->unsignedInteger('failed_count')->default(0);$t->unsignedInteger('skipped_count')->default(0);$t->text('error_message')->nullable();$t->dateTime('started_at');$t->dateTime('finished_at')->nullable();});
 if(!Capsule::schema()->hasTable('mod_cloudhost247_ovh_locks'))Capsule::schema()->create('mod_cloudhost247_ovh_locks',function($t){$t->string('lock_name',64)->primary();$t->string('owner',64);$t->dateTime('locked_until');$t->dateTime('updated_at');});
}}
