import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../components/CatalogStateBanner';
import StatusBadge from '../components/StatusBadge';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';

interface Os {id:string;name:string;slug:string}
interface Version {id:string;version:string;display_name:string;release_name:string|null;architecture_support:string[];status:string;is_default:boolean;is_recommended:boolean;is_lts:boolean;release_date:string|null;end_of_life_date:string|null;provider_image_count:number;active_image_count:number;available_region_count:number}
export default function AdminOsVersionsPage(){
 const {slug=''}=useParams();usePageMeta('OS versions','Admin — operating-system versions and lifecycle.');
 const [os,setOs]=useState<Os|null>(null);const [versions,setVersions]=useState<Version[]|null>(null);const [error,setError]=useState('');const [show,setShow]=useState(false);const [editing,setEditing]=useState<Version|null>(null);
 const [form,setForm]=useState({version:'',displayName:'',releaseName:'',x86:true,arm:false,isLts:false,releaseDate:'',endOfLifeDate:''});
 const load=useCallback(()=>apiFetch<{operatingSystem:Os;versions:Version[]}>(`/api/v1/admin/operating-systems/${slug}/versions`).then((result)=>{setOs(result.operatingSystem);setVersions(result.versions);}).catch((cause:Error)=>setError(cause.message)),[slug]);useEffect(()=>{load();},[load]);
 async function create(event:FormEvent){event.preventDefault();if(!os)return;try{const body={displayName:form.displayName,releaseName:form.releaseName||null,architectureSupport:[form.x86&&'x86_64',form.arm&&'arm64'].filter(Boolean),isLts:form.isLts,releaseDate:form.releaseDate||null,endOfLifeDate:form.endOfLifeDate||null};if(editing)await apiFetch(`/api/v1/admin/operating-system-versions/${editing.id}`,{method:'PATCH',body:JSON.stringify(body)});else await apiFetch(`/api/v1/admin/operating-systems/${os.id}/versions`,{method:'POST',body:JSON.stringify({...body,version:form.version,status:'DISABLED'})});setShow(false);setEditing(null);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Save failed');}}
 function edit(version:Version){setEditing(version);setShow(true);setForm({version:version.version,displayName:version.display_name,releaseName:version.release_name??'',x86:version.architecture_support.includes('x86_64'),arm:version.architecture_support.includes('arm64'),isLts:version.is_lts,releaseDate:version.release_date??'',endOfLifeDate:version.end_of_life_date??''});}
 async function patch(version:Version,body:Record<string,unknown>){try{await apiFetch(`/api/v1/admin/operating-system-versions/${version.id}`,{method:'PATCH',body:JSON.stringify(body)});await load();}catch(cause){setError(cause instanceof Error?cause.message:'Update failed');}}
 return <div className="ch247-stack"><section className="ch247-card ch247-section-heading"><div><Link to="/admin/infrastructure/operating-systems">← Operating systems</Link><h1>{os?.name??'Operating system'} versions</h1><p className="ch247-page__hint">EOL and archived versions remain visible on existing servers but are excluded from new deployments.</p></div><button className="ch247-btn ch247-btn--primary" onClick={()=>{setShow((current)=>!current);setEditing(null);}}>Add version</button></section>{error&&<CatalogErrorBanner message={error}/>} {!versions&&!error&&<CatalogLoadingBanner label="Loading versions…"/>}
 {show&&<form className="ch247-card ch247-form" onSubmit={create}><h2>{editing?'Edit version':'New version'}</h2><div className="ch247-form-grid"><label className="ch247-field">Version<input required disabled={!!editing} value={form.version} onChange={(e)=>setForm({...form,version:e.target.value})}/></label><label className="ch247-field">Display name<input required value={form.displayName} onChange={(e)=>setForm({...form,displayName:e.target.value})}/></label><label className="ch247-field">Release name<input value={form.releaseName} onChange={(e)=>setForm({...form,releaseName:e.target.value})}/></label><label className="ch247-field">Release date<input type="date" value={form.releaseDate} onChange={(e)=>setForm({...form,releaseDate:e.target.value})}/></label><label className="ch247-field">End of life<input type="date" value={form.endOfLifeDate} onChange={(e)=>setForm({...form,endOfLifeDate:e.target.value})}/></label></div><div className="ch247-fieldset"><label><input type="checkbox" checked={form.x86} onChange={(e)=>setForm({...form,x86:e.target.checked})}/>x86_64</label><label><input type="checkbox" checked={form.arm} onChange={(e)=>setForm({...form,arm:e.target.checked})}/>ARM64</label><label><input type="checkbox" checked={form.isLts} onChange={(e)=>setForm({...form,isLts:e.target.checked})}/>LTS</label></div><button className="ch247-btn ch247-btn--primary">{editing?'Save changes':'Create disabled'}</button></form>}
 {versions&&<section className="ch247-card"><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Version</th><th>Status</th><th>Architecture</th><th>Mappings / regions</th><th>Lifecycle</th><th>Actions</th></tr></thead><tbody>{versions.map((version)=><tr key={version.id}><td><strong>{version.display_name}</strong><br/><small>{version.release_name}{version.is_lts?' · LTS':''}{version.is_recommended?' · Recommended':''}{version.is_default?' · Default':''}</small></td><td><StatusBadge status={version.status}/></td><td>{version.architecture_support.join(' · ')}</td><td><strong>{version.active_image_count}</strong> active / {version.provider_image_count} total<br/><small>{version.available_region_count} available region{version.available_region_count===1?'':'s'}</small></td><td>{version.release_date??'—'} → {version.end_of_life_date??'Not set'}</td><td><div className="ch247-actions"><button className="ch247-btn" onClick={()=>edit(version)}>Edit</button><Link className="ch247-btn" to={`/admin/infrastructure/images?version=${version.id}`}>Images</Link>{version.status!=='ACTIVE'&&<button className="ch247-btn" onClick={()=>void patch(version,{status:'ACTIVE'})}>Activate</button>}<button className="ch247-btn" onClick={()=>void patch(version,{isRecommended:!version.is_recommended})}>{version.is_recommended?'Unrecommend':'Recommend'}</button><button className="ch247-btn" onClick={()=>void patch(version,{isDefault:true})}>Make default</button><button className="ch247-btn ch247-btn--danger" onClick={()=>void patch(version,{status:'ARCHIVED'})}>Retire</button></div></td></tr>)}</tbody></table></div></section>}
 </div>;
}
