import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../components/CatalogStateBanner';
import StatusBadge from '../components/StatusBadge';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';
interface ImageRow{id:string;provider_id:string;operating_system_version_id:string;provider_image_id:string|null;provider_template_id:string|null;architecture:string;region_id:string|null;datacenter_id:string|null;status:string;verified_at:string|null;verification_error:string|null;provider_name:string;os_display_name:string;region_name:string|null;datacenter_name:string|null}
interface Provider{id:string;name:string}
interface Region{id:string;provider_id:string;name:string;code:string}
interface Os{id:string;name:string;slug:string}
interface Version{id:string;display_name:string;architecture_support:string[]}
export default function AdminOsImagesPage(){
 usePageMeta('OS images','Admin — provider image mappings.');const[params]=useSearchParams();const[images,setImages]=useState<ImageRow[]|null>(null);const[providers,setProviders]=useState<Provider[]>([]);const[regions,setRegions]=useState<Region[]>([]);const[versions,setVersions]=useState<Version[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState('');const[show,setShow]=useState(false);
 const[form,setForm]=useState({providerId:'',operatingSystemVersionId:params.get('version')??'',providerImageId:'',providerTemplateId:'',architecture:'x86_64',regionId:''});
 const load=useCallback(async()=>{try{const [imageResult,providerResult,osResult]=await Promise.all([apiFetch<{images:ImageRow[]}>('/api/v1/admin/os-images'),apiFetch<{providers:Provider[];regions:Region[]}>('/api/v1/admin/providers'),apiFetch<{operatingSystems:Os[]}>('/api/v1/admin/operating-systems')]);setImages(imageResult.images);setProviders(providerResult.providers);setRegions(providerResult.regions);const all:Version[]=[];for(const os of osResult.operatingSystems){const result=await apiFetch<{versions:Version[]}>(`/api/v1/admin/operating-systems/${os.id}/versions`);all.push(...result.versions);}setVersions(all);setForm((current)=>({...current,providerId:current.providerId||providerResult.providers[0]?.id||'',operatingSystemVersionId:current.operatingSystemVersionId||all[0]?.id||''}));}catch(cause){setError(cause instanceof Error?cause.message:'Load failed');}},[]);useEffect(()=>{void load();},[load]);
 async function create(event:FormEvent){event.preventDefault();try{await apiFetch('/api/v1/admin/os-images',{method:'POST',body:JSON.stringify({...form,providerImageId:form.providerImageId||null,providerTemplateId:form.providerTemplateId||null,regionId:form.regionId||null})});setShow(false);setMessage('Image mapping created as draft. Test it against the provider before enabling.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Create failed');}}
 async function operation(image:ImageRow,action:'test'|'enable'|'disable'|'delete'){setBusy(`${action}:${image.id}`);setError('');try{if(action==='test')await apiFetch(`/api/v1/admin/os-images/${image.id}/test`,{method:'POST',body:'{}'});else if(action==='delete')await apiFetch(`/api/v1/admin/os-images/${image.id}`,{method:'DELETE'});else await apiFetch(`/api/v1/admin/os-images/${image.id}`,{method:'PATCH',body:JSON.stringify({status:action==='enable'?'ACTIVE':'DISABLED'})});setMessage(action==='test'?'Provider confirmed the image exists.':`Image ${action}d.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:`Image ${action} failed`);}finally{setBusy('');}}
 return <div className="ch247-stack"><section className="ch247-card ch247-section-heading"><div><span className="ch247-eyebrow">Admin · Infrastructure</span><h1>Provider OS images</h1><p className="ch247-page__hint">Private provider identifiers map to customer-facing OS versions. They are never returned by public configuration APIs.</p></div><button className="ch247-btn ch247-btn--primary" onClick={()=>setShow((current)=>!current)}>Add image mapping</button></section><nav className="ch247-infra-nav"><Link to="/admin/infrastructure/operating-systems">Operating systems</Link><Link className="is-active" to="/admin/infrastructure/images">OS images</Link><Link to="/admin/infrastructure/providers">Providers & regions</Link><Link to="/admin/infrastructure/availability">Availability</Link><Link to="/admin/infrastructure/provisioning">Provisioning</Link></nav>
 {error&&<CatalogErrorBanner message={error}/>} {message&&<p className="ch247-banner ch247-banner--info">{message}</p>} {!images&&!error&&<CatalogLoadingBanner label="Loading image mappings…"/>}
 {show&&<form className="ch247-card ch247-form" onSubmit={create}><h2>New provider mapping</h2><div className="ch247-form-grid"><label className="ch247-field">Provider<select required value={form.providerId} onChange={(e)=>setForm({...form,providerId:e.target.value,regionId:''})}>{providers.map((provider)=><option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="ch247-field">OS version<select required value={form.operatingSystemVersionId} onChange={(e)=>setForm({...form,operatingSystemVersionId:e.target.value})}>{versions.map((version)=><option key={version.id} value={version.id}>{version.display_name}</option>)}</select></label><label className="ch247-field">Architecture<select value={form.architecture} onChange={(e)=>setForm({...form,architecture:e.target.value})}><option>x86_64</option><option>arm64</option></select></label><label className="ch247-field">Region<select value={form.regionId} onChange={(e)=>setForm({...form,regionId:e.target.value})}><option value="">All provider regions</option>{regions.filter((region)=>region.provider_id===form.providerId).map((region)=><option key={region.id} value={region.id}>{region.name} · {region.code}</option>)}</select></label><label className="ch247-field">Provider image ID<input value={form.providerImageId} onChange={(e)=>setForm({...form,providerImageId:e.target.value})}/></label><label className="ch247-field">Provider template ID<input value={form.providerTemplateId} onChange={(e)=>setForm({...form,providerTemplateId:e.target.value})}/></label></div><p className="ch247-page__hint">Supply the identifier required by this adapter. At least one identifier is required.</p><button className="ch247-btn ch247-btn--primary">Create draft mapping</button></form>}
 {images&&<section className="ch247-card"><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Operating system</th><th>Provider / location</th><th>Architecture</th><th>Private identifier</th><th>Status</th><th>Actions</th></tr></thead><tbody>{images.map((image)=><tr key={image.id}><td><strong>{image.os_display_name}</strong></td><td>{image.provider_name}<br/><small>{image.region_name??'All regions'}{image.datacenter_name?` · ${image.datacenter_name}`:''}</small></td><td>{image.architecture}</td><td><code>{image.provider_image_id??image.provider_template_id}</code></td><td><StatusBadge status={image.status}/><br/><small>{image.verified_at?`Verified ${new Date(image.verified_at).toLocaleDateString()}`:image.verification_error??'Not tested'}</small></td><td><div className="ch247-actions"><button className="ch247-btn" disabled={busy!==''} onClick={()=>void operation(image,'test')}>Test</button>{image.status!=='ACTIVE'?<button className="ch247-btn" disabled={busy!==''||!image.verified_at} onClick={()=>void operation(image,'enable')}>Enable</button>:<button className="ch247-btn" disabled={busy!==''} onClick={()=>void operation(image,'disable')}>Disable</button>}<button className="ch247-btn ch247-btn--danger" disabled={busy!==''||image.status==='ACTIVE'} onClick={()=>void operation(image,'delete')}>Delete</button></div></td></tr>)}</tbody></table></div></section>}
 </div>;
}
