import { FormEvent,useEffect,useState } from 'react';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';
type Conversation={id:string;status:string;visitor_name:string|null;visitor_email:string|null;customer_account_email:string|null;assigned_agent_email:string|null;escalation_reason:string|null;priority:string;updated_at:string};
type Message={id:string;author_type:string;body:string;created_at:string};
export default function AdminAiSupportPage(){usePageMeta('AI Support','Manage AI conversations and human handoffs.');const[items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[reply,setReply]=useState(''),[filter,setFilter]=useState(''),[overview,setOverview]=useState<any>(null),[error,setError]=useState('');
 async function load(){try{const [list,stats]=await Promise.all([apiFetch<{conversations:Conversation[]}>(`/api/v1/admin/ai-support/conversations${filter?`?status=${filter}`:''}`),apiFetch('/api/v1/admin/ai-support/overview')]);setItems(list.conversations);setOverview(stats)}catch(e){setError(e instanceof Error?e.message:'Load failed')}}useEffect(()=>{void load()},[filter]);
 async function open(id:string){setSelected(id);const data=await apiFetch<{messages:Message[]}>(`/api/v1/admin/ai-support/conversations/${id}`);setMessages(data.messages)}
 async function send(e:FormEvent){e.preventDefault();if(!selected)return;await apiFetch(`/api/v1/admin/ai-support/conversations/${selected}/reply`,{method:'POST',body:JSON.stringify({message:reply})});setReply('');await open(selected);await load()}
 async function update(status:string){if(!selected)return;await apiFetch(`/api/v1/admin/ai-support/conversations/${selected}`,{method:'PATCH',body:JSON.stringify({status})});await open(selected);await load()}
 return <div className="ch247-stack"><section className="ch247-card"><h1>AI Support Overview</h1><p className="ch247-page__hint">Native deterministic assistance and human support handoffs.</p>{overview&&<div className="ch247-metric-grid"><article><small>Active AI</small><strong>{overview.counts.AI_ACTIVE??0}</strong></article><article><small>Waiting for human</small><strong>{overview.counts.WAITING_FOR_HUMAN??0}</strong></article><article><small>In progress</small><strong>{overview.counts.IN_PROGRESS??0}</strong></article><article><small>Resolved</small><strong>{overview.counts.RESOLVED??0}</strong></article><article><small>Newsletter</small><strong>{overview.newsletterSubscriptions}</strong></article></div>}<label>Status <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option>{['AI_ACTIVE','WAITING_FOR_HUMAN','ASSIGNED','IN_PROGRESS','WAITING_FOR_CUSTOMER','RESOLVED','CLOSED'].map(x=><option key={x}>{x}</option>)}</select></label>{error&&<p className="ch247-status-error">{error}</p>}</section><section className="ch247-card"><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Customer</th><th>Status</th><th>Reason</th><th>Assigned</th><th>Updated</th></tr></thead><tbody>{items.map(c=><tr key={c.id} onClick={()=>void open(c.id)}><td>{c.visitor_name??c.customer_account_email??c.visitor_email??'Visitor'}</td><td>{c.status}</td><td>{c.escalation_reason??'—'}</td><td>{c.assigned_agent_email??'Queue'}</td><td>{new Date(c.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>{selected&&<section className="ch247-card"><h2>Conversation</h2>{messages.map(m=><article key={m.id} className="ch247-ticket-message"><strong>{m.author_type}</strong><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}<form onSubmit={send} className="ch247-form"><textarea required value={reply} onChange={e=>setReply(e.target.value)}/><button>Reply as support</button></form><div className="ch247-actions"><button onClick={()=>void update('RESOLVED')}>Resolve</button><button onClick={()=>void update('AI_ACTIVE')}>Return to AI</button><button onClick={()=>void update('CLOSED')}>Close</button></div></section>}</div>}
