import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../components/CatalogStateBanner';
import InfrastructureNav from '../components/InfrastructureNav';
import StatusBadge from '../components/StatusBadge';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';
interface ImageRow{id:string;provider_id:string;operating_system_version_id:string;provider_image_id:string|null;provider_template_id:string|null;architecture:string;region_id:string|null;datacenter_id:string|null;status:string;verified_at:string|null;verification_error:string|null;provider_name:string;os_display_name:string;region_name:string|null;datacenter_name:string|null}
interface Provider{id:string;name:string}
interface Region{id:string;provider_id:string;name:string;code:string}
interface Datacenter{id:string;region_id:string;name:string;code:string;status:string}
interface Os{id:string;name:string;slug:string}
interface Version{id:string;display_name:string;architecture_support:string[]}
export default function AdminOsImagesPage(){
 usePageMeta('OS images','Admin — provider image mappings.');const[params]=useSearchParams();const versionFilter=params.get('version')??'';const osFilter=params.get('os')??'';const imageQuery=versionFilter?`?versionId=${encodeURIComponent(versionFilter)}`:osFilter?`?operatingSystemId=${encodeURIComponent(osFilter)}`:'';const[images,setImages]=useState<ImageRow[]|null>(null);const[providers,setProviders]=useState<Provider[]>([]);const[regions,setRegions]=useState<Region[]>([]);const[datacenters,setDatacenters]=useState<Datacenter[]>([]);const[versions,setVersions]=useState<Version[]>([]);const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState('');const[show,setShow]=useState(false);const[editing,setEditing]=useState<ImageRow|null>(null);const[revalidating,setRevalidating]=useState(false);
 const[form,setForm]=useState({providerId:'',operatingSystemVersionId:params.get('version')??'',providerImageId:'',providerTemplateId:'',architecture:'x86_64',regionId:'',datacenterId:''});
 const[filters,setFilters]=useState({search:'',providerId:'',architecture:'',status:''});
 const visibleImages=useMemo(()=>(images??[]).filter((image)=>{
   if(filters.providerId&&image.provider_id!==filters.providerId)return false;
   if(filters.architecture&&image.architecture!==filters.architecture)return false;
   if(filters.status&&image.status!==filters.status)return false;
   const needle=filters.search.trim().toLowerCase();
   if(needle&&!`${image.os_display_name} ${image.provider_name} ${image.region_name??''} ${image.datacenter_name??''} ${image.provider_image_id??''} ${image.provider_template_id??''}`.toLowerCase().includes(needle))return false;
   return true;
 }),[images,filters]);
 const load=useCallback(async()=>{try{const [imageResult,providerResult,osResult]=await Promise.all([apiFetch<{images:ImageRow[]}>(`/api/v1/admin/os-images${imageQuery}`),apiFetch<{providers:Provider[];regions:Region[];datacenters:Datacenter[]}>('/api/v1/admin/providers'),apiFetch<{operatingSystems:Os[]}>('/api/v1/admin/operating-systems')]);setImages(imageResult.images);setProviders(providerResult.providers);setRegions(providerResult.regions);setDatacenters(providerResult.datacenters);const all:Version[]=[];for(const os of osResult.operatingSystems){const result=await apiFetch<{versions:Version[]}>(`/api/v1/admin/operating-systems/${os.id}/versions`);all.push(...result.versions);}setVersions(all);setForm((current)=>({...current,providerId:current.providerId||providerResult.providers[0]?.id||'',operatingSystemVersionId:current.operatingSystemVersionId||all[0]?.id||''}));}catch(cause){setError(cause instanceof Error?cause.message:'Load failed');}},[imageQuery]);useEffect(()=>{void load();},[load]);
 /**
  * Re-checks every enabled mapping whose verification has gone stale. The worker does this every
  * six hours; this button is for operators who have just changed something at the provider.
  */
 async function revalidateAll(){setRevalidating(true);setError('');setMessage('');try{const result=await apiFetch<{results:Array<{outcome:string}>}>('/api/v1/admin/os-images/revalidate',{method:'POST',body:JSON.stringify({staleAfterDays:0})});const invalidated=result.results.filter((item)=>item.outcome==='INVALIDATED').length;const unreachable=result.results.filter((item)=>item.outcome==='PROVIDER_UNREACHABLE').length;setMessage(`Re-checked ${result.results.length} enabled mapping(s): ${invalidated} withdrawn by the provider, ${unreachable} could not be reached.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Re-check failed');}finally{setRevalidating(false);}}
 async function create(event:FormEvent){event.preventDefault();try{const body={providerImageId:form.providerImageId||null,providerTemplateId:form.providerTemplateId||null,architecture:form.architecture,regionId:form.regionId||null,datacenterId:form.datacenterId||null};if(editing){await apiFetch(`/api/v1/admin/os-images/${editing.id}`,{method:'PATCH',body:JSON.stringify(body)});setMessage('Image mapping updated as draft. Test it again before enabling.');}else{await apiFetch('/api/v1/admin/os-images',{method:'POST',body:JSON.stringify({...body,providerId:form.providerId,operatingSystemVersionId:form.operatingSystemVersionId})});setMessage('Image mapping created as draft. Test it against the provider before enabling.');}setShow(false);setEditing(null);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Save failed');}}
 function edit(image:ImageRow){setEditing(image);setShow(true);setForm({providerId:image.provider_id,operatingSystemVersionId:image.operating_system_version_id,providerImageId:image.provider_image_id??'',providerTemplateId:image.provider_template_id??'',architecture:image.architecture,regionId:image.region_id??'',datacenterId:image.datacenter_id??''});}
 async function operation(image:ImageRow,action:'test'|'enable'|'disable'|'delete'){setBusy(`${action}:${image.id}`);setError('');try{if(action==='test')await apiFetch(`/api/v1/admin/os-images/${image.id}/test`,{method:'POST',body:'{}'});else if(action==='delete')await apiFetch(`/api/v1/admin/os-images/${image.id}`,{method:'DELETE'});else await apiFetch(`/api/v1/admin/os-images/${image.id}`,{method:'PATCH',body:JSON.stringify({status:action==='enable'?'ACTIVE':'DISABLED'})});setMessage(action==='test'?'Provider confirmed the image exists.':`Image ${action}d.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:`Image ${action} failed`);}finally{setBusy('');}}
 return <div className="ch247-stack"><section className="ch247-card ch247-section-heading"><div><span className="ch247-eyebrow">Admin · Infrastructure</span><h1>Provider OS images</h1><p className="ch247-page__hint">Private provider identifiers map to customer-facing OS versions. They are never returned by public configuration APIs. Enabled mappings are re-checked against the provider every six hours; a withdrawn image is marked invalid and disappears from ordering before anyone can pay for it.</p></div><div className="ch247-actions"><button className="ch247-btn" disabled={revalidating} onClick={()=>void revalidateAll()}>{revalidating?'Re-checking…':'Re-check enabled mappings'}</button><button className="ch247-btn ch247-btn--primary" onClick={()=>{setShow((current)=>!current);setEditing(null);}}>Add image mapping</button></div></section><InfrastructureNav active="images"/>
 {error&&<CatalogErrorBanner message={error}/>} {message&&<p className="ch247-banner ch247-banner--info">{message}</p>} {!images&&!error&&<CatalogLoadingBanner label="Loading image mappings…"/>}
 {show&&<form className="ch247-card ch247-form" onSubmit={create}><h2>{editing?'Edit provider mapping':'New provider mapping'}</h2><div className="ch247-form-grid"><label className="ch247-field">Provider<select required disabled={Boolean(editing)} value={form.providerId} onChange={(e)=>setForm({...form,providerId:e.target.value,regionId:'',datacenterId:''})}>{providers.map((provider)=><option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="ch247-field">OS version<select required disabled={Boolean(editing)} value={form.operatingSystemVersionId} onChange={(e)=>setForm({...form,operatingSystemVersionId:e.target.value})}>{versions.map((version)=><option key={version.id} value={version.id}>{version.display_name}</option>)}</select></label><label className="ch247-field">Architecture<select value={form.architecture} onChange={(e)=>setForm({...form,architecture:e.target.value})}><option>x86_64</option><option>arm64</option></select></label><label className="ch247-field">Region<select value={form.regionId} onChange={(e)=>setForm({...form,regionId:e.target.value,datacenterId:''})}><option value="">All provider regions</option>{regions.filter((region)=>region.provider_id===form.providerId).map((region)=><option key={region.id} value={region.id}>{region.name} · {region.code}</option>)}</select></label><label className="ch247-field">Datacenter<select value={form.datacenterId} disabled={!form.regionId} onChange={(e)=>setForm({...form,datacenterId:e.target.value})}><option value="">All datacenters in scope</option>{datacenters.filter((dc)=>dc.region_id===form.regionId).map((dc)=><option key={dc.id} value={dc.id}>{dc.name} · {dc.code}{dc.status!=='ACTIVE'?' (disabled)':''}</option>)}</select></label><label className="ch247-field">Provider image ID<input value={form.providerImageId} onChange={(e)=>setForm({...form,providerImageId:e.target.value})}/></label><label className="ch247-field">Provider template ID<input value={form.providerTemplateId} onChange={(e)=>setForm({...form,providerTemplateId:e.target.value})}/></label></div><p className="ch247-page__hint">Supply the identifier required by this adapter. At least one identifier is required.</p><button className="ch247-btn ch247-btn--primary">{editing?'Save as draft':'Create draft mapping'}</button></form>}
 {images&&<section className="ch247-card"><div className="ch247-form-grid"><label className="ch247-field">Search<input value={filters.search} onChange={(e)=>setFilters({...filters,search:e.target.value})} placeholder="Search OS, provider, region, identifier…"/></label><label className="ch247-field">Provider<select value={filters.providerId} onChange={(e)=>setFilters({...filters,providerId:e.target.value})}><option value="">All providers</option>{providers.map((provider)=><option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="ch247-field">Architecture<select value={filters.architecture} onChange={(e)=>setFilters({...filters,architecture:e.target.value})}><option value="">All architectures</option><option value="x86_64">x86_64</option><option value="arm64">ARM64</option></select></label><label className="ch247-field">Status<select value={filters.status} onChange={(e)=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{['DRAFT','VALIDATING','ACTIVE','DISABLED','INVALID'].map((status)=><option key={status} value={status}>{status}</option>)}</select></label></div><p className="ch247-page__hint">Showing {visibleImages.length} of {images.length} mapping{images.length===1?'':'s'}.</p><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Operating system</th><th>Provider / location</th><th>Architecture</th><th>Private identifier</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleImages.map((image)=><tr key={image.id}><td><strong>{image.os_display_name}</strong></td><td>{image.provider_name}<br/><small>{image.region_name??'All regions'}{image.datacenter_name?` · ${image.datacenter_name}`:''}</small></td><td>{image.architecture}</td><td><code>{image.provider_image_id??image.provider_template_id}</code></td><td><StatusBadge status={image.status}/><br/><small>{image.verified_at?`Verified ${new Date(image.verified_at).toLocaleDateString()}`:image.verification_error??'Not tested'}</small></td><td><div className="ch247-actions"><button className="ch247-btn" disabled={busy!==''||image.status==='ACTIVE'} onClick={()=>edit(image)}>Edit</button><button className="ch247-btn" disabled={busy!==''} onClick={()=>void operation(image,'test')}>Test</button>{image.status!=='ACTIVE'?<button className="ch247-btn" disabled={busy!==''||!image.verified_at} onClick={()=>void operation(image,'enable')}>Enable</button>:<button className="ch247-btn" disabled={busy!==''} onClick={()=>void operation(image,'disable')}>Disable</button>}<button className="ch247-btn ch247-btn--danger" disabled={busy!==''||image.status==='ACTIVE'} onClick={()=>void operation(image,'delete')}>Delete</button></div></td></tr>)}{visibleImages.length===0&&<tr><td colSpan={6}><p className="ch247-banner ch247-banner--warning">No image mappings match these filters.</p></td></tr>}</tbody></table></div></section>}
 </div>;
}
