import { FormEvent, useCallback, useEffect, useState } from 'react';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../components/CatalogStateBanner';
import InfrastructureNav from '../components/InfrastructureNav';
import ProviderConfigurationPanel from '../components/ProviderConfigurationPanel';
import StatusBadge from '../components/StatusBadge';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';
interface Provider{id:string;name:string;slug:string;provider_type:string;adapter:string;status:string;api_base_url:string|null;credential_env_prefix:string|null;last_health_status:string|null}
interface Region{id:string;provider_id:string;code:string;name:string;country_code:string|null;status:string}
interface Datacenter{id:string;region_id:string;code:string;name:string;status:string}
export default function AdminProvidersPage(){
 usePageMeta('Providers & regions','Admin — infrastructure provider configuration.');const [data,setData]=useState<{providers:Provider[];regions:Region[];datacenters:Datacenter[]}|null>(null);const[error,setError]=useState('');const[message,setMessage]=useState('');const[show,setShow]=useState(false);
 const[configFor,setConfigFor]=useState('');const[form,setForm]=useState({name:'',slug:'',providerType:'HETZNER',adapter:'hetzner',apiBaseUrl:'',credentialEnvPrefix:'HETZNER'});const[region,setRegion]=useState({providerId:'',code:'',name:'',countryCode:''});const[datacenter,setDatacenter]=useState({regionId:'',code:'',name:''});
 const load=useCallback(()=>apiFetch<{providers:Provider[];regions:Region[];datacenters:Datacenter[]}>('/api/v1/admin/providers').then((result)=>{setData(result);if(!region.providerId&&result.providers[0])setRegion((current)=>({...current,providerId:result.providers[0]!.id}));if(!datacenter.regionId&&result.regions[0])setDatacenter((current)=>({...current,regionId:result.regions[0]!.id}));}).catch((cause:Error)=>setError(cause.message)),[region.providerId]);useEffect(()=>{load();},[load]);
 async function create(event:FormEvent){event.preventDefault();try{await apiFetch('/api/v1/admin/providers',{method:'POST',body:JSON.stringify({...form,status:'CONFIGURATION_REQUIRED',apiBaseUrl:form.apiBaseUrl||null})});setShow(false);setMessage('Provider created. Add credentials to server environment, restart, then validate/activate it.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Create failed');}}
 async function activate(provider:Provider){try{await apiFetch(`/api/v1/admin/providers/${provider.id}`,{method:'PATCH',body:JSON.stringify({status:provider.status==='ACTIVE'?'DISABLED':'ACTIVE'})});setMessage(provider.status==='ACTIVE'?'Provider disabled.':'Provider API validation passed and the provider is active.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Provider validation failed');}}
 async function addRegion(event:FormEvent){event.preventDefault();try{const result=await apiFetch<{region:Region}>('/api/v1/admin/regions',{method:'POST',body:JSON.stringify({...region,countryCode:region.countryCode||null})});setRegion({...region,code:'',name:'',countryCode:''});setDatacenter((current)=>({...current,regionId:result.region.id}));await load();}catch(cause){setError(cause instanceof Error?cause.message:'Region create failed');}}
 async function addDatacenter(event:FormEvent){event.preventDefault();try{await apiFetch('/api/v1/admin/datacenters',{method:'POST',body:JSON.stringify(datacenter)});setDatacenter({...datacenter,code:'',name:''});await load();}catch(cause){setError(cause instanceof Error?cause.message:'Datacenter create failed');}}
 return <div className="ch247-stack"><section className="ch247-card ch247-section-heading"><div><span className="ch247-eyebrow">Admin · Infrastructure</span><h1>Providers &amp; regions</h1><p className="ch247-page__hint">Credentials live only in server environment variables. Missing or unsupported adapters fail closed.</p></div><button className="ch247-btn ch247-btn--primary" onClick={()=>setShow((current)=>!current)}>Add provider</button></section><InfrastructureNav active="providers"/>
 {error&&<CatalogErrorBanner message={error}/>} {message&&<p className="ch247-banner ch247-banner--info">{message}</p>} {!data&&!error&&<CatalogLoadingBanner label="Loading providers…"/>}
 {show&&<form className="ch247-card ch247-form" onSubmit={create}><h2>New provider</h2><div className="ch247-form-grid"><label className="ch247-field">Name<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label className="ch247-field">Slug<input required value={form.slug} onChange={(e)=>setForm({...form,slug:e.target.value.toLowerCase()})}/></label><label className="ch247-field">Provider type<select value={form.providerType} onChange={(e)=>setForm({...form,providerType:e.target.value})}>{['HETZNER','OVH','PROXMOX','VIRTUALIZOR','SOLUSVM','OPENSTACK','AWS','DIGITALOCEAN','VULTR','CONTABO','GENERIC_HTTP','OTHER'].map((item)=><option key={item}>{item}</option>)}</select></label><label className="ch247-field">Adapter<select value={form.adapter} onChange={(e)=>setForm({...form,adapter:e.target.value})}>{['hetzner','ovh','proxmox','virtualizor','solusvm','openstack','aws','digitalocean','vultr','contabo','generic_http'].map((item)=><option key={item}>{item}</option>)}</select></label><label className="ch247-field">API base URL<input value={form.apiBaseUrl} onChange={(e)=>setForm({...form,apiBaseUrl:e.target.value})}/></label><label className="ch247-field">Credential environment prefix<input value={form.credentialEnvPrefix} onChange={(e)=>setForm({...form,credentialEnvPrefix:e.target.value.toUpperCase()})}/></label></div><button className="ch247-btn ch247-btn--primary">Create provider</button></form>}
 {data?.providers.map((provider)=><section className="ch247-card" key={provider.id}><div className="ch247-section-heading"><div><h2>{provider.name}</h2><p className="ch247-page__hint">{provider.provider_type} · {provider.adapter} · secrets: {provider.credential_env_prefix??provider.slug.toUpperCase()}</p></div><div className="ch247-actions"><StatusBadge status={provider.status}/><button className="ch247-btn" onClick={()=>setConfigFor((current)=>current===provider.id?'':provider.id)}>{configFor===provider.id?'Hide configuration':'Configuration'}</button><button className="ch247-btn" onClick={()=>void activate(provider)}>{provider.status==='ACTIVE'?'Disable':'Validate & activate'}</button></div></div>{configFor===provider.id&&<ProviderConfigurationPanel providerId={provider.id}/>}<div className="ch247-provider-regions">{data.regions.filter((item)=>item.provider_id===provider.id).map((item)=><div key={item.id}><strong>{item.name}</strong><small>{item.code}{item.country_code?` · ${item.country_code}`:''} · {item.status}</small><span>{data.datacenters.filter((dc)=>dc.region_id===item.id).length} datacenters</span></div>)}{data.regions.every((item)=>item.provider_id!==provider.id)&&<p className="ch247-page__hint">No regions configured.</p>}</div></section>)}
 {data&&data.providers.length>0&&<form className="ch247-card ch247-form" onSubmit={addRegion}><h2>Add region</h2><div className="ch247-form-grid"><label className="ch247-field">Provider<select value={region.providerId} onChange={(e)=>setRegion({...region,providerId:e.target.value})}>{data.providers.map((provider)=><option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="ch247-field">Provider region code<input required value={region.code} onChange={(e)=>setRegion({...region,code:e.target.value})}/></label><label className="ch247-field">Display name<input required value={region.name} onChange={(e)=>setRegion({...region,name:e.target.value})}/></label><label className="ch247-field">Country code<input maxLength={2} value={region.countryCode} onChange={(e)=>setRegion({...region,countryCode:e.target.value.toUpperCase()})}/></label></div><button className="ch247-btn">Add region</button></form>}
 {data&&data.regions.length>0&&<form className="ch247-card ch247-form" onSubmit={addDatacenter}><h2>Add datacenter</h2><div className="ch247-form-grid"><label className="ch247-field">Region<select value={datacenter.regionId} onChange={(e)=>setDatacenter({...datacenter,regionId:e.target.value})}>{data.regions.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="ch247-field">Provider datacenter code<input required value={datacenter.code} onChange={(e)=>setDatacenter({...datacenter,code:e.target.value})}/></label><label className="ch247-field">Display name<input required value={datacenter.name} onChange={(e)=>setDatacenter({...datacenter,name:e.target.value})}/></label></div><button className="ch247-btn">Add datacenter</button></form>}
 </div>;
}
