import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../components/CatalogStateBanner';
import InfrastructureNav from '../components/InfrastructureNav';
import StatusBadge from '../components/StatusBadge';
import { apiFetch } from '../lib/api';
import { usePageMeta } from '../lib/usePageMeta';
interface Job{id:string;deployment_id:string;server_id:string;operation:string;status:string;attempts:number;max_attempts:number;idempotency_key:string;retryable:boolean|null;provider_server_id:string|null;provider_response:Record<string,unknown>|null;error_code:string|null;error_message:string|null;started_at:string|null;completed_at:string|null;created_at:string;customer_email:string|null;server_name:string;provider_name:string;os_display_name:string|null;order_number:string|null;logs:Array<{at:string;level:string;stage:string;message:string;metadata?:Record<string,unknown>}>}
interface Metrics{total:number;ready:number;failed:number;average_duration_seconds:number;retries:number;queueDepth:number;stalledJobs:number;failuresByCode:Array<{code:string;count:number}>;providers:Array<{provider_id:string;provider_name:string;adapter:string;status:string;total:number;ready:number;failed:number;in_progress:number}>}
interface Detail{job:Job;steps:Array<{id:string;step_order:number;name:string;status:string;started_at:string|null;completed_at:string|null;output:string|null;error:string|null}>;events:Array<{id:string;level:string;message:string;created_at:string}>}
export default function AdminProvisioningPage(){
 usePageMeta('Provisioning','Admin — infrastructure job operations and observability.');const{id:routeId}=useParams();const[jobs,setJobs]=useState<Job[]|null>(null);const[detail,setDetail]=useState<Detail|null>(null);const[metrics,setMetrics]=useState<Metrics|null>(null);const[filter,setFilter]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState('');
 const load=useCallback(async()=>{try{const query=filter?`?status=${filter}`:'';const[jobResult,metricResult]=await Promise.all([apiFetch<{jobs:Job[]}>(`/api/v1/admin/provisioning-jobs${query}`),apiFetch<Metrics>('/api/v1/admin/provisioning-metrics')]);setJobs(jobResult.jobs);setMetrics(metricResult);const focus=routeId??detail?.job.id;if(focus)setDetail(await apiFetch<Detail>(`/api/v1/admin/provisioning-jobs/${focus}`));}catch(cause){setError(cause instanceof Error?cause.message:'Load failed');}},[filter,routeId,detail?.job.id]);useEffect(()=>{void load();},[filter,routeId]);
 async function action(job:Job,name:'retry'|'cancel'){setBusy(`${name}:${job.id}`);try{await apiFetch(`/api/v1/admin/provisioning-jobs/${job.id}/${name}`,{method:'POST',body:'{}'});await load();}catch(cause){setError(cause instanceof Error?cause.message:`Could not ${name} job`);}finally{setBusy('');}}
 return <div className="ch247-stack"><section className="ch247-card ch247-section-heading"><div><span className="ch247-eyebrow">Admin · Infrastructure</span><h1>Provisioning jobs</h1><p className="ch247-page__hint">Durable PostgreSQL queue, provider response time, retries, stage logs, and terminal failures.</p></div><label className="ch247-field">Status<select value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="">All statuses</option>{['QUEUED','ALLOCATING','CREATING','INSTALLING_OS','CONFIGURING','NETWORK_CONFIGURING','SECURITY_CONFIGURING','HEALTH_CHECK','READY','FAILED','CANCELLED'].map((item)=><option key={item}>{item}</option>)}</select></label></section><InfrastructureNav active="provisioning"/>
 {metrics&&<section className="ch247-metric-grid"><article><small>Total jobs</small><strong>{metrics.total}</strong></article><article><small>Success rate</small><strong>{metrics.total?Math.round(metrics.ready/metrics.total*100):0}%</strong></article><article><small>Failures</small><strong>{metrics.failed}</strong></article><article><small>Queue depth</small><strong>{metrics.queueDepth}</strong></article><article><small>Average duration</small><strong>{Math.round(metrics.average_duration_seconds??0)}s</strong></article><article><small>Retries</small><strong>{metrics.retries}</strong></article><article><small>Stalled &gt; 30m</small><strong>{metrics.stalledJobs}</strong></article></section>}
 {metrics&&metrics.failuresByCode.length>0&&<section className="ch247-card"><h2>Failures by error code</h2><p className="ch247-page__hint">Configuration errors are never retried automatically; transient errors are.</p><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Error code</th><th>Jobs</th></tr></thead><tbody>{metrics.failuresByCode.map((row)=><tr key={row.code}><td><code>{row.code}</code></td><td>{row.count}</td></tr>)}</tbody></table></div></section>}
 {metrics&&metrics.providers.length>0&&<section className="ch247-card"><h2>Provider health</h2><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Provider</th><th>Adapter</th><th>Status</th><th>Jobs</th><th>Ready</th><th>Failed</th><th>In progress</th></tr></thead><tbody>{metrics.providers.map((row)=><tr key={row.provider_id}><td>{row.provider_name}</td><td><code>{row.adapter}</code></td><td><StatusBadge status={row.status}/></td><td>{row.total}</td><td>{row.ready}</td><td className={row.failed>0?'ch247-error-text':undefined}>{row.failed}</td><td>{row.in_progress}</td></tr>)}</tbody></table></div></section>}
 {error&&<CatalogErrorBanner message={error}/>} {!jobs&&!error&&<CatalogLoadingBanner label="Loading provisioning jobs…"/>}
 {jobs&&<section className="ch247-card"><div className="ch247-table-wrap"><table className="ch247-table"><thead><tr><th>Job / order</th><th>Customer / server</th><th>Provider / OS</th><th>Status</th><th>Duration</th><th>Attempts</th><th/></tr></thead><tbody>{jobs.map((job)=>{const duration=job.started_at?Math.round(((job.completed_at?new Date(job.completed_at).getTime():Date.now())-new Date(job.started_at).getTime())/1000):0;return <tr key={job.id}><td><strong>{job.id.slice(0,8)}</strong><br/><small>{job.order_number??job.operation}</small></td><td>{job.customer_email??'—'}<br/><small>{job.server_name}</small></td><td>{job.provider_name}<br/><small>{job.os_display_name??'—'}</small></td><td><StatusBadge status={job.status}/>{job.error_code&&<small className="ch247-error-text">{job.error_code}</small>}</td><td>{duration}s</td><td>{job.attempts}/{job.max_attempts}</td><td><div className="ch247-actions"><button className="ch247-btn" onClick={async()=>{setDetail(await apiFetch<Detail>(`/api/v1/admin/provisioning-jobs/${job.id}`));}}>Logs</button>{job.status==='FAILED'&&<button className="ch247-btn" disabled={busy!==''} onClick={()=>void action(job,'retry')}>Retry</button>}{job.status==='QUEUED'&&<button className="ch247-btn ch247-btn--danger" disabled={busy!==''} onClick={()=>void action(job,'cancel')}>Cancel</button>}</div></td></tr>;})}</tbody></table></div></section>}
 {detail&&<section className="ch247-card"><div className="ch247-section-heading"><div><span className="ch247-eyebrow">Provisioning job</span><h2>#{detail.job.id}</h2></div><button className="ch247-btn" onClick={()=>setDetail(null)}>Close</button></div><dl className="ch247-kv"><dt>Operation</dt><dd>{detail.job.operation}</dd><dt>Status</dt><dd><StatusBadge status={detail.job.status}/></dd><dt>Idempotency key</dt><dd><code>{detail.job.idempotency_key}</code></dd><dt>Provider resource</dt><dd><code>{detail.job.provider_server_id??'Not allocated'}</code></dd><dt>Attempts</dt><dd>{detail.job.attempts}/{detail.job.max_attempts}</dd><dt>Retryable</dt><dd>{detail.job.retryable===null?'Not classified':detail.job.retryable?'Yes':'No'}</dd>{detail.job.error_code&&<><dt>Failure</dt><dd className="ch247-error-text"><code>{detail.job.error_code}</code> · {detail.job.error_message}</dd></>}</dl><h3>Durable steps</h3><ol className="ch247-pipeline">{detail.steps.map((step)=><li className={`is-${step.status}`} key={step.id}><span className="ch247-pipeline__dot"/><div><strong>{step.step_order}. {step.name}</strong><small>{step.started_at?new Date(step.started_at).toLocaleString():'Not started'}{step.completed_at?` → ${new Date(step.completed_at).toLocaleString()}`:''}</small>{step.output&&<small>{step.output}</small>}{step.error&&<small className="ch247-error-text">{step.error}</small>}</div></li>)}</ol><h3>Stage log</h3><div className="ch247-console">{detail.job.logs.map((entry,index)=><div className={`ch247-console__line is-${entry.level}`} key={`${entry.at}-${index}`}><span className="ch247-console__time">{new Date(entry.at).toLocaleTimeString()}</span><strong>[{entry.stage}]</strong> {entry.message}{entry.metadata&&Object.keys(entry.metadata).length>0&&<small> {JSON.stringify(entry.metadata)}</small>}</div>)}{detail.job.logs.length===0&&<div className="ch247-console__line">No stage log entries.</div>}</div><h3>Queue events</h3><div className="ch247-console">{detail.events.map((event)=><div className={`ch247-console__line is-${event.level}`} key={event.id}><span className="ch247-console__time">{new Date(event.created_at).toLocaleTimeString()}</span>{event.message}</div>)}</div>{detail.job.provider_response&&<><h3>Sanitized provider response</h3><pre className="ch247-console">{JSON.stringify(detail.job.provider_response,null,2)}</pre></>}</section>}
 </div>;
}
