import { FormEvent, useState } from 'react';
import { apiFetch } from '../lib/api';
import { useApiResource } from '../lib/useApiResource';
import { usePageMeta } from '../lib/usePageMeta';

export default function DomainBrokeragePage() {
  usePageMeta('Domain Brokerage', 'Track legitimate domain acquisition requests.');
  const cases = useApiResource<{ cases: Array<{ id:string; brokerage_id:string; domain:string; status:string; current_offer:number|null; currency:string; payment_status:string; transfer_status:string }> }>('/api/v1/account/domain-brokerage/cases');
  const [domain, setDomain] = useState(''); const [budget, setBudget] = useState(''); const [message, setMessage] = useState(''); const [notice, setNotice] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setNotice(''); try { await apiFetch('/api/v1/account/domain-brokerage/cases', { method:'POST', body: JSON.stringify({ domain, customerName:'Account holder', contactInformation:'Use my CloudHost247 account contact details', maxBudget:Number(budget), currency:'USD', message, termsAccepted:true, idempotencyKey: crypto.randomUUID() }) }); setNotice('Request submitted. Acquisition is not guaranteed; a registered domain is not automatically for sale.'); setDomain(''); setBudget(''); } catch (err) { setNotice(err instanceof Error ? err.message : 'Unable to submit request'); } }
  return <div className="ch247-stack"><div className="ch247-card"><h1>Domain Brokerage</h1><p className="ch247-page__hint">CloudHost247 can attempt a legitimate acquisition through an approved route or manual broker. Registration does not mean the owner has agreed to sell.</p><form onSubmit={submit} className="ch247-stack"><label>Domain<input value={domain} onChange={e=>setDomain(e.target.value)} required placeholder="example.com" /></label><label>Maximum acquisition budget (confidential)<input type="number" min="1" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} required /></label><label>Message to broker (optional)<textarea value={message} onChange={e=>setMessage(e.target.value)} /></label><label><input type="checkbox" required /> I agree to the Domain Brokerage terms. Acquisition is not guaranteed.</label><button type="submit">Broker This Domain</button>{notice && <p role="status">{notice}</p>}</form></div><div className="ch247-card"><h2>Your brokerage cases</h2>{cases.status==='loading'&&<p>Loading…</p>}{cases.status==='error'&&<p>{cases.message}</p>}{cases.status==='success'&&cases.data.cases.length===0&&<p>No brokerage cases yet.</p>}{cases.status==='success'&&cases.data.cases.map(c=><article key={c.id}><h3>{c.brokerage_id} · {c.domain}</h3><p>Status: {c.status} · Payment: {c.payment_status} · Transfer: {c.transfer_status}</p><p>Current offer: {c.current_offer ? `${c.currency} ${c.current_offer}` : 'No offer yet'}</p></article>)}</div></div>;
}
