/**
 * Tools Center — the canonical tool catalogue (spec §3, §63, §72).
 *
 * This file is the single source of truth for *what tools exist*, what each one needs in order to
 * run, and where its UI lives. Operator overrides (enable/disable, maintenance, provider binding,
 * limits) live in the `tool_definitions` table and are layered on top by src/tools/core/registry.ts.
 *
 * Nothing here describes a capability the platform does not have: an entry with `capability` or
 * `providerKind` set resolves to SERVICE_UNAVAILABLE / CONFIGURATION_REQUIRED — and the API says so
 * — rather than returning invented data (spec §62, §89).
 */

export type ToolCategorySlug =
  | 'dns'
  | 'ip'
  | 'network'
  | 'developer'
  | 'webmaster'
  | 'security'
  | 'domain'
  | 'productivity'
  | 'diagnostics';

export type ToolVisibility = 'public' | 'customer' | 'admin';

export type RateLimitProfile = 'light' | 'standard' | 'heavy' | 'restricted';

/** Runtime capability keys checked by src/tools/core/capabilities.ts. */
export type CapabilityKey =
  | 'dns-udp'
  | 'dns-doh'
  | 'tcp-connect'
  | 'icmp-ping'
  | 'traceroute'
  | 'tls-client'
  | 'smtp-client'
  | 'http-fetch'
  | 'raw-socket';

export type ProviderKind =
  | 'DNSBL'
  | 'GEOLOCATION'
  | 'RDAP'
  | 'WHOIS'
  | 'BLACKLIST_API'
  | 'DKIM_VERIFY'
  | 'BIN'
  | 'OCR'
  | 'REVERSE_IP'
  | 'AVAILABILITY'
  | 'SERP'
  | 'AI'
  | 'OBJECT_STORAGE'
  | 'SPEED_TEST'
  | 'OTHER';

export interface ToolCatalogEntry {
  slug: string;
  name: string;
  category: ToolCategorySlug;
  /** One-line card description. */
  summary: string;
  /** Longer explanation shown on the tool page ("what this checks / what it cannot tell you"). */
  description: string;
  icon: string;
  /** SPA route. */
  path: string;
  /** API endpoint (the /api/v1 alias always exists alongside /api). */
  apiPath: string;
  methods: Array<'GET' | 'POST' | 'DELETE'>;
  /** True when the tool needs a signed-in CloudHost247 account. */
  authRequired: boolean;
  visibility: ToolVisibility;
  capability?: CapabilityKey;
  /** Provider kind this tool needs; when set and not `providerOptional`, missing config is an honest CONFIGURATION_REQUIRED. */
  providerKind?: ProviderKind;
  providerOptional?: boolean;
  /** When set, the tool works only for resources the caller owns (spec §58). */
  requiresOwnership?: boolean;
  rateLimitProfile: RateLimitProfile;
  /** Cache duration in seconds; 0 = never cached. */
  cacheSeconds: number;
  timeoutMs: number;
  keywords: string[];
  /** Shown in the UI as an explicit limitation/expectation. */
  notes?: string[];
}

const STANDARD_NOTES = {
  approxGeo:
    'IP geolocation is approximate and describes where an address is registered/announced — it is not a physical location of a person or device.',
} as const;

export const TOOL_CATALOG: readonly ToolCatalogEntry[] = [
  // ------------------------------------------------------------------ DNS
  {
    slug: 'dns-propagation',
    name: 'DNS Propagation Checker',
    category: 'dns',
    summary: 'Query the same record against multiple public resolvers worldwide.',
    description:
      'Sends the same DNS question to each enabled resolver in the CloudHost247 resolver registry and reports, per resolver, the answer, response time and status. Results describe exactly the resolvers queried — CloudHost247 does not claim that these answers represent global propagation.',
    icon: 'globe',
    path: '/tools/dns/propagation',
    apiPath: '/api/tools/dns-propagation',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'heavy',
    cacheSeconds: 30,
    timeoutMs: 20_000,
    keywords: ['propagation', 'whatsmydns', 'dns', 'worldwide', 'resolvers', 'nameservers'],
    notes: [
      'Each row is one resolver. A resolver may answer from any of its anycast locations, so the country shown is the resolver\'s published location, not necessarily the datacentre that answered.',
      'Caching at authoritative nameservers means a recently changed record can legitimately return both the old and new value for the duration of its TTL.',
    ],
  },
  {
    slug: 'dns-lookup',
    name: 'DNS Lookup',
    category: 'dns',
    summary: 'Look up A, AAAA, CNAME, MX, NS, TXT, SOA, SRV, CAA, PTR, DS and DNSKEY records.',
    description:
      'Queries a selected CloudHost247 resolver for one record type and shows every answer with TTL, priority (MX/SRV) and the resolver that answered. DS and DNSKEY come from the DNSSEC zone.',
    icon: 'search',
    path: '/tools/dns/lookup',
    apiPath: '/api/tools/dns-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'light',
    cacheSeconds: 60,
    timeoutMs: 8_000,
    keywords: ['dns', 'lookup', 'a', 'aaaa', 'cname', 'mx', 'ns', 'txt', 'soa', 'srv', 'caa', 'ptr'],
  },
  {
    slug: 'dns-health',
    name: 'DNS Health Checker',
    category: 'dns',
    summary: 'Run every DNS, delegation, email-authentication and DNSSEC check for a domain.',
    description:
      'Runs a battery of independent checks against the domain\'s authoritative servers and public resolvers: NS delegation consistency, A/AAAA/CNAME, MX, SPF, DKIM, DMARC, BIMI, CAA, SOA, TTL consistency, DNSSEC and resolution failures. Each check reports PASS, WARNING, ERROR, NOT_CHECKED or UNKNOWN with its own explanation.',
    icon: 'activity',
    path: '/tools/dns/health',
    apiPath: '/api/tools/dns-health',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'heavy',
    cacheSeconds: 300,
    timeoutMs: 25_000,
    keywords: ['health', 'audit', 'dns', 'dnssec', 'spf', 'dmarc', 'dkim', 'delegation'],
    notes: [
      'The overall status summarises specific checks; a domain is never labelled "secure" merely because a record exists.',
    ],
  },
  {
    slug: 'mx-lookup',
    name: 'MX Lookup',
    category: 'dns',
    summary: 'Resolve MX hosts, their addresses, reverse DNS and mail provider.',
    description:
      'Resolves the domain\'s MX records, then resolves each mail host to IPv4/IPv6 and performs a reverse lookup. The provider is identified only when the MX hostname matches a known CloudHost247 mapping; otherwise it is reported as Unknown rather than guessed.',
    icon: 'mail',
    path: '/tools/dns/mx',
    apiPath: '/api/tools/mx-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 12_000,
    keywords: ['mx', 'mail', 'email', 'exchange', 'smtp'],
  },
  {
    slug: 'spf-checker',
    name: 'SPF Checker',
    category: 'dns',
    summary: 'Parse and validate the domain\'s SPF policy, including DNS lookup count.',
    description:
      'Fetches the SPF TXT record, parses every mechanism and modifier, checks the RFC 7208 syntax, counts the DNS lookups the record requires (limit 10) and flags common misconfigurations: multiple SPF records, deprecated ptr, missing terminal all, lookups beyond 10, and include loops.',
    icon: 'shield-check',
    path: '/tools/dns/spf',
    apiPath: '/api/tools/spf-checker',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 120,
    timeoutMs: 15_000,
    keywords: ['spf', 'email', 'authentication', 'sender policy', 'txt'],
  },
  {
    slug: 'dmarc-checker',
    name: 'DMARC Checker',
    category: 'dns',
    summary: 'Inspect and validate a _dmarc policy, tag by tag.',
    description:
      'Fetches _dmarc.<domain> and validates every tag (v, p, sp, pct, rua, ruf, adkim, aspf, fo, rf, ri), explains what the policy means for receiving mail servers, and warns about combinations that are syntactically valid but operationally risky.',
    icon: 'mail-check',
    path: '/tools/dns/dmarc',
    apiPath: '/api/tools/dmarc-checker',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 120,
    timeoutMs: 10_000,
    keywords: ['dmarc', 'email', 'policy', 'rua', 'alignment'],
  },
  {
    slug: 'dmarc-generator',
    name: 'DMARC Record Generator',
    category: 'dns',
    summary: 'Build a correctly formatted _dmarc record interactively.',
    description:
      'Generates the TXT value for a _dmarc record from a guided form and shows exactly where to publish it. Generation is deterministic and validated server-side, so the value can be pasted into CloudHost247 DNS management, cPanel or any DNS host.',
    icon: 'wand',
    path: '/tools/dns/dmarc-generator',
    apiPath: '/api/tools/dmarc-generator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['dmarc', 'generator', 'txt', 'policy'],
  },
  {
    slug: 'dkim-checker',
    name: 'DKIM Checker',
    category: 'dns',
    summary: 'Check selector._domainkey records for one or more selectors.',
    description:
      'Queries the DKIM public-key records for the selectors you supply, parses the key, reports the key type and flags syntax problems. CloudHost247 cannot confirm a signature actually validates from the public key alone — when an external DKIM verifier provider is configured, that extra verification is offered explicitly.',
    icon: 'key',
    path: '/tools/dns/dkim',
    apiPath: '/api/tools/dkim-checker',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    providerKind: 'DKIM_VERIFY',
    providerOptional: true,
    rateLimitProfile: 'standard',
    cacheSeconds: 120,
    timeoutMs: 12_000,
    keywords: ['dkim', 'selector', 'domainkey', 'email', 'signature'],
  },
  {
    slug: 'bimi-checker',
    name: 'BIMI Checker',
    category: 'dns',
    summary: 'Inspect the BIMI record, logo URL and VMC certificate URL.',
    description:
      'Fetches default._bimi.<domain>, parses the l= and a= tags, validates the URL shape, and reports whether the DMARC policy satisfies BIMI\'s enforcement prerequisite. It reports what the DNS says; it does not claim a mailbox provider will display the logo.',
    icon: 'badge-check',
    path: '/tools/dns/bimi',
    apiPath: '/api/tools/bimi-checker',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 12_000,
    keywords: ['bimi', 'brand', 'logo', 'vmc', 'dmarc'],
  },
  {
    slug: 'dnskey-lookup',
    name: 'DNSKEY Lookup',
    category: 'dns',
    summary: 'Show the zone\'s DNSKEY records with key tag, algorithm, flags and public key.',
    description:
      'Queries DNSKEY at the zone apex, computes the RFC 4034 §5.1.4 key tag for each key and reports SEP/Zone flags, protocol and algorithm. Presence of DNSKEY records does not by itself prove DNSSEC validation; the DNS Health Checker reports delegation evidence separately.',
    icon: 'key-round',
    path: '/tools/dns/dnskey',
    apiPath: '/api/tools/dnskey-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 10_000,
    keywords: ['dnskey', 'dnssec', 'keytag', 'algorithm'],
  },
  {
    slug: 'ds-lookup',
    name: 'DS Lookup',
    category: 'dns',
    summary: 'Show the DS records published by the parent zone and the DNSSEC chain state.',
    description:
      'Queries DS at the parent zone (or at the zone itself when it is a TLD), lists key tag, algorithm, digest type and digest, and reports whether a matching DNSKEY exists at the child so the delegation chain can be described factually.',
    icon: 'link',
    path: '/tools/dns/ds',
    apiPath: '/api/tools/ds-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 10_000,
    keywords: ['ds', 'dnssec', 'delegation', 'digest', 'chain'],
  },
  {
    slug: 'reverse-dns',
    name: 'Reverse DNS / PTR Lookup',
    category: 'dns',
    summary: 'PTR lookup for IPv4/IPv6 with forward-confirmed reverse DNS.',
    description:
      'Builds the in-addr.arpa / ip6.arpa name, resolves its PTR records and then resolves each returned hostname forward to confirm the address appears in its A/AAAA records (forward-confirmed reverse DNS).',
    icon: 'undo',
    path: '/tools/dns/reverse',
    apiPath: '/api/tools/reverse-dns',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 120,
    timeoutMs: 10_000,
    keywords: ['ptr', 'reverse dns', 'rdns', 'fcrdns', 'in-addr.arpa'],
  },
  {
    slug: 'reverse-ip',
    name: 'Reverse IP Lookup',
    category: 'dns',
    summary: 'Find hostnames hosted on an IP address, when a data provider is configured.',
    description:
      'There is no public DNS mechanism that lists the domains behind an IP address. This tool therefore requires an administrator-configured reverse-IP data provider and returns CONFIGURATION_REQUIRED until one exists. It never claims to discover every domain on an address.',
    icon: 'layers',
    path: '/tools/dns/reverse-ip',
    apiPath: '/api/tools/reverse-ip',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    providerKind: 'REVERSE_IP',
    rateLimitProfile: 'restricted',
    cacheSeconds: 900,
    timeoutMs: 12_000,
    keywords: ['reverse ip', 'hosted domains', 'shared ip'],
    notes: ['Even with a provider, results are that provider\'s index — never a complete list of everything hosted on the address.'],
  },

  // ------------------------------------------------------------------ IP
  {
    slug: 'ip-lookup',
    name: 'IP Address Lookup',
    category: 'ip',
    summary: 'ASN, organisation, country, reverse DNS and network range for an IP.',
    description:
      'Combines the free, keyless Team Cymru DNS origin lookup (ASN, prefix, registry, country) with reverse DNS and, when a geolocation provider is configured, city/region/timezone enrichment. Address version, class (public/private/reserved) and prefix are always reported.',
    icon: 'ip',
    path: '/tools/ip/lookup',
    apiPath: '/api/tools/ip-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    providerKind: 'GEOLOCATION',
    providerOptional: true,
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 12_000,
    keywords: ['ip', 'lookup', 'asn', 'geoip', 'reverse dns', 'whois'],
    notes: [STANDARD_NOTES.approxGeo],
  },
  {
    slug: 'my-ip',
    name: 'What Is My IP',
    category: 'ip',
    summary: 'Show the public IP this request arrived from, plus connection details.',
    description:
      'Reports the address the CloudHost247 edge actually observed for your request (and the IPv6 address separately when the connection used IPv6), with user-agent and, when detectable, the negotiated TLS protocol/cipher. No attempt is made to fingerprint the device beyond what the browser sends.',
    icon: 'wifi',
    path: '/tools/ip/my-ip',
    apiPath: '/api/tools/my-ip',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['my ip', 'what is my ip', 'ipv4', 'ipv6', 'user agent'],
  },
  {
    slug: 'ip-whois',
    name: 'IP WHOIS',
    category: 'ip',
    summary: 'Registry data for an IPv4/IPv6 address over RDAP.',
    description:
      'Queries RDAP (the structured, standards-based successor to port-43 WHOIS) for the address: network handle, name, range, CIDR blocks, registrant organisation, abuse contact, events and remarks. The RDAP bootstrap endpoint is operator-configurable.',
    icon: 'file-search',
    path: '/tools/ip/whois',
    apiPath: '/api/tools/ip-whois',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    providerKind: 'RDAP',
    providerOptional: true,
    rateLimitProfile: 'standard',
    cacheSeconds: 900,
    timeoutMs: 12_000,
    keywords: ['whois', 'rdap', 'registrar', 'registry', 'abuse'],
  },
  {
    slug: 'domain-to-ip',
    name: 'Domain → IP',
    category: 'ip',
    summary: 'Resolve a hostname to IPv4/IPv6 with the full CNAME chain.',
    description: 'Resolves A and AAAA through a chosen CloudHost247 resolver, showing the CNAME chain, TTLs and response time for each answer.',
    icon: 'arrow-right-left',
    path: '/tools/ip/domain-to-ip',
    apiPath: '/api/tools/domain-to-ip',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'light',
    cacheSeconds: 60,
    timeoutMs: 8_000,
    keywords: ['domain to ip', 'resolve', 'a record', 'aaaa', 'cname'],
  },
  {
    slug: 'ip-to-hostname',
    name: 'IP → Hostname',
    category: 'ip',
    summary: 'Reverse DNS for an address, with FCRDNS confirmation.',
    description: 'Performs the PTR lookup for an address and confirms each hostname resolves back to it.',
    icon: 'arrow-left-right',
    path: '/tools/ip/ip-to-hostname',
    apiPath: '/api/tools/ip-to-hostname',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 120,
    timeoutMs: 10_000,
    keywords: ['reverse dns', 'ptr', 'hostname', 'ip'],
  },
  {
    slug: 'isp-lookup',
    name: 'ISP Lookup',
    category: 'ip',
    summary: 'Network operator, ASN and country for an IP address.',
    description:
      'Uses the keyless Team Cymru DNS origin service for ASN/prefix/registry/country and the reverse-DNS operator name, and adds ISP/carrier names from a geolocation provider when one is configured.',
    icon: 'radio',
    path: '/tools/ip/isp',
    apiPath: '/api/tools/isp-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    providerKind: 'GEOLOCATION',
    providerOptional: true,
    rateLimitProfile: 'standard',
    cacheSeconds: 300,
    timeoutMs: 12_000,
    keywords: ['isp', 'carrier', 'asn', 'operator'],
    notes: [STANDARD_NOTES.approxGeo],
  },
  {
    slug: 'ip-converters',
    name: 'IP Converters',
    category: 'ip',
    summary: 'Decimal ↔ IP, IPv4 ↔ IPv6, IPv6 compression/expansion, CIDR ↔ range.',
    description:
      'Deterministic conversions with the intermediate steps shown: IPv4/IPv6 to decimal and back, IPv4-mapped IPv6 and NAT64 forms, IPv6 compression and expansion, and IPv6 CIDR ↔ address range.',
    icon: 'calculator',
    path: '/tools/ip/converters',
    apiPath: '/api/tools/ip-converters',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['decimal', 'ipv6', 'compression', 'expansion', 'cidr', 'range', 'converter'],
    notes: ['IPv6 → IPv4 is only meaningful for IPv4-mapped, 6to4 and NAT64 addresses; for ordinary IPv6 addresses the tool says so instead of inventing an equivalent.'],
  },
  {
    slug: 'subnet-calculator',
    name: 'Subnet Calculator',
    category: 'network',
    summary: 'IPv4/IPv6 network, broadcast, host range, masks and splitting.',
    description:
      'Computes network address, broadcast, first/last usable host, address count, CIDR notation, subnet mask, wildcard mask and binary forms for IPv4 and IPv6, and can split a network into equal subnets.',
    icon: 'network',
    path: '/tools/network/subnet-calculator',
    apiPath: '/api/tools/subnet-calculator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['subnet', 'cidr', 'netmask', 'wildcard', 'vlsm', 'calculator'],
  },

  // ------------------------------------------------------------------ Network
  {
    slug: 'ping',
    name: 'Ping Tool',
    category: 'network',
    summary: 'Measure reachability and latency from the CloudHost247 server.',
    description:
      'Uses the ICMP ping utility when the deployment allows it, and otherwise falls back to TCP connect timing against the port you choose — clearly labelled as TCP latency, never presented as ICMP. Targets are validated, private ranges are refused and results are rate limited.',
    icon: 'radio-tower',
    path: '/tools/network/ping',
    apiPath: '/api/tools/ping',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    capability: 'icmp-ping',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 15_000,
    keywords: ['ping', 'latency', 'icmp', 'reachability'],
    notes: ['CloudHost247 servers on shared cPanel hosting frequently cannot open raw ICMP sockets; in that case the tool states that ICMP is unavailable and offers TCP connect timing instead.'],
  },
  {
    slug: 'traceroute',
    name: 'Traceroute',
    category: 'network',
    summary: 'Hop-by-hop path to a target, where the environment permits.',
    description:
      'Runs the system traceroute utility with a bounded hop count and timeout when the binary exists and the environment allows it. When it does not, the tool reports UNAVAILABLE_IN_THIS_ENVIRONMENT and explains why rather than returning fabricated hops.',
    icon: 'route',
    path: '/tools/network/traceroute',
    apiPath: '/api/tools/traceroute',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    capability: 'traceroute',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 25_000,
    keywords: ['traceroute', 'hops', 'path', 'network'],
  },
  {
    slug: 'port-checker',
    name: 'Port Checker',
    category: 'network',
    summary: 'Check whether a TCP port on a public host accepts connections.',
    description:
      'Opens a TCP connection to a validated public host and port with a short timeout, reporting open, closed, filtered/timeout or unreachable. Single ports and short ranges only, with strict per-account limits; private and reserved address ranges are refused.',
    icon: 'plug',
    path: '/tools/network/port-checker',
    apiPath: '/api/tools/port-checker',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    capability: 'tcp-connect',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['port', 'checker', 'tcp', 'firewall', 'open port'],
    notes: ['This is a connectivity check, not a port scanner: a single port or a short explicit range, rate limited and logged.'],
  },
  {
    slug: 'mac-lookup',
    name: 'MAC Address Lookup',
    category: 'network',
    summary: 'Identify the OUI/vendor registered to a MAC address prefix.',
    description:
      'Looks up the first three octets (OUI) of a MAC address against the locally-held IEEE OUI prefix table and reports the registrant, plus the address\'s unicast/multicast and global/local bits.',
    icon: 'barcode',
    path: '/tools/network/mac-lookup',
    apiPath: '/api/tools/mac-lookup',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 3600,
    timeoutMs: 5_000,
    keywords: ['mac', 'oui', 'vendor', 'ethernet'],
  },
  {
    slug: 'mac-generator',
    name: 'MAC Address Generator',
    category: 'network',
    summary: 'Generate valid random, locally-administered or globally-administered MACs.',
    description: 'Generates cryptographically random MAC addresses with the correct unicast/multicast and U/L bits for the requested mode.',
    icon: 'shuffle',
    path: '/tools/network/mac-generator',
    apiPath: '/api/tools/mac-generator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['mac', 'generator', 'random'],
  },
  {
    slug: 'asn-whois',
    name: 'ASN WHOIS',
    category: 'network',
    summary: 'Autonomous system details, announced prefixes and registry.',
    description:
      'Queries RDAP for the AS number and the DNS-based Team Cymru origin service for announced prefixes, then resolves the AS name from RDAP. Results are attributable: every field lists the source that produced it.',
    icon: 'git-branch',
    path: '/tools/network/asn',
    apiPath: '/api/tools/asn-whois',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    providerKind: 'RDAP',
    providerOptional: true,
    rateLimitProfile: 'standard',
    cacheSeconds: 900,
    timeoutMs: 15_000,
    keywords: ['asn', 'autonomous system', 'bgp', 'prefixes', 'rdap'],
  },
  {
    slug: 'speed-test',
    name: 'Internet Speed Test',
    category: 'network',
    summary: 'Browser-based download, upload and latency measurement with hard limits.',
    description:
      'Measures throughput between your browser and CloudHost247 using bounded transfers: the server caps each measurement by size and duration, and rate limits each client. Latency is measured with small request/response timing and jitter is reported when at least three samples are collected.',
    icon: 'gauge',
    path: '/tools/network/speed-test',
    apiPath: '/api/tools/speed-test',
    methods: ['GET', 'POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['speed test', 'bandwidth', 'download', 'upload', 'latency', 'jitter'],
    notes: ['Measures the path between your browser and this CloudHost247 server — not your line\'s rated speed.'],
  },

  // ------------------------------------------------------------------ Developer
  {
    slug: 'http-headers',
    name: 'HTTP Headers Checker',
    category: 'developer',
    summary: 'Status, headers, redirect chain, cache and security-header analysis.',
    description:
      'Fetches a URL through the SSRF-protected client, follows redirects with a hop limit, and reports the status code, every response header, the redirect chain, and an assessment of security headers (HSTS, CSP, X-Content-Type-Options, X-Frame-Options/frame-ancestors, Referrer-Policy, Permissions-Policy) and cache directives.',
    icon: 'file-code',
    path: '/tools/developer/http-headers',
    apiPath: '/api/tools/http-headers',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'http-fetch',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['http', 'headers', 'security headers', 'redirect', 'cache'],
  },
  {
    slug: 'server-os',
    name: 'Website OS Checker',
    category: 'developer',
    summary: 'Infer server software with an explicit confidence level.',
    description:
      'Reads Server, X-Powered-By, Via and proxy-identifying headers and reports each technology with a confidence level — Confirmed when the server states it, Likely when derived from several weak signals, Unknown when nothing reliable is present. No probing of the server beyond the single HTTP request.',
    icon: 'server',
    path: '/tools/developer/server-os',
    apiPath: '/api/tools/server-os',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'http-fetch',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 15_000,
    keywords: ['server', 'os', 'nginx', 'apache', 'technology', 'fingerprint'],
  },
  {
    slug: 'smtp-tester',
    name: 'SMTP Tester',
    category: 'developer',
    summary: 'Test an SMTP server\'s reachability, TLS and (optionally) authentication.',
    description:
      'Connects to the SMTP host, reads the banner, negotiates STARTTLS or implicit TLS, and reports the server capabilities, certificate summary and whether AUTH is offered. When you supply credentials they are used for that single test only: never logged, never stored, and never echoed back.',
    icon: 'send',
    path: '/tools/developer/smtp-test',
    apiPath: '/api/tools/smtp-tester',
    methods: ['POST'],
    authRequired: true,
    visibility: 'customer',
    capability: 'smtp-client',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 25_000,
    keywords: ['smtp', 'email', 'mail server', 'starttls', 'authentication'],
    notes: [
      'SMTP credentials are used in memory for one connection and discarded; the audit log stores only the host, port and outcome.',
    ],
  },
  {
    slug: 'email-header',
    name: 'Email Header Analyzer',
    category: 'developer',
    summary: 'Parse a raw message header: Received chain, auth results, sending IP.',
    description:
      'Parses a pasted header, reconstructs the Received chain with per-hop delays, extracts SPF/DKIM/DMARC results from Authentication-Results, identifies the sending IP and mail servers, and flags alignment mismatches between From, Return-Path and the authenticated domain.',
    icon: 'mail-search',
    path: '/tools/developer/email-header',
    apiPath: '/api/tools/email-header',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'standard',
    cacheSeconds: 0,
    timeoutMs: 10_000,
    keywords: ['email header', 'spf', 'dkim', 'dmarc', 'received', 'authentication results'],
    notes: [
      'The pasted header is analysed in memory. It is stored only if you explicitly save the analysis to your reports.',
    ],
  },
  {
    slug: 'json-tools',
    name: 'JSON Tools',
    category: 'developer',
    summary: 'Viewer, formatter, beautifier, minifier and validator.',
    description:
      'Validates JSON with precise error positions, formats it with the indentation you choose, minifies it, and can sort keys. All processing happens in the browser; the API endpoint exists so the same behaviour is available to integrations and is covered by tests.',
    icon: 'braces',
    path: '/tools/developer/json',
    apiPath: '/api/tools/json-tools',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['json', 'formatter', 'beautifier', 'minifier', 'validator', 'viewer'],
  },
  {
    slug: 'encoding-tools',
    name: 'Encoding Tools',
    category: 'developer',
    summary: 'Base64, MD5, binary ↔ text, ROT13 and Morse code.',
    description:
      'Encodes and decodes Base64 (UTF-8 safe), computes MD5, converts between text and binary, applies ROT13 and translates to/from Morse code. MD5 is provided for checksum/interoperability work only and the UI states plainly that it is unsuitable for password storage.',
    icon: 'binary',
    path: '/tools/developer/encoding',
    apiPath: '/api/tools/encoding-tools',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['base64', 'md5', 'binary', 'rot13', 'morse', 'encoder', 'decoder'],
  },
  {
    slug: 'url-tools',
    name: 'URL Tools',
    category: 'developer',
    summary: 'Multi-URL opener, rewrite-rule and .htaccess generators.',
    description:
      'Opens several URLs in browser tabs (client-side only — no server-side fetching merely to open a link), parses and explains URL components, and generates common Apache rewrite/redirect rules and .htaccess blocks with safe defaults.',
    icon: 'link-2',
    path: '/tools/developer/url',
    apiPath: '/api/tools/url-tools',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['url', 'opener', 'rewrite', 'htaccess', 'redirect'],
    notes: ['Browser pop-up blockers may stop the multi-URL opener; the tool opens the first URL as a direct user-initiated navigation and the rest as tabs.'],
  },
  {
    slug: 'user-agent',
    name: 'User Agent Tool',
    category: 'developer',
    summary: 'Show the user-agent and headers your browser actually sent.',
    description: 'Displays the exact User-Agent string and request headers CloudHost247 received, so a support conversation can start from the same facts.',
    icon: 'monitor',
    path: '/tools/developer/user-agent',
    apiPath: '/api/tools/user-agent',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['user agent', 'browser', 'headers', 'fingerprint'],
  },

  // ------------------------------------------------------------------ Webmaster
  {
    slug: 'broken-links',
    name: 'Broken Link Checker',
    category: 'webmaster',
    summary: 'Crawl a site within strict limits and report failing links.',
    description:
      'Crawls the same host starting from the URL you provide, within hard limits on pages, links, runtime and response size, and reports each link with its status, type (internal/external), redirect chain, error and the page it was found on. Private and reserved destinations are refused.',
    icon: 'unlink',
    path: '/tools/webmaster/broken-links',
    apiPath: '/api/tools/broken-links',
    methods: ['POST'],
    authRequired: true,
    visibility: 'customer',
    capability: 'http-fetch',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 30_000,
    keywords: ['broken links', 'crawler', 'seo', '404', 'link checker'],
    notes: ['Only HTML pages on the same host are crawled; external links are checked but never followed.'],
  },
  {
    slug: 'open-graph',
    name: 'Open Graph Checker',
    category: 'webmaster',
    summary: 'Inspect og: and Twitter card metadata and preview the link.',
    description: 'Parses Open Graph and Twitter/X card tags, warns about missing or malformed required properties, resolves relative image URLs and renders a preview of how the link is likely to appear.',
    icon: 'share-2',
    path: '/tools/webmaster/open-graph',
    apiPath: '/api/tools/open-graph',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'http-fetch',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['open graph', 'og', 'twitter card', 'social preview', 'seo'],
  },
  {
    slug: 'robots-generator',
    name: 'robots.txt Generator',
    category: 'webmaster',
    summary: 'Build a valid robots.txt with sitemaps and crawl delay.',
    description:
      'Generates robots.txt from a guided form (user-agent groups, allow/disallow rules, sitemaps, crawl-delay, common presets), validating directives so the file cannot be emitted in a malformed state.',
    icon: 'file-text',
    path: '/tools/webmaster/robots-generator',
    apiPath: '/api/tools/robots-generator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['robots.txt', 'generator', 'crawl', 'sitemap', 'seo'],
  },
  {
    slug: 'serp-simulator',
    name: 'SERP Simulator',
    category: 'webmaster',
    summary: 'Preview a search result snippet for title, URL and description length.',
    description:
      'Renders a desktop and mobile search-result preview and reports pixel-width and character guidance for the title and description. It is explicitly a simulator for appearance only; it shows no ranking data.',
    icon: 'list',
    path: '/tools/webmaster/serp-simulator',
    apiPath: '/api/tools/serp-simulator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['serp', 'search preview', 'snippet', 'title length', 'seo'],
    notes: ['This tool does not query Google or any search engine and cannot show a real ranking position.'],
  },

  // ------------------------------------------------------------------ Security
  {
    slug: 'ssl-checker',
    name: 'SSL Certificate Checker',
    category: 'security',
    summary: 'Certificate chain, validity, SANs, protocol and expiry for a host.',
    description:
      'Opens a real TLS connection, reports the leaf and chain certificates (subject, issuer, SANs, validity, signature algorithm, key parameters), the negotiated protocol and cipher, hostname match, and days remaining. Private keys are never requested or displayed.',
    icon: 'lock',
    path: '/tools/security/ssl',
    apiPath: '/api/tools/ssl-checker',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'tls-client',
    rateLimitProfile: 'restricted',
    cacheSeconds: 120,
    timeoutMs: 15_000,
    keywords: ['ssl', 'tls', 'certificate', 'expiry', 'chain', 'https'],
  },
  {
    slug: 'ip-blacklist',
    name: 'IP Blacklist Checker',
    category: 'security',
    summary: 'Check an IP against the DNS blocklists the operator has enabled.',
    description:
      'Queries each enabled DNS-based blocklist for the address and reports listed / not listed / error per provider, with the listing code or text the provider returned and delisting guidance. Providers are managed by a Super Admin — nothing is hard-coded.',
    icon: 'shield-alert',
    path: '/tools/security/ip-blacklist',
    apiPath: '/api/tools/ip-blacklist',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    capability: 'dns-udp',
    providerKind: 'DNSBL',
    rateLimitProfile: 'heavy',
    cacheSeconds: 600,
    timeoutMs: 25_000,
    keywords: ['blacklist', 'rbl', 'dnsbl', 'spam', 'reputation', 'delist'],
    notes: [
      'Many blocklists refuse queries that arrive from public resolvers. When that happens the tool reports the refusal — it never reports "not listed" for a query the provider did not answer.',
    ],
  },
  {
    slug: 'password-tools',
    name: 'Password Tools',
    category: 'security',
    summary: 'Generate strong passwords and evaluate strength locally.',
    description:
      'Generates random passwords with the character classes and length you choose, evaluates the strength of a password using client-side entropy estimation against common patterns, and explains the difference between a one-way password hash and reversible encryption.',
    icon: 'key-square',
    path: '/tools/security/password',
    apiPath: '/api/tools/password-tools',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['password', 'generator', 'strength', 'hash', 'entropy'],
    notes: [
      'Passwords are generated in your browser. If you use the API, the password is generated server-side, returned once and never logged or stored.',
    ],
  },
  {
    slug: 'bin-checker',
    name: 'BIN Checker',
    category: 'security',
    summary: 'Issuer information for a card BIN/IIN from a configured provider.',
    description:
      'Accepts only the first 6–8 digits (the BIN/IIN) and returns the issuer data the configured provider supplies. CloudHost247 never accepts, transmits or stores a full card number, and this is not a card-validation or testing service.',
    icon: 'credit-card',
    path: '/tools/security/bin-checker',
    apiPath: '/api/tools/bin-checker',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    providerKind: 'BIN',
    rateLimitProfile: 'restricted',
    cacheSeconds: 3600,
    timeoutMs: 10_000,
    keywords: ['bin', 'iin', 'card', 'issuer', 'bank'],
  },

  // ------------------------------------------------------------------ Domain
  {
    slug: 'punycode',
    name: 'Punycode / IDN Converter',
    category: 'domain',
    summary: 'Convert between Unicode domain names and their ASCII (punycode) form.',
    description:
      'Uses standards-compliant IDNA processing (Node\'s URL hostname parser, which implements UTS#46-style mapping) to convert between a Unicode domain and its punycode form, validating the result and reporting the label-by-label conversion.',
    icon: 'languages',
    path: '/tools/domain/punycode',
    apiPath: '/api/tools/punycode',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['punycode', 'idn', 'unicode', 'domain', 'idna'],
  },
  {
    slug: 'domain-availability',
    name: 'Domain Availability',
    category: 'domain',
    summary: 'Check whether a domain is available, using CloudHost247\'s registrar integration.',
    description:
      'Uses the existing CloudHost247 Domain Services providers (registrar APIs and RDAP) to check availability, and returns the same states the domain search does: available, registered, premium, unsupported, unknown. Signed-in customers can add a result straight to the cart.',
    icon: 'search-check',
    path: '/tools/domain/search',
    apiPath: '/api/tools/domain-availability',
    methods: ['GET'],
    authRequired: false,
    visibility: 'public',
    providerKind: 'AVAILABILITY',
    providerOptional: true,
    rateLimitProfile: 'heavy',
    cacheSeconds: 60,
    timeoutMs: 15_000,
    keywords: ['domain', 'availability', 'search', 'register', 'rdap'],
    notes: ['Availability is only ever what the configured provider reports; an unconfigured provider yields UNKNOWN, never a guess.'],
  },
  {
    slug: 'domain-health',
    name: 'Domain Health Center',
    category: 'diagnostics',
    summary: 'Unified DNS, email, web, network and security view for a domain you own.',
    description:
      'Combines the DNS, email, web, network and security checks for one of your CloudHost247 domains into a single factual report, joining DNS answers to the hosting server, SSL certificate and mail configuration CloudHost247 already stores for that domain.',
    icon: 'heart-pulse',
    path: '/domains/:domain/health',
    apiPath: '/api/tools/domain-health',
    methods: ['GET'],
    authRequired: true,
    visibility: 'customer',
    requiresOwnership: true,
    capability: 'dns-udp',
    rateLimitProfile: 'heavy',
    cacheSeconds: 300,
    timeoutMs: 30_000,
    keywords: ['domain health', 'diagnostics', 'dns', 'ssl', 'email', 'hosting'],
  },

  // ------------------------------------------------------------------ Productivity
  {
    slug: 'word-counter',
    name: 'Word & Text Counter',
    category: 'productivity',
    summary: 'Words, characters, sentences, paragraphs and reading time.',
    description: 'Counts words, characters (with and without spaces), sentences and paragraphs, and estimates reading time from word count.',
    icon: 'type',
    path: '/tools/productivity/word-counter',
    apiPath: '/api/tools/word-counter',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['word count', 'character count', 'sentences', 'paragraphs', 'text'],
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    category: 'productivity',
    summary: 'Generate placeholder text by words, sentences or paragraphs.',
    description: 'Generates classical Lorem Ipsum placeholder text in the quantity you request, with a choice of starting with "Lorem ipsum dolor sit amet…".',
    icon: 'align-left',
    path: '/tools/productivity/lorem-ipsum',
    apiPath: '/api/tools/lorem-ipsum',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['lorem ipsum', 'placeholder', 'dummy text'],
  },
  {
    slug: 'notepad',
    name: 'Online Notepad',
    category: 'productivity',
    summary: 'A scratch pad that stays in your browser.',
    description: 'A distraction-free text area with local persistence in your browser only. Nothing typed into the notepad is sent to CloudHost247 unless you explicitly save it as a report.',
    icon: 'notebook-pen',
    path: '/tools/productivity/notepad',
    apiPath: '/api/tools/notepad',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['notepad', 'scratch', 'notes', 'text'],
  },
  {
    slug: 'small-text',
    name: 'Small Text Generator',
    category: 'productivity',
    summary: 'Convert text to small caps, superscript and subscript Unicode.',
    description: 'Maps letters to Unicode small-cap, superscript and subscript equivalents. Characters without a mapping are left unchanged and reported, so the output never silently loses content.',
    icon: 'text',
    path: '/tools/productivity/small-text',
    apiPath: '/api/tools/small-text',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['small text', 'superscript', 'subscript', 'unicode', 'fonts'],
  },
  {
    slug: 'invisible-character',
    name: 'Invisible Character Generator',
    category: 'productivity',
    summary: 'Copy zero-width and invisible Unicode characters.',
    description: 'Provides the standard invisible Unicode characters with their code points and names, ready to copy. Each entry is labelled with its code point so the output is auditable.',
    icon: 'eye-off',
    path: '/tools/productivity/invisible-character',
    apiPath: '/api/tools/invisible-character',
    methods: ['GET', 'POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 3600,
    timeoutMs: 5_000,
    keywords: ['invisible', 'zero width', 'unicode', 'blank character'],
  },
  {
    slug: 'runic-translator',
    name: 'Runic Translator',
    category: 'productivity',
    summary: 'Transliterate Latin text to Elder Futhark runes and back.',
    description: 'Transliterates Latin letters to Elder Futhark runes using a documented, deterministic mapping (digraphs first), and transliterates back. Characters with no runic equivalent are reported rather than dropped.',
    icon: 'scroll',
    path: '/tools/productivity/runic',
    apiPath: '/api/tools/runic-translator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['runic', 'futhark', 'translator', 'rune'],
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    category: 'productivity',
    summary: 'Create QR codes for URLs, text, email, phone, WiFi and vCards.',
    description:
      'Generates QR codes server-side (so the same PNG/SVG is reproducible from the API) for URLs, plain text, email, phone numbers, WiFi credentials and vCards. Nothing you enter is stored; the response contains the image and nothing else.',
    icon: 'qr-code',
    path: '/tools/productivity/qr',
    apiPath: '/api/tools/qr-generator',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'standard',
    cacheSeconds: 0,
    timeoutMs: 8_000,
    keywords: ['qr', 'qr code', 'generator', 'vcard', 'wifi'],
  },
  {
    slug: 'qr-scanner',
    name: 'QR Scanner',
    category: 'productivity',
    summary: 'Scan a QR code from your camera or an image file.',
    description:
      'Decodes QR codes in the browser using the device camera or an uploaded image, using the platform\'s QR reader support. Decoded content is shown for review and is never uploaded unless you explicitly save it.',
    icon: 'scan-line',
    path: '/tools/productivity/qr-scanner',
    apiPath: '/api/tools/qr-scanner',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['qr', 'scanner', 'decode', 'camera'],
    notes: ['Decoding happens in your browser using the Barcode Detection API where available; when the browser has no decoder, the tool says so instead of uploading your image somewhere.'],
  },
  {
    slug: 'wifi-qr',
    name: 'WiFi QR Tool',
    category: 'productivity',
    summary: 'Share a WiFi network as a QR code, without storing the password.',
    description:
      'Builds the standard WIFI: QR payload from SSID, password, encryption type and hidden flag, then renders it as PNG or SVG. The password is used to render the image and is never written to the database; saving the result as a report stores only the SSID and encryption type.',
    icon: 'wifi-pen',
    path: '/tools/productivity/wifi-qr',
    apiPath: '/api/tools/wifi-qr',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'standard',
    cacheSeconds: 0,
    timeoutMs: 8_000,
    keywords: ['wifi', 'qr', 'ssid', 'password', 'share'],
  },
  {
    slug: 'time-card',
    name: 'Time Card Calculator',
    category: 'productivity',
    summary: 'Clock-in/clock-out totals with breaks and overtime.',
    description: 'Calculates worked time from clock-in/clock-out pairs and breaks, in either 12- or 24-hour format, and applies the overtime rule you specify (daily or weekly thresholds).',
    icon: 'clock',
    path: '/tools/productivity/time-card',
    apiPath: '/api/tools/time-card',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['time card', 'timesheet', 'hours', 'overtime', 'payroll'],
  },
  {
    slug: 'color-tools',
    name: 'Designer Colour Tools',
    category: 'productivity',
    summary: 'Convert between HEX, RGB, HSL, HSV/HSB and CMYK.',
    description: 'Converts a colour between HEX, RGB, HSL, HSV/HSB and CMYK, shows the preview, contrast ratio against black and white, and provides copy-ready values for each notation.',
    icon: 'palette',
    path: '/tools/productivity/colors',
    apiPath: '/api/tools/color-tools',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['color', 'colour', 'hex', 'rgb', 'cmyk', 'hsv', 'hsl', 'designer'],
  },
  {
    slug: 'reverse-image-search',
    name: 'Reverse Image Search',
    category: 'productivity',
    summary: 'Launch an image search with the engines you choose.',
    description:
      'Opens the reverse-image-search service you pick (Google Lens, TinEye, Bing Visual Search, Yandex Images) in a new tab. This tool performs no crawling or scraping of third-party engines: the search itself happens in your browser, under those services\' own terms.',
    icon: 'image-search',
    path: '/tools/productivity/reverse-image',
    apiPath: '/api/tools/reverse-image-search',
    methods: ['POST'],
    authRequired: false,
    visibility: 'public',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['reverse image', 'image search', 'tineye', 'lens'],
  },
  {
    slug: 'image-ocr',
    name: 'Image → Text (OCR)',
    category: 'productivity',
    summary: 'Extract text from an image using a configured OCR provider.',
    description:
      'Uploads an image to the administrator-configured OCR provider and returns the extracted text with a confidence estimate where the provider supplies one. No OCR provider configured means CONFIGURATION_REQUIRED — the platform does not guess at text.',
    icon: 'image',
    path: '/tools/productivity/image-ocr',
    apiPath: '/api/tools/image-ocr',
    methods: ['POST'],
    authRequired: true,
    visibility: 'customer',
    providerKind: 'OCR',
    rateLimitProfile: 'restricted',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['ocr', 'image to text', 'extract text', 'tesseract'],
  },

  // ------------------------------------------------------------------ Diagnostics
  {
    slug: 'tool-history',
    name: 'Tool History',
    category: 'diagnostics',
    summary: 'Your recent tool runs, with the metadata that was stored.',
    description: 'Lists your own tool runs (tool, target, time, status) and lets you clear them. Credentials, SMTP passwords, API keys, private keys, full card numbers and email contents are never stored in history.',
    icon: 'history',
    path: '/tools/history',
    apiPath: '/api/tools/tool-history',
    methods: ['GET', 'DELETE'],
    authRequired: true,
    visibility: 'customer',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['history', 'recent', 'activity'],
  },
  {
    slug: 'tool-favorites',
    name: 'Favorites',
    category: 'diagnostics',
    summary: 'The tools you have starred.',
    description: 'Shows your starred tools and lets you remove them. Favorites are per account.',
    icon: 'star',
    path: '/tools/favorites',
    apiPath: '/api/tools/tool-favorites',
    methods: ['GET', 'POST', 'DELETE'],
    authRequired: true,
    visibility: 'customer',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['favorites', 'starred', 'pinned'],
  },
  {
    slug: 'tool-reports',
    name: 'Saved Reports',
    category: 'diagnostics',
    summary: 'Diagnostic results you chose to save, downloadable and deletable.',
    description: 'Saves the exact result you saw (with credential-shaped fields stripped) so it can be downloaded, attached to a support ticket or compared later.',
    icon: 'file-archive',
    path: '/tools/reports',
    apiPath: '/api/tools/tool-reports',
    methods: ['GET', 'POST', 'DELETE'],
    authRequired: true,
    visibility: 'customer',
    rateLimitProfile: 'light',
    cacheSeconds: 0,
    timeoutMs: 5_000,
    keywords: ['reports', 'save', 'export', 'download'],
  },
  {
    slug: 'tool-monitors',
    name: 'Monitoring',
    category: 'diagnostics',
    summary: 'Scheduled SSL-expiry, DNS-record and email-configuration monitoring.',
    description:
      'Registers a monitor that the CloudHost247 worker evaluates on a schedule: SSL certificate expiry thresholds, specific DNS records whose value must not change, and the email authentication configuration (MX/SPF/DKIM/DMARC/BIMI). Notifications are delivered through the existing CloudHost247 notification system.',
    icon: 'bell-ring',
    path: '/tools/monitors',
    apiPath: '/api/tools/tool-monitors',
    methods: ['GET', 'POST', 'DELETE'],
    authRequired: true,
    visibility: 'customer',
    capability: 'dns-udp',
    rateLimitProfile: 'standard',
    cacheSeconds: 0,
    timeoutMs: 20_000,
    keywords: ['monitor', 'alert', 'ssl expiry', 'dns change', 'email config'],
  },
];

export const CATEGORY_LABELS: Record<ToolCategorySlug, string> = {
  dns: 'DNS Tools',
  ip: 'IP Tools',
  network: 'Network Tools',
  developer: 'Developer Tools',
  webmaster: 'Webmaster & SEO Tools',
  security: 'Security Tools',
  domain: 'Domain Tools',
  productivity: 'Productivity Tools',
  diagnostics: 'Diagnostics & Monitoring',
};

export function catalogEntry(slug: string): ToolCatalogEntry | undefined {
  return TOOL_CATALOG.find((entry) => entry.slug === slug);
}

/**
 * Tools that have no runnable API of their own (they are navigation/dashboard surfaces). They are
 * published in the catalogue so the dashboard can list them, but the executor refuses to "run"
 * them.
 */
export const NON_RUNNABLE_TOOL_SLUGS = new Set([
  'tool-history',
  'tool-favorites',
  'tool-reports',
  'tool-monitors',
]);

/** Public marketing-safe tool list used by tests to assert the catalogue is coherent. */
export const TOOL_SLUGS: readonly string[] = TOOL_CATALOG.map((entry) => entry.slug);
