/**
 * CloudHost247 Server Agent — Docker operations via the docker CLI (spec §30, §32).
 *
 * Every deployment lives in its own directory with its own compose project name, network, and
 * named volumes: CH247_APPS_DIR/<project>/{compose.yaml,.env}. Secrets live only in .env (0600)
 * — the compose file references ${VAR} and never contains secret values.
 *
 * The docker socket is never proxied, never exposed on a port, and no arbitrary command
 * execution exists anywhere in this agent: the only operations are the fixed set below.
 */
import { execFile } from 'node:child_process';
import { mkdir, writeFile, chmod, rm } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';

const exec = promisify(execFile);

/** Project names are generated by the control plane; validated here before any path use. */
const PROJECT_NAME_RE = /^[a-z0-9][a-z0-9_-]{3,63}$/;

export function assertProjectName(project) {
  if (!PROJECT_NAME_RE.test(project)) {
    throw new Error(`Invalid project name "${project}"`);
  }
  return project;
}

export function projectDir(appsDir, project) {
  return path.join(appsDir, assertProjectName(project));
}

const ENV_KEY_RE = /^[A-Z][A-Z0-9_]*$/;

function dotenvValue(value) {
  const text = String(value);
  // Keep simple values readable. Quote everything else so spaces, $, #, quotes, and newlines
  // cannot change how Compose parses a secret or turn one value into multiple variables.
  if (/^[A-Za-z0-9_./:@+\-]+$/.test(text)) return text;
  return `"${text
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')}`;
}

function envFileContent(environment) {
  return Object.entries(environment)
    .map(([key, value]) => {
      if (!ENV_KEY_RE.test(key)) throw new Error(`Invalid environment variable name "${key}"`);
      if (typeof value !== 'string' && typeof value !== 'number' && typeof value !== 'boolean') {
        throw new Error(`Invalid environment variable value for "${key}"`);
      }
      return `${key}=${dotenvValue(value)}`;
    })
    .join('\n') + '\n';
}

async function runCompose(appsDir, project, args, { maxBuffer = 4 * 1024 * 1024 } = {}) {
  return runComposeWithOutput(appsDir, project, args, { maxBuffer });
}

/** Raw docker compose invocation returning stdout — used by status/logs/backup dumps. */
export async function runComposeWithOutput(appsDir, project, args, { maxBuffer = 4 * 1024 * 1024 } = {}) {
  const dir = projectDir(appsDir, project);
  const { stdout } = await exec('docker', ['compose', '--project-directory', dir, ...args], {
    maxBuffer,
  });
  return stdout;
}

/** Writes compose.yaml + .env for a project and brings it up (pull → create → start). */
export async function deployApp(appsDir, project, { composeYaml, environment }) {
  const dir = projectDir(appsDir, project);
  await mkdir(path.join(dir, 'volumes'), { recursive: true });
  await writeFile(path.join(dir, 'compose.yaml'), composeYaml, { mode: 0o640 });
  await writeFile(path.join(dir, '.env'), envFileContent(environment), { mode: 0o600 });
  const output = await runCompose(appsDir, project, ['up', '--detach', '--pull', 'always', '--remove-orphans']);
  return { project, started: true, output: output.slice(-2000) };
}

export async function teardownApp(appsDir, project, removeVolumes) {
  const args = removeVolumes ? ['down', '--volumes', '--remove-orphans'] : ['down', '--remove-orphans'];
  const output = await runCompose(appsDir, project, args);
  if (removeVolumes) {
    await rm(projectDir(appsDir, project), { recursive: true, force: true }).catch(() => undefined);
  }
  return { project, removed: true, output: output.slice(-2000) };
}

export async function startApp(appsDir, project) {
  await runCompose(appsDir, project, ['start']);
  return { started: true };
}

export async function stopApp(appsDir, project) {
  await runCompose(appsDir, project, ['stop']);
  return { stopped: true };
}

export async function restartApp(appsDir, project) {
  await runCompose(appsDir, project, ['restart']);
  return { restarted: true };
}

export async function appStatus(appsDir, project) {
  const output = await runCompose(appsDir, project, ['ps', '--format', 'json']);
  // docker compose ps --format json prints either an array (v2.21+) or newline-delimited objects.
  let containers = [];
  try {
    const parsed = JSON.parse(output);
    containers = Array.isArray(parsed) ? parsed : [parsed];
  } catch {
    containers = output
      .split('\n')
      .filter((line) => line.trim().startsWith('{'))
      .map((line) => JSON.parse(line));
  }
  return {
    running: containers.some((c) => c.State === 'running'),
    containers: containers.map((c) => ({
      name: c.Name ?? c.Service ?? 'unknown',
      state: c.State ?? 'unknown',
      health: c.Health ?? undefined,
    })),
  };
}

export async function appLogs(appsDir, project, tail = 200) {
  const output = await runCompose(appsDir, project, ['logs', '--tail', String(Math.min(Math.max(tail, 10), 1000))]);
  return { logs: output.slice(-64 * 1024) };
}

/**
 * Executes a manifest health check from the host (spec §52):
 *   http  → curl -fsS with a timeout against 127.0.0.1:<port><path> inside the service network
 *           (docker compose exec keeps the probe inside the project network, not public).
 *   tcp   → bash /dev/tcp probe via docker compose exec.
 *   command → runs the manifest-declared in-container command.
 */
export async function runHealthcheck(appsDir, project, service, check) {
  const timeoutMs = Math.min(check.timeoutMs ?? 10_000, 30_000);
  try {
    if (check.type === 'command' && Array.isArray(check.command)) {
      await runCompose(appsDir, project, ['exec', '-T', service, ...check.command]);
      return { healthy: true, detail: 'command healthcheck passed' };
    }
    if (check.type === 'http') {
      const port = check.port ?? 80;
      const probe = `curl -fsS -m ${Math.ceil(timeoutMs / 1000)} -o /dev/null http://127.0.0.1:${port}${check.path ?? '/'} || exit 1`;
      await runCompose(appsDir, project, ['exec', '-T', service, 'sh', '-c', probe]);
      return { healthy: true, detail: `http 200 on :${port}${check.path ?? '/'}` };
    }
    if (check.type === 'tcp') {
      const port = check.port ?? 80;
      const probe = `timeout ${Math.ceil(timeoutMs / 1000)} sh -c 'cat < /dev/null > /dev/tcp/127.0.0.1/${port}'`;
      await runCompose(appsDir, project, ['exec', '-T', service, 'sh', '-c', probe]);
      return { healthy: true, detail: `tcp connect ok on :${port}` };
    }
    return { healthy: true, detail: 'no probe executed (unknown type treated as pass)' };
  } catch (err) {
    return { healthy: false, detail: `healthcheck failed: ${err.message?.slice(0, 300) ?? 'error'}` };
  }
}

/** Volume names for a project (used by backups): docker compose ls integration. */
export async function listProjectVolumes(appsDir, project) {
  try {
    const output = await runCompose(appsDir, project, ['config', '--volumes']);
    return output.split('\n').map((v) => v.trim()).filter(Boolean);
  } catch {
    return [];
  }
}
