<?php
if(!defined('WHMCS'))die('Direct access denied');require_once __DIR__.'/bootstrap.php';
use CloudHost247\Rdp\Api\ConfigResolver;use CloudHost247\Rdp\Api\ProviderClient;use CloudHost247\Rdp\Operations\DatabaseLedger;use CloudHost247\Rdp\Operations\LifecycleService;use CloudHost247\Foundation\Support\AuditLogger;use CloudHost247\Foundation\Support\SafeError;
function RDP_MetaData(){return array('DisplayName'=>'CloudHost247 Secure RDP','APIVersion'=>'1.1','RequiresServer'=>true);}
function RDP_ConfigOptions(){return array('Provider Product ID'=>array('Type'=>'text','Size'=>'40','Description'=>'Exact provider product identifier from the authorized provider catalog.'),'Customer Reboot Allowed'=>array('Type'=>'yesno','Description'=>'Reserved for a verified provider capability; no client mutation is exposed by default.'));}
function RDP_TestConnection(array$p){try{$c=rdp_client($p);$c->test();return array('success'=>true,'error'=>'');}catch(\Throwable$e){$safe=SafeError::from($e,'cloudhost247_rdp','connection.test','Provider connection could not be verified.');return array('success'=>false,'error'=>$safe['display']);}}
function RDP_CreateAccount(array$p){return rdp_lifecycle_result('create',$p);}
function RDP_SuspendAccount(array$p){return rdp_lifecycle_result('suspend',$p);}
function RDP_UnsuspendAccount(array$p){return rdp_lifecycle_result('unsuspend',$p);}
function RDP_TerminateAccount(array$p){return rdp_lifecycle_result('terminate',$p);}
function rdp_lifecycle_result($operation,array$p){try{$ledger=rdp_ledger();$service=new LifecycleService(rdp_client($p),$ledger);$sid=(int)$p['serviceid'];$cid=(int)$p['userid'];if(!$sid||!$cid)throw new \InvalidArgumentException('Valid WHMCS service and client context is required.');if($operation==='create'){$product=trim((string)($p['configoption1']??''));if(!preg_match('/^[A-Za-z0-9._:-]{1,191}$/',$product))throw new \InvalidArgumentException('A valid provider product identifier is required.');$result=$service->create($sid,$cid,$product);}else$result=$service->{$operation}($sid,$cid);$status=$result['status'];AuditLogger::record('cloudhost247_rdp','service.'.$operation,'service',$sid,array(),array('status'=>$status),'completed'===$status?'success':'failed',$status==='completed'?null:$status);if($status==='completed')return'success';if($status==='reconciliation_required')return'Provider result is uncertain. Reconciliation is required before retrying.';return'RDP '.$operation.' was not confirmed. Reference the CloudHost247 audit event.';}catch(\Throwable$e){$safe=SafeError::from($e,'cloudhost247_rdp','service.'.$operation,'The RDP operation could not be completed safely.');return$safe['display'];}}
function RDP_AdminCustomButtonArray(){return array('Refresh Verified Status'=>'refreshVerifiedStatus','Reconcile State (Read Only)'=>'reconcileState');}
function RDP_refreshVerifiedStatus(array$p){return rdp_read_action($p,false);}function RDP_reconcileState(array$p){return rdp_read_action($p,true);}
function rdp_read_action(array$p,$reconcile){try{$ledger=rdp_ledger();$service=new LifecycleService(rdp_client($p),$ledger);$result=$service->reconcile((int)$p['serviceid'],(int)$p['userid']);return in_array($result['status'],array('matched','mismatch'),true)?'success':'Provider state is not verified; administrator intervention is required.';}catch(\Throwable$e){return SafeError::from($e,'cloudhost247_rdp','service.reconcile','RDP state could not be verified.')['display'];}}
function RDP_ClientArea(array$p){try{$uid=(int)($_SESSION['uid']??0);if(!$uid||$uid!==(int)$p['userid'])throw new \RuntimeException('Authenticated service ownership is required.');$ledger=rdp_ledger();$b=$ledger->binding((int)$p['serviceid']);if(!$b||(int)$b->client_id!==$uid)throw new \RuntimeException('Service binding is unavailable.');$details=json_decode($b->safe_details_json?:'{}',true);if(!is_array($details))$details=array();return array('tabOverviewReplacementTemplate'=>'templates/overview.tpl','templateVariables'=>array('rdpService'=>array('status'=>$b->status,'hostname'=>$details['hostname']??'NOT VERIFIED','username'=>$details['username']??'NOT VERIFIED','ip'=>$details['ip']??'NOT VERIFIED','location'=>$details['location']??'NOT VERIFIED','product'=>$details['product']??'NOT VERIFIED','last_verified'=>$b->last_verified_at?:'NOT VERIFIED')));}catch(\Throwable$e){$safe=SafeError::from($e,'cloudhost247_rdp','client.overview','RDP service information is unavailable.');return array('tabOverviewReplacementTemplate'=>'templates/error.tpl','templateVariables'=>array('rdpError'=>$safe['display']));}}
function RDP_AdminServicesTabFields(array$p){try{$ledger=rdp_ledger();$b=$ledger->binding((int)$p['serviceid']);if(!$b)return array('RDP Provider State'=>'NOT VERIFIED');$details=json_decode($b->safe_details_json?:'{}',true);return array('RDP Provider State'=>htmlspecialchars($b->status,ENT_QUOTES,'UTF-8'),'Provider Service Reference'=>htmlspecialchars($b->provider_service_id,ENT_QUOTES,'UTF-8'),'Last Verified'=>htmlspecialchars($b->last_verified_at?:'NOT VERIFIED',ENT_QUOTES,'UTF-8'),'Safe Details'=>htmlspecialchars(json_encode($details),ENT_QUOTES,'UTF-8'));}catch(\Throwable$e){return array('RDP Provider State'=>'NOT VERIFIED');}}
function RDP_AdminServicesTabFieldsSave(array$p){return;}
function rdp_ledger(){$l=new DatabaseLedger();$l->ensureSchema();return$l;}
function rdp_client(array$p){$resolved=ConfigResolver::resolve($p);return new ProviderClient($resolved['endpoint'],$resolved['token']);}
