<?php
$root=dirname(__DIR__,2);foreach(array('Contracts/Provider','Contracts/Ledger','Api/ProviderException','Api/ProviderClient','Operations/LifecycleService')as$f)require_once$root.'/modules/servers/RDP/lib/'.$f.'.php';
class FakeLedger implements \CloudHost247\Rdp\Contracts\Ledger{public$ops=array();public$bindings=array();function operation($k){return$this->ops[$k]??null;}function begin(array$o){$x=(object)$o;$x->status='running';$this->ops[$o['idempotency_key']]=$x;}function retry($k){$this->ops[$k]->status='running';}function finish($k,$s,array$e=array(),$c=null){$this->ops[$k]->status=$s;$this->ops[$k]->error_code=$c;$this->ops[$k]->evidence=$e;}function binding($id){return$this->bindings[$id]??null;}function bind(array$b){$this->bindings[$b['service_id']]=(object)array('whmcs_service_id'=>$b['service_id'],'client_id'=>$b['client_id'],'provider_service_id'=>$b['provider_service_id'],'status'=>$b['status'],'updated_at'=>'1','safe_details_json'=>json_encode($b['details']));}function updateBinding($id,$s,array$d=array()){$this->bindings[$id]->status=$s;$this->bindings[$id]->updated_at=(string)((int)$this->bindings[$id]->updated_at+1);}function recent($id,$l=25){return array_values($this->ops);}}
class FakeProvider implements \CloudHost247\Rdp\Contracts\Provider{public$responses=array();public$calls=array();function next($op){$this->calls[]=$op;$r=array_shift($this->responses);if($r instanceof Throwable)throw$r;return$r;}function create(array$r,$k){return$this->next('create');}function suspend($r,$k){return$this->next('suspend');}function unsuspend($r,$k){return$this->next('unsuspend');}function terminate($r,$k){return$this->next('terminate');}function service($r){return$this->next('service');}function test(){return array('ok'=>true);}}
function response($status,$id='svc-1'){return array('status'=>$status,'operation_id'=>'op-1','service'=>array('id'=>$id,'status'=>$status,'hostname'=>'rdp.example.test','username'=>'administrator','ip'=>'192.0.2.8'));}
$tests=array();
$p=new FakeProvider();$l=new FakeLedger();$p->responses[]=response('active');$r=(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->create(1,2,'plan-1');$tests['provision success']=$r['status']==='completed'&&$l->binding(1)->provider_service_id==='svc-1';
$p=new FakeProvider();$l=new FakeLedger();$p->responses[]=new \CloudHost247\Rdp\Api\ProviderException('rejected','no',false);$r=(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->create(1,2,'plan');$tests['provision failure']=$r['status']==='failed';
$p=new FakeProvider();$l=new FakeLedger();$p->responses[]=new \CloudHost247\Rdp\Api\ProviderException('transport','timeout',true);$s=new \CloudHost247\Rdp\Operations\LifecycleService($p,$l);$r=$s->create(1,2,'plan');$r2=$s->create(1,2,'plan');$tests['timeout reconciles without duplicate']=$r['status']==='reconciliation_required'&&$r2['status']==='reconciliation_required'&&count($p->calls)===1;
$p=new FakeProvider();$l=new FakeLedger();$p->responses[]=response('active');$s=new \CloudHost247\Rdp\Operations\LifecycleService($p,$l);$s->create(1,2,'plan');$s->create(1,2,'plan');$tests['duplicate provisioning']=$p->calls===array('create');
foreach(array('suspend'=>'suspended','unsuspend'=>'active','terminate'=>'terminated')as$op=>$state){$p=new FakeProvider();$l=new FakeLedger();$l->bind(array('service_id'=>1,'client_id'=>2,'provider_service_id'=>'svc-1','status'=>'active','details'=>array()));$p->responses[]=response($state);$r=(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->{$op}(1,2);$tests[$op.' success']=$r['status']==='completed'&&$l->binding(1)->status===$state;$p=new FakeProvider();$l=new FakeLedger();$l->bind(array('service_id'=>1,'client_id'=>2,'provider_service_id'=>'svc-1','status'=>'active','details'=>array()));$p->responses[]=new \CloudHost247\Rdp\Api\ProviderException('rejected','no',false);$r=(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->{$op}(1,2);$tests[$op.' failure']=$r['status']==='failed';}
$p=new FakeProvider();$l=new FakeLedger();$l->bind(array('service_id'=>1,'client_id'=>2,'provider_service_id'=>'svc-1','status'=>'active','details'=>array()));try{(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->suspend(1,99);$tests['wrong ownership']=false;}catch(Throwable$e){$tests['wrong ownership']=true;}
$p=new FakeProvider();$l=new FakeLedger();$l->bind(array('service_id'=>1,'client_id'=>2,'provider_service_id'=>'svc-1','status'=>'active','details'=>array()));$p->responses[]=array('service'=>array('id'=>'svc-1','status'=>'suspended'));$r=(new \CloudHost247\Rdp\Operations\LifecycleService($p,$l))->reconcile(1,2);$tests['reconciliation mismatch']=$r['status']==='mismatch'&&$r['remote']==='suspended';
putenv('CH247_RDP_ALLOWED_HOSTS=api.example.test');$captured=array();$transport=function($m,$u,$h,$b,$c)use(&$captured){$captured=compact('m','u','h','b');return array('status'=>200,'body'=>'{"service":{"id":"svc-1","status":"active"}}');};$client=new \CloudHost247\Rdp\Api\ProviderClient('https://api.example.test','1234567890123456',$transport);$client->service('svc-1');$joined=implode("\n",$captured['h']);$tests['credential not in URL or body']=strpos($captured['u'],'123456')===false&&strpos((string)$captured['b'],'123456')===false&&strpos($joined,'Bearer ')!==false;
try{new \CloudHost247\Rdp\Api\ProviderClient('http://api.example.test','1234567890123456',$transport);$tests['https required']=false;}catch(Throwable$e){$tests['https required']=true;}
try{new \CloudHost247\Rdp\Api\ProviderClient('https://evil.example','1234567890123456',$transport);$tests['host allowlist']=false;}catch(Throwable$e){$tests['host allowlist']=true;}
$redirect=function(){return array('status'=>302,'body'=>'{}');};try{(new \CloudHost247\Rdp\Api\ProviderClient('https://api.example.test','1234567890123456',$redirect))->service('svc');$tests['redirect rejected']=false;}catch(Throwable$e){$tests['redirect rejected']=true;}
$malformed=function(){return array('status'=>200,'body'=>'not-json');};try{(new \CloudHost247\Rdp\Api\ProviderClient('https://api.example.test','1234567890123456',$malformed))->service('svc');$tests['malformed response rejected']=false;}catch(Throwable$e){$tests['malformed response rejected']=true;}
$fail=0;foreach($tests as$n=>$ok){echo($ok?'ok':'not ok')." - $n\n";if(!$ok)$fail++;}exit($fail?1:0);
