<?php
namespace CloudHost247\Rdp\Api;
use CloudHost247\Rdp\Contracts\Provider;
final class ProviderClient implements Provider
{
 private $base,$token,$transport;
 public function __construct($endpoint,$token,callable$transport=null){$parts=parse_url(trim((string)$endpoint));$host=strtolower(isset($parts['host'])?$parts['host']:'');$allowed=array_filter(array_map('trim',explode(',',strtolower((string)getenv('CH247_RDP_ALLOWED_HOSTS')))));if(($parts['scheme']??'')!=='https'||!$host||!in_array($host,$allowed,true)||isset($parts['user'])||isset($parts['pass'])||isset($parts['query'])||isset($parts['fragment']))throw new \InvalidArgumentException('RDP provider endpoint must be an allowlisted HTTPS origin.');if(!is_string($token)||strlen($token)<16||strlen($token)>4096)throw new \InvalidArgumentException('RDP provider authentication is unavailable.');$port=isset($parts['port'])?':'.(int)$parts['port']:'';$this->base='https://'.$host.$port.rtrim(isset($parts['path'])?$parts['path']:'','/');$this->token=$token;$this->transport=$transport?:array($this,'curl');}
 public function test(){return$this->request('GET','/me',null,null,true);}
 public function create(array$r,$key){return$this->request('POST','/services',array('product_id'=>(string)$r['product_id'],'client_reference'=>(string)$r['client_reference']),$key,false);}
 public function suspend($ref,$key){return$this->action($ref,'suspend',$key);}public function unsuspend($ref,$key){return$this->action($ref,'unsuspend',$key);}public function terminate($ref,$key){return$this->action($ref,'terminate',$key);}public function service($ref){return$this->request('GET','/services/'.$this->reference($ref),null,null,true);}
 private function action($ref,$action,$key){return$this->request('POST','/services/'.$this->reference($ref).'/'.$action,array(),$key,false);}
 private function reference($v){$v=(string)$v;if(!preg_match('/^[A-Za-z0-9._:-]{1,191}$/',$v))throw new \InvalidArgumentException('Invalid provider service reference.');return rawurlencode($v);}
 private function request($method,$path,$body,$key,$safeRetry){$correlation=bin2hex(random_bytes(16));$headers=array('Accept: application/json','Content-Type: application/json','Authorization: Bearer '.$this->token,'X-Correlation-ID: '.$correlation);if($key)$headers[]='Idempotency-Key: '.$key;$attempts=$safeRetry?2:1;for($i=0;$i<$attempts;$i++){try{$response=call_user_func($this->transport,$method,$this->base.$path,$headers,$body===null?null:json_encode($body),$correlation);}catch(\Throwable$e){if($i+1<$attempts)continue;throw new ProviderException('transport','Provider communication failed.',!$safeRetry);}if(!is_array($response)||!isset($response['status'],$response['body']))throw new ProviderException('invalid_response','Provider response envelope is invalid.',!$safeRetry);$status=(int)$response['status'];if($status<200||$status>=300){$uncertain=$method!=='GET'&&($status===0||$status>=500);throw new ProviderException('http_'.$status,'Provider rejected or could not confirm the request.',$uncertain);}$decoded=json_decode((string)$response['body'],true);if(!is_array($decoded)||json_last_error()!==JSON_ERROR_NONE)throw new ProviderException('malformed_json','Provider returned malformed JSON.',$method!=='GET');return$this->validate($decoded,$method,$path);}}
 private function validate(array$r,$method,$path){if(substr($path,0,9)==='/services'&&$method==='GET'){if(empty($r['service'])||!is_array($r['service']))throw new ProviderException('schema','Provider service response is incomplete.');return$this->serviceShape($r);}if($method==='POST'){if(empty($r['status'])||!in_array($r['status'],array('active','provisioning','suspended','terminated','accepted'),true))throw new ProviderException('schema','Provider mutation response has an invalid status.',true);if(empty($r['operation_id'])||!preg_match('/^[A-Za-z0-9._:-]{1,191}$/',(string)$r['operation_id']))throw new ProviderException('schema','Provider operation reference is invalid.',true);if(isset($r['service']))$r=$this->serviceShape($r);return$r;}return$r;}
 private function serviceShape(array$r){$s=$r['service'];if(empty($s['id'])||!preg_match('/^[A-Za-z0-9._:-]{1,191}$/',(string)$s['id']))throw new ProviderException('schema','Provider service identifier is invalid.');$allowed=array('id','status','hostname','username','ip','location','product');$safe=array();foreach($allowed as$k)if(isset($s[$k])&&is_scalar($s[$k]))$safe[$k]=substr((string)$s[$k],0,255);$r['service']=$safe;unset($r['password'],$r['token'],$r['secret']);return$r;}
 public function curl($method,$url,array$headers,$body,$correlation){$ch=curl_init();curl_setopt_array($ch,array(CURLOPT_URL=>$url,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>false,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_MAXREDIRS=>0,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>$headers,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2));if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,$body);$response=curl_exec($ch);if($response===false){curl_close($ch);throw new ProviderException('transport','Provider communication failed.',$method!=='GET');}$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if(strlen($response)>1048576)throw new ProviderException('response_too_large','Provider response exceeded the safe limit.',$method!=='GET');return array('status'=>$status,'body'=>$response);}
}
