/**
 * Tools Center — robots.txt generator and analyser (spec §39).
 *
 * Generator: builds a valid robots.txt from explicit choices (crawl policy, sitemaps, host,
 * crawl-delay), and refuses to emit the contradictory combinations users most often ask for
 * (Allow: / and Disallow: / in the same group) without saying why.
 *
 * Analyser: parses an existing robots.txt the way a crawler does — groups, user-agents, rules and
 * the longest-match precedence — and reports what it finds, including the traps (a BOM, a wildcard
 * where the crawler does not support it, a sitemap outside the group, "Disallow:" with an empty
 * value, comments in the middle of a line).
 */
import { invalidInput } from '../core/errors';

export interface RobotsTemplateOptions {
  mode: 'block-all' | 'allow-all' | 'block-ai' | 'allow-search-engines' | 'custom';
  sitemaps?: string[];
  host?: string;
  crawlDelaySeconds?: number;
  disallowPaths?: string[];
  allowPaths?: string[];
  userAgents?: string[];
  keepOutOfIndex?: boolean;
}

export interface RobotsTemplateResult {
  text: string;
  lines: number;
  groups: Array<{ userAgents: string[]; rules: string[] }>;
  warnings: string[];
  notes: string[];
}

const AI_CRAWLERS = ['GPTBot', 'CCBot', 'ClaudeBot', 'anthropic-ai', 'Google-Extended', 'Bytespider', 'PerplexityBot', 'Applebot-Extended'];

export function generateRobots(options: RobotsTemplateOptions): RobotsTemplateResult {
  const warnings: string[] = [];
  const groups: RobotsTemplateResult['groups'] = [];
  const sitemaps = (options.sitemaps ?? []).map((sitemap) => sitemap.trim()).filter(Boolean);
  for (const sitemap of sitemaps) {
    if (!/^https?:\/\//i.test(sitemap)) throw invalidInput(`Sitemap URLs must be absolute (start with http:// or https://): "${sitemap}"`);
  }
  if (options.crawlDelaySeconds !== undefined && (!Number.isInteger(options.crawlDelaySeconds) || options.crawlDelaySeconds < 0)) {
    throw invalidInput('Crawl-delay must be a whole number of seconds (0 removes it).');
  }

  const searchEngineAgents = ['Googlebot', 'Bingbot', 'DuckDuckBot', 'Applebot'];
  switch (options.mode) {
    case 'block-all':
      groups.push({ userAgents: ['*'], rules: ['Disallow: /'] });
      break;
    case 'allow-all':
      groups.push({ userAgents: ['*'], rules: ['Allow: /'] });
      break;
    case 'block-ai':
      groups.push({ userAgents: ['*'], rules: ['Allow: /'] });
      for (const crawler of AI_CRAWLERS) groups.push({ userAgents: [crawler], rules: ['Disallow: /'] });
      break;
    case 'allow-search-engines':
      groups.push({ userAgents: ['*'], rules: ['Disallow: /'] });
      groups.push({ userAgents: searchEngineAgents, rules: ['Allow: /'] });
      break;
    case 'custom': {
      const agents = (options.userAgents && options.userAgents.length > 0 ? options.userAgents : ['*']).map((agent) => agent.trim()).filter(Boolean);
      const rules: string[] = [];
      for (const path of options.allowPaths ?? []) if (path.trim()) rules.push(`Allow: ${path.trim()}`);
      for (const path of options.disallowPaths ?? []) if (path.trim()) rules.push(`Disallow: ${path.trim()}`);
      if (rules.length === 0) throw invalidInput('Add at least one Allow or Disallow rule, or choose one of the presets.');
      groups.push({ userAgents: agents, rules });
      break;
    }
    default:
      throw invalidInput('Choose a mode: block-all, allow-all, block-ai, allow-search-engines or custom.');
  }

  const lines: string[] = [
    '# robots.txt generated by CloudHost247 Tools Center',
    `# Generated ${new Date().toISOString().slice(0, 10)}. Review the rules below before publishing.`,
    '',
  ];
  for (const group of groups) {
    for (const agent of group.userAgents) lines.push(`User-agent: ${agent}`);
    for (const rule of group.rules) lines.push(rule);
    if (options.crawlDelaySeconds && options.crawlDelaySeconds > 0 && group.userAgents.includes('*')) {
      lines.push(`Crawl-delay: ${options.crawlDelaySeconds}`);
      warnings.push('Crawl-delay is honoured by Bing and some others, but Google ignores it (use Search Console crawl-rate settings instead).');
    }
    lines.push('');
  }
  if (options.keepOutOfIndex) {
    lines.push('# To keep a page out of search results you also need a noindex meta tag or X-Robots-Tag header:');
    lines.push('# robots.txt prevents crawling, NOT indexing. A blocked URL can still appear in results without a snippet.');
    lines.push('');
  }
  if (sitemaps.length > 0) {
    for (const sitemap of sitemaps) lines.push(`Sitemap: ${sitemap}`);
    lines.push('');
  }
  if (options.host) lines.push(`Host: ${options.host}`, '');

  if (options.mode === 'allow-search-engines') {
    warnings.push('This configuration blocks every crawler except the named search engines. Verify the list against the engines you actually care about, and remember that blocking a crawler is not a security control.');
  }
  if (options.mode === 'block-all') {
    warnings.push('Disallow: / keeps well-behaved crawlers out, but it does not protect anything. A page you do not want public must require authentication or be removed.');
  }

  return {
    text: lines.join('\n'),
    lines: lines.length,
    groups,
    warnings,
    notes: [
      'robots.txt is a request, not an enforcement mechanism. Crawlers that ignore it (and anyone with a script) will still fetch what is reachable.',
      'The longest matching rule wins for a given crawler; Allow and Disallow of equal length means Allow wins in the modern specification.',
      'Only the group that matches the crawler applies. A crawler that matches a specific named group ignores all rules in the * group.',
    ],
  };
}

export interface RobotsRule {
  type: 'allow' | 'disallow' | 'crawl-delay' | 'sitemap' | 'host' | 'clean-param' | 'unknown';
  value: string;
  line: number;
}

export interface RobotsGroup {
  userAgents: string[];
  rules: RobotsRule[];
  line: number;
}

export interface RobotsAnalysis {
  groups: RobotsGroup[];
  sitemaps: string[];
  host: string | null;
  crawlDelays: Array<{ userAgent: string; seconds: number }>;
  totals: { lines: number; groups: number; allowRules: number; disallowRules: number; comments: number; blank: number };
  issues: Array<{ severity: 'warning' | 'error'; code: string; line: number | null; message: string }>;
  tests: Array<{ userAgent: string; path: string; decision: 'ALLOWED' | 'DISALLOWED' | 'NO_RULE'; matchedRule: string | null; note: string }>;
  notes: string[];
}

/** Parses robots.txt into groups exactly as the REP (robots exclusion protocol) does. */
export function analyseRobots(input: { text: string; testPaths?: string[]; testUserAgents?: string[] }): RobotsAnalysis {
  const text = input.text ?? '';
  if (text.trim().length === 0) throw invalidInput('Paste a robots.txt to analyse.');
  if (text.length > 512 * 1024) throw invalidInput('The file is larger than 512 KB, which is well beyond a real robots.txt.');

  const issues: RobotsAnalysis['issues'] = [];
  if (text.charCodeAt(0) === 0xfeff) issues.push({ severity: 'error', code: 'BOM', line: 1, message: 'The file starts with a UTF-8 byte-order mark. Some crawlers treat the first line as garbage because of it.' });

  const lines = text.split(/\r?\n/);
  const groups: RobotsGroup[] = [];
  let current: RobotsGroup | null = null;
  let expectingUserAgent = false;
  const sitemaps: string[] = [];
  const crawlDelays: RobotsAnalysis['crawlDelays'] = [];
  let host: string | null = null;
  let comments = 0;
  let blank = 0;

  for (let index = 0; index < lines.length; index += 1) {
    const lineNumber = index + 1;
    let line = (lines[index] ?? '').replace(/^\uFEFF/, '');
    const commentIndex = line.indexOf('#');
    if (commentIndex !== -1) {
      comments += 1;
      line = line.slice(0, commentIndex);
    }
    line = line.trim();
    if (line.length === 0) {
      blank += 1;
      expectingUserAgent = false;
      continue;
    }

    const match = /^([A-Za-z][A-Za-z-]*)\s*:\s*(.*)$/.exec(line);
    if (!match) {
      issues.push({ severity: 'warning', code: 'UNPARSEABLE_LINE', line: lineNumber, message: `Line ${lineNumber} is not a "Field: value" pair and will be ignored: "${line.slice(0, 80)}".` });
      continue;
    }
    const field = (match[1] ?? '').toLowerCase();
    const value = (match[2] ?? '').trim();

    if (field === 'user-agent') {
      if (!expectingUserAgent || !current) {
        current = { userAgents: [], rules: [], line: lineNumber };
        groups.push(current);
      }
      current.userAgents.push(value);
      expectingUserAgent = true;
      if (value.length === 0) issues.push({ severity: 'error', code: 'EMPTY_USER_AGENT', line: lineNumber, message: `Line ${lineNumber} has an empty User-agent value.` });
      continue;
    }

    if (field === 'sitemap') {
      sitemaps.push(value);
      if (!/^https?:\/\//i.test(value)) issues.push({ severity: 'warning', code: 'RELATIVE_SITEMAP', line: lineNumber, message: `The Sitemap value on line ${lineNumber} is not an absolute URL.` });
      continue;
    }
    if (field === 'host') {
      host = value;
      continue;
    }

    if (!current) {
      issues.push({ severity: 'warning', code: 'RULE_BEFORE_GROUP', line: lineNumber, message: `Line ${lineNumber} contains a ${field} rule before any User-agent group; crawlers ignore it.` });
      continue;
    }

    if (field === 'allow' || field === 'disallow') {
      if (!expectingUserAgent && current.rules.length === 0) {
        // Not an error: a rule directly after the user-agent list is the normal shape.
      }
      expectingUserAgent = false;
      current.rules.push({ type: field, value: value.length > 0 ? value : '/', line: lineNumber });
      if (field === 'disallow' && value.length === 0) {
        issues.push({ severity: 'warning', code: 'EMPTY_DISALLOW', line: lineNumber, message: `Line ${lineNumber} is "Disallow:" with no path. That means "allow everything", which is the opposite of what most authors intend. The parsed rule is treated as "Disallow: /" by this analyser for display, but crawlers treat an empty value as no restriction.` });
      }
      if (/[?*$]/.test(value)) {
        issues.push({
          severity: 'warning',
          code: 'WILDCARD',
          line: lineNumber,
          message: `Line ${lineNumber} uses wildcards/hints (${/[*]/.test(value) ? '*' : ''}${/[$]/.test(value) ? '$' : ''}). Google, Bing and modern crawlers support them, but some robots.txt parsers ignore wildcard characters and will read this rule as a literal path.`,
        });
      }
      continue;
    }

    if (field === 'crawl-delay') {
      const seconds = Number(value);
      if (!Number.isFinite(seconds) || seconds < 0) {
        issues.push({ severity: 'warning', code: 'BAD_CRAWL_DELAY', line: lineNumber, message: `The Crawl-delay on line ${lineNumber} is not a number.` });
      } else {
        for (const agent of current.userAgents) crawlDelays.push({ userAgent: agent, seconds });
      }
      continue;
    }

    current.rules.push({ type: 'unknown', value: `${field}: ${value}`, line: lineNumber });
  }

  for (const group of groups) {
    if (group.userAgents.length === 0) issues.push({ severity: 'error', code: 'GROUP_WITHOUT_AGENT', line: group.line, message: `The group at line ${group.line} has rules but no User-agent.` });
    const hasBlockAll = group.rules.some((rule) => rule.type === 'disallow' && rule.value === '/');
    const hasAllowAll = group.rules.some((rule) => rule.type === 'allow' && rule.value === '/');
    if (hasBlockAll && hasAllowAll) {
      issues.push({
        severity: 'warning',
        code: 'CONTRADICTORY_GROUP',
        line: group.line,
        message: `The group for ${group.userAgents.join(', ')} contains both "Disallow: /" and "Allow: /". Modern crawlers resolve equal-length rules in favour of Allow, so the block does not apply.`,
      });
    }
  }
  if (sitemaps.length === 0) {
    issues.push({ severity: 'warning', code: 'NO_SITEMAP', line: null, message: 'No Sitemap directive is present. It is optional, but it is how crawlers discover URLs that no page links to. The sitemap should also be submitted in Search Console.' });
  }

  // Evaluate test paths with the real longest-match precedence.
  const testPaths = input.testPaths && input.testPaths.length > 0 ? input.testPaths : ['/', '/admin/', '/private/page.html', '/images/logo.png'];
  const testUserAgents = input.testUserAgents && input.testUserAgents.length > 0 ? input.testUserAgents : ['*', 'Googlebot', ...AI_CRAWLERS.slice(0, 2)];
  const tests: RobotsAnalysis['tests'] = [];
  for (const userAgent of testUserAgents) {
    const group = groups.find((candidate) => candidate.userAgents.includes(userAgent)) ?? groups.find((candidate) => candidate.userAgents.includes('*')) ?? null;
    for (const path of testPaths) {
      if (!group) {
        tests.push({ userAgent, path, decision: 'NO_RULE', matchedRule: null, note: 'No matching group, so the crawler is unrestricted.' });
        continue;
      }
      let best: { rule: RobotsRule; length: number } | null = null;
      for (const rule of group.rules) {
        if (rule.type !== 'allow' && rule.type !== 'disallow') continue;
        const pattern = rule.value;
        const matches = pattern === '/' ? path.startsWith('/') : path.startsWith(pattern.replace(/[*$].*$/, ''));
        if (!matches) continue;
        const length = pattern.replace(/[*$]/g, '').length;
        if (!best || length >= best.length) best = { rule, length };
      }
      tests.push({
        userAgent,
        path,
        decision: best ? (best.rule.type === 'allow' ? 'ALLOWED' : 'DISALLOWED') : 'NO_RULE',
        matchedRule: best ? `${best.rule.type}: ${best.rule.value}` : null,
        note: best ? `Matched "${best.rule.value}" on line ${best.rule.line}; the longest match wins.` : 'No rule matches, so the path is allowed.',
      });
    }
  }

  return {
    groups,
    sitemaps,
    host,
    crawlDelays,
    totals: {
      lines: lines.length,
      groups: groups.length,
      allowRules: groups.reduce((sum, group) => sum + group.rules.filter((rule) => rule.type === 'allow').length, 0),
      disallowRules: groups.reduce((sum, group) => sum + group.rules.filter((rule) => rule.type === 'disallow').length, 0),
      comments,
      blank,
    },
    issues,
    tests,
    notes: [
      'Rules are matched with the longest-pattern-wins precedence used by Google and Bing. Wildcards in a path are approximated in the decision table (the literal prefix up to * is matched); a full pattern matcher belongs in a crawler, not in a checker.',
      'robots.txt is not access control. Use authentication for anything private, and a noindex directive or header for anything that must not appear in search results.',
      'A crawler is allowed to fetch robots.txt itself, always, even under Disallow: /.',
    ],
  };
}

export { invalidInput as robotsInvalidInput };
