id: bookstack
name: BookStack
category: documents
description: Platform for organising and storing information in books, chapters, and pages.
website: https://bookstackapp.com
repository: https://github.com/BookStackApp/BookStack
documentation: https://www.bookstackapp.com/docs
license: MIT
featured: false
popularity: 530
deployment:
  engine: docker-compose
supportedHostingTypes:
- docker
- vps
- dedicated
requirements:
  cpu: 1
  memory: 1024
  storage: 20480
  recommended:
    cpu: 1
    memory: 2048
    storage: 40960
services:
  app:
    image: lscr.io/linuxserver/bookstack
    internal: false
    port: 80
    volumes:
    - /config
    dependsOn:
    - db
  db:
    image: mariadb:11
    internal: true
    volumes:
    - /var/lib/mysql
    database: mariadb
environment:
  required: []
  optional:
  - key: APP_URL
    defaultFromUrl: true
domain:
  enabled: true
  primaryRequired: false
healthcheck:
  type: http
  path: /
  port: 80
ssl:
  enabled: true
backup:
  enabled: true
  includes:
  - volumes
  - database
update:
  strategy: pull-and-recreate
versions:
- version: '24.12'
  image: lscr.io/linuxserver/bookstack:24.12.1-ls
  stable: true
