<?php
namespace CloudHost247\Builder\Support;

/**
 * Identifier helpers.
 *
 * Node identifiers are written into class names and data attributes on the
 * published page, so they are restricted to a CSS- and attribute-safe alphabet
 * and are always regenerated by the server: a document supplied by a browser
 * can never introduce an identifier that escapes a selector or an attribute.
 */
final class Ids
{
    const NODE_PATTERN = '/^[a-z][a-z0-9]{3,31}$/';
    const KEY_PATTERN = '/^[a-z][a-z0-9_-]{1,63}$/';

    public static function node($prefix = 'n')
    {
        $prefix = preg_match('/^[a-z]{1,3}$/', (string) $prefix) === 1 ? (string) $prefix : 'n';
        return $prefix . bin2hex(random_bytes(6));
    }

    public static function isNode($value)
    {
        return is_string($value) && preg_match(self::NODE_PATTERN, $value) === 1;
    }

    public static function isKey($value)
    {
        return is_string($value) && preg_match(self::KEY_PATTERN, $value) === 1;
    }

    /** URL-safe opaque token, used for draft preview links. */
    public static function token($bytes = 32)
    {
        $bytes = max(16, min(64, (int) $bytes));
        return bin2hex(random_bytes($bytes));
    }

    /** Stable hash of a token for storage; the token itself is never stored. */
    public static function fingerprint($token)
    {
        return hash('sha256', (string) $token);
    }
}
