import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiFetch, ApiRequestError } from '../../lib/api';
import { getToken } from '../../lib/auth';
import { toolsApiPath } from '../../lib/tools-runtime';
import { usePageMeta } from '../../lib/usePageMeta';
import { CatalogErrorBanner, CatalogLoadingBanner } from '../../components/CatalogStateBanner';
import { EmptyState, Feedback, Pill, statusTone, useAction } from '../../components/platform/ui';
import { formatDate, titleCase, type LogoCatalogue, type LogoConcept, type LogoProject } from '../../lib/platform-api';

/**
 * Logo Maker.
 *
 * The marks are generated by the platform's own vector engine — real, standards-compliant SVG, and a
 * PNG rendered from that same SVG — so nothing here depends on an external design service. Editing a
 * concept appends a revision and the earlier version stays restorable; the assisted palette
 * suggestion is the one AI-assisted part and it fails closed: without a configured model credential
 * it says exactly which setting an operator must provide, and it never changes a concept by itself.
 */
export default function LogoMakerPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const token = getToken();
  if (projectId) return <ProjectView projectId={projectId} token={token} />;
  return <ProjectList token={token} />;
}

function svgDataUrl(svg: string): string {
  // Rendered through an <img>, never as inline markup: an SVG string cannot execute script in this
  // context, and the server has already escaped every author-supplied value.
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function ProjectList({ token }: { token: string | null }) {
  usePageMeta('Logo Maker', 'Generate a real vector logo, edit it, and export SVG or PNG.', {
    canonical: '/marketing/logo-maker',
    jsonLd: { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'CloudHost247 Logo Maker', applicationCategory: 'DesignApplication' },
  });
  const [catalogue, setCatalogue] = useState<LogoCatalogue | null>(null);
  const [projects, setProjects] = useState<LogoProject[]>([]);
  const [form, setForm] = useState({ companyName: '', tagline: '', industry: '', style: 'modern', paletteSlug: '', fontSlug: '' });
  const [error, setError] = useState('');
  const action = useAction();

  const load = useCallback(() => {
    apiFetch<LogoCatalogue>('/api/v1/logo-maker/catalogue')
      .then((response) => {
        setCatalogue(response);
        setForm((current) => ({
          ...current,
          style: current.style || response.styles[0] || 'modern',
          paletteSlug: current.paletteSlug || response.palettes[0]?.slug || '',
          fontSlug: current.fontSlug || response.fonts[0]?.slug || '',
        }));
      })
      .catch((err: Error) => setError(err.message));
    if (token) {
      apiFetch<{ projects: LogoProject[] }>('/api/v1/logo-maker/projects')
        .then((response) => setProjects(response.projects))
        .catch(() => setProjects([]));
    }
  }, [token]);

  useEffect(() => load(), [load]);

  return (
    <div className="ch247-page">
      <h1>Logo Maker</h1>
      <p className="ch247-page__hint">
        Describe the brand, choose a direction, and the platform generates editable logo concepts — vector, scalable,
        and exportable as SVG or PNG at the size you need.
      </p>
      <Feedback error={action.error} message={action.message} />
      {error ? <CatalogErrorBanner message={error} /> : null}

      {!token ? (
        <div className="ch247-state-banner">
          <p>Sign in to create a logo project and keep your concepts, revisions and exports together.</p>
          <Link className="ch247-button" to="/login?next=/marketing/logo-maker">
            Sign in
          </Link>
        </div>
      ) : null}

      {catalogue === null ? (
        <CatalogLoadingBanner />
      ) : (
        <section className="ch247-card">
          <h2>New logo project</h2>
          <div className="ch247-form">
            <label className="ch247-field">
              <span className="ch247-field-label">Brand or company name</span>
              <input value={form.companyName} maxLength={160} onChange={(event) => setForm({ ...form, companyName: event.target.value })} />
            </label>
            <label className="ch247-field">
              <span className="ch247-field-label">Tagline (optional)</span>
              <input value={form.tagline} maxLength={200} onChange={(event) => setForm({ ...form, tagline: event.target.value })} />
            </label>
            <label className="ch247-field">
              <span className="ch247-field-label">Industry (optional)</span>
              <input value={form.industry} maxLength={80} onChange={(event) => setForm({ ...form, industry: event.target.value })} />
            </label>
            <label className="ch247-field">
              <span className="ch247-field-label">Style</span>
              <select value={form.style} onChange={(event) => setForm({ ...form, style: event.target.value })}>
                {catalogue.styles.map((style) => (
                  <option key={style} value={style}>
                    {titleCase(style)}
                  </option>
                ))}
              </select>
            </label>
            <label className="ch247-field">
              <span className="ch247-field-label">Palette</span>
              <select value={form.paletteSlug} onChange={(event) => setForm({ ...form, paletteSlug: event.target.value })}>
                {catalogue.palettes.map((palette) => (
                  <option key={palette.slug} value={palette.slug}>
                    {palette.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="ch247-field">
              <span className="ch247-field-label">Typeface</span>
              <select value={form.fontSlug} onChange={(event) => setForm({ ...form, fontSlug: event.target.value })}>
                {catalogue.fonts.map((font) => (
                  <option key={font.slug} value={font.slug}>
                    {font.name}
                  </option>
                ))}
              </select>
            </label>
            <button
              type="button"
              className="ch247-button"
              disabled={!token || action.busy || form.companyName.trim().length < 1}
              onClick={() =>
                void action.run(async () => {
                  const response = await apiFetch<{ project: LogoProject }>('/api/v1/logo-maker/projects', {
                    method: 'POST',
                    body: JSON.stringify({
                      companyName: form.companyName.trim(),
                      tagline: form.tagline.trim() || null,
                      industry: form.industry.trim() || null,
                      style: form.style,
                      paletteSlug: form.paletteSlug,
                      fontSlug: form.fontSlug,
                    }),
                  });
                  setForm({ ...form, companyName: '', tagline: '', industry: '' });
                  load();
                  window.location.assign(`/marketing/logo-maker/${response.project.id}`);
                })
              }
            >
              {action.busy ? 'Creating…' : 'Create project'}
            </button>
          </div>
        </section>
      )}

      {token ? (
        <section className="ch247-card">
          <h2>Your logo projects</h2>
          {projects.length === 0 ? (
            <EmptyState>No logo projects yet.</EmptyState>
          ) : (
            <div className="ch247-table-scroll">
              <table className="ch247-table">
                <thead>
                  <tr>
                    <th scope="col">Brand</th>
                    <th scope="col">Style</th>
                    <th scope="col">Selected concept</th>
                    <th scope="col">Created</th>
                    <th scope="col" />
                  </tr>
                </thead>
                <tbody>
                  {projects.map((project) => (
                    <tr key={project.id}>
                      <td>{project.company_name}</td>
                      <td>{titleCase(project.style)}</td>
                      <td>{project.selected_concept_id ? 'Yes' : 'Not chosen yet'}</td>
                      <td>{formatDate(project.created_at)}</td>
                      <td>
                        <Link to={`/marketing/logo-maker/${project.id}`}>Open</Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>
      ) : null}
    </div>
  );
}

function ProjectView({ projectId, token }: { projectId: string; token: string | null }) {
  usePageMeta('Logo project', 'Generate, edit and export logo concepts.', { noIndex: true });
  const [catalogue, setCatalogue] = useState<LogoCatalogue | null>(null);
  const [project, setProject] = useState<LogoProject | null>(null);
  const [concepts, setConcepts] = useState<LogoConcept[]>([]);
  const [revisions, setRevisions] = useState<Record<string, Array<{ revision: number; note: string | null; created_at: string }>>>({});
  const [editing, setEditing] = useState<{ id: string; patch: Record<string, string> } | null>(null);
  const [suggestion, setSuggestion] = useState<{ paletteSlug: string; style: string; rationale: string } | null>(null);
  const [brief, setBrief] = useState('');
  const [error, setError] = useState('');
  const action = useAction();

  const load = useCallback(() => {
    if (!token) return;
    apiFetch<{ project: LogoProject; concepts: LogoConcept[] }>(`/api/v1/logo-maker/projects/${projectId}`)
      .then((response) => {
        setProject(response.project);
        setConcepts(response.concepts);
      })
      .catch((err: Error) => setError(err.message));
    apiFetch<LogoCatalogue>('/api/v1/logo-maker/catalogue')
      .then(setCatalogue)
      .catch(() => setCatalogue(null));
  }, [projectId, token]);

  useEffect(() => load(), [load]);

  if (!token) {
    return (
      <div className="ch247-page">
        <h1>Logo project</h1>
        <div className="ch247-state-banner">
          <p>Logo projects are private to your account.</p>
          <Link className="ch247-button" to={`/login?next=/marketing/logo-maker/${projectId}`}>
            Sign in
          </Link>
        </div>
      </div>
    );
  }
  if (error) return <CatalogErrorBanner message={error} />;
  if (!project) return <CatalogLoadingBanner label="Loading your logo project…" />;

  return (
    <div className="ch247-page ch247-page--wide">
      <p className="ch247-page__hint">
        <Link to="/marketing/logo-maker">← All logo projects</Link>
      </p>
      <h1>
        {project.company_name} <Pill tone={statusTone(project.status)}>{titleCase(project.status)}</Pill>
      </h1>
      <p className="ch247-page__hint">
        {titleCase(project.style)} · {project.palette_slug} · {project.font_slug}
        {project.tagline ? ` · “${project.tagline}”` : ''}
      </p>
      <Feedback error={action.error} message={action.message} />

      <div className="ch247-inline-actions">
        <button
          type="button"
          className="ch247-button"
          disabled={action.busy}
          onClick={() =>
            void action.run(async () => {
              const response = await apiFetch<{ concepts: LogoConcept[] }>(`/api/v1/logo-maker/projects/${project.id}/concepts`, { method: 'POST' });
              setConcepts(response.concepts);
              return `${response.concepts.length} concept${response.concepts.length === 1 ? '' : 's'} ready.`;
            })
          }
        >
          {concepts.length ? 'Regenerate concepts' : 'Generate concepts'}
        </button>
        <button
          type="button"
          className="ch247-button ch247-button--ghost"
          disabled={action.busy || brief.trim().length < 20}
          onClick={() =>
            void action.run(async () => {
              try {
                const response = await apiFetch<{ paletteSlug: string; style: string; rationale: string }>(
                  `/api/v1/logo-maker/projects/${project.id}/suggest`,
                  { method: 'POST', body: JSON.stringify({ brief: brief.trim() }) }
                );
                setSuggestion(response);
                return 'Suggestion received — nothing has been changed. Apply it if you agree.';
              } catch (err) {
                if (err instanceof ApiRequestError && err.status === 403) {
                  setSuggestion(null);
                  return err.message;
                }
                throw err;
              }
            })
          }
        >
          Suggest a palette
        </button>
      </div>

      <section className="ch247-card">
        <h2>Assisted suggestion</h2>
        <label className="ch247-field">
          <span className="ch247-field-label">Describe the brand in a sentence or two (at least 20 characters)</span>
          <textarea rows={2} maxLength={1500} value={brief} onChange={(event) => setBrief(event.target.value)} />
        </label>
        {suggestion ? (
          <div className="ch247-note">
            <p>
              Suggested palette <strong>{suggestion.paletteSlug}</strong>, style <strong>{titleCase(suggestion.style)}</strong>
              {suggestion.rationale ? ` — ${suggestion.rationale}` : ''}
            </p>
            <button
              type="button"
              className="ch247-button ch247-button--small"
              disabled={action.busy}
              onClick={() =>
                void action.run(async () => {
                  await apiFetch(`/api/v1/logo-maker/projects/${project.id}`, {
                    method: 'PATCH',
                    body: JSON.stringify({ paletteSlug: suggestion.paletteSlug, style: suggestion.style }),
                  });
                  setSuggestion(null);
                  load();
                  return 'Project updated. Regenerate the concepts to see the new direction.';
                })
              }
            >
              Apply suggestion
            </button>
          </div>
        ) : (
          <p className="ch247-page__hint">
            The suggestion needs a configured model provider; without one the platform says so instead of guessing.
          </p>
        )}
      </section>

      {concepts.length === 0 ? (
        <EmptyState>No concepts yet — generate them from this project.</EmptyState>
      ) : (
        <div className="ch247-logo-gallery">
          {concepts.map((concept) => (
            <article key={concept.id} className={`ch247-logo-card${concept.is_selected ? ' is-selected' : ''}`}>
              <img className="ch247-logo-preview" src={svgDataUrl(concept.svg)} alt={`Logo concept ${concept.variant} for ${project.company_name}`} />
              <div className="ch247-logo-card__meta">
                <span>
                  Variant {concept.variant} · {titleCase(concept.layout)} · {titleCase(concept.mark_style)}
                </span>
                {concept.is_selected ? <Pill tone="ok">Selected</Pill> : null}
              </div>
              <div className="ch247-inline-actions">
                <button
                  type="button"
                  className="ch247-button ch247-button--ghost ch247-button--small"
                  disabled={action.busy || concept.is_selected}
                  onClick={() =>
                    void action.run(async () => {
                      await apiFetch(`/api/v1/logo-maker/projects/${project.id}/concepts/${concept.id}/select`, { method: 'POST' });
                      load();
                      return `Concept ${concept.variant} is now your chosen mark.`;
                    })
                  }
                >
                  Use this
                </button>
                <button
                  type="button"
                  className="ch247-button ch247-button--ghost ch247-button--small"
                  onClick={() =>
                    setEditing(
                      editing?.id === concept.id
                        ? null
                        : {
                            id: concept.id,
                            patch: {
                              layout: concept.layout,
                              markStyle: concept.mark_style,
                              paletteSlug: concept.palette_slug,
                              fontSlug: concept.font_slug,
                            },
                          }
                    )
                  }
                >
                  {editing?.id === concept.id ? 'Close editor' : 'Edit'}
                </button>
                <button
                  type="button"
                  className="ch247-button ch247-button--ghost ch247-button--small"
                  disabled={action.busy}
                  onClick={() =>
                    void action.run(async () => {
                      const response = await apiFetch<{ revisions: Array<{ revision: number; note: string | null; created_at: string }> }>(
                        `/api/v1/logo-maker/projects/${project.id}/concepts/${concept.id}/revisions`
                      );
                      setRevisions({ ...revisions, [concept.id]: response.revisions });
                      return `${response.revisions.length} version(s) available.`;
                    })
                  }
                >
                  Versions
                </button>
              </div>

              {revisions[concept.id] ? (
                <ul className="ch247-plainlist">
                  {revisions[concept.id]!.map((revision) => (
                    <li key={revision.revision}>
                      v{revision.revision} · {formatDate(revision.created_at)}{' '}
                      <button
                        type="button"
                        className="ch247-button ch247-button--ghost ch247-button--small"
                        disabled={action.busy}
                        onClick={() =>
                          void action.run(async () => {
                            await apiFetch(`/api/v1/logo-maker/projects/${project.id}/concepts/${concept.id}/revisions/${revision.revision}/restore`, {
                              method: 'POST',
                            });
                            load();
                            return `Restored version ${revision.revision}.`;
                          })
                        }
                      >
                        Restore
                      </button>
                    </li>
                  ))}
                </ul>
              ) : null}

              {editing?.id === concept.id && catalogue ? (
                <div className="ch247-form">
                  <label className="ch247-field">
                    <span className="ch247-field-label">Layout</span>
                    <select value={editing.patch.layout} onChange={(event) => setEditing({ ...editing, patch: { ...editing.patch, layout: event.target.value } })}>
                      {catalogue.layouts.map((layout) => (
                        <option key={layout.slug} value={layout.slug}>
                          {layout.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="ch247-field">
                    <span className="ch247-field-label">Mark style</span>
                    <select value={editing.patch.markStyle} onChange={(event) => setEditing({ ...editing, patch: { ...editing.patch, markStyle: event.target.value } })}>
                      {catalogue.markStyles.map((mark) => (
                        <option key={mark.slug} value={mark.slug}>
                          {mark.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="ch247-field">
                    <span className="ch247-field-label">Palette</span>
                    <select
                      value={editing.patch.paletteSlug}
                      onChange={(event) => setEditing({ ...editing, patch: { ...editing.patch, paletteSlug: event.target.value } })}
                    >
                      {catalogue.palettes.map((palette) => (
                        <option key={palette.slug} value={palette.slug}>
                          {palette.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  <label className="ch247-field">
                    <span className="ch247-field-label">Typeface</span>
                    <select value={editing.patch.fontSlug} onChange={(event) => setEditing({ ...editing, patch: { ...editing.patch, fontSlug: event.target.value } })}>
                      {catalogue.fonts.map((font) => (
                        <option key={font.slug} value={font.slug}>
                          {font.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  <button
                    type="button"
                    className="ch247-button ch247-button--small"
                    disabled={action.busy}
                    onClick={() =>
                      void action.run(async () => {
                        await apiFetch(`/api/v1/logo-maker/projects/${project.id}/concepts/${concept.id}`, {
                          method: 'PATCH',
                          body: JSON.stringify(editing.patch),
                        });
                        setEditing(null);
                        load();
                        return 'Concept updated — the previous version is kept as a revision.';
                      })
                    }
                  >
                    Save changes
                  </button>
                </div>
              ) : null}

              <div className="ch247-inline-actions">
                {(['svg', 'png'] as const).map((format) => (
                  <button
                    key={format}
                    type="button"
                    className="ch247-button ch247-button--ghost ch247-button--small"
                    disabled={action.busy}
                    onClick={() =>
                      void action.run(async () => {
                        const response = await fetch(
                          toolsApiPath(`/api/v1/logo-maker/projects/${project.id}/concepts/${concept.id}/export`),
                          {
                            method: 'POST',
                            headers: {
                              'Content-Type': 'application/json',
                              ...(getToken() ? { Authorization: `Bearer ${getToken()}` } : {}),
                            },
                            body: JSON.stringify({ format, ...(format === 'png' ? { width: 1024, height: 1024, background: 'transparent' } : {}) }),
                          }
                        );
                        if (!response.ok) {
                          const body = (await response.json().catch(() => null)) as { message?: string } | null;
                          throw new Error(body?.message ?? `Export failed (HTTP ${response.status})`);
                        }
                        const blob = await response.blob();
                        const url = URL.createObjectURL(blob);
                        const link = document.createElement('a');
                        link.href = url;
                        link.download = `${project.company_name.replace(/[^A-Za-z0-9._-]/g, '_')}-concept-${concept.variant}.${format}`;
                        document.body.appendChild(link);
                        link.click();
                        link.remove();
                        URL.revokeObjectURL(url);
                        return `${format.toUpperCase()} downloaded.`;
                      })
                    }
                  >
                    Download {format.toUpperCase()}
                  </button>
                ))}
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}
