import { createHash,randomBytes,randomUUID } from 'node:crypto';
import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Env } from '../config/env';
import type { Queryable } from '../db/types';
import { getPool } from '../db/pool';
import { authenticate,type AuthenticatedRequestContext } from '../lib/require-auth';
import { requireRole } from '../lib/require-role';
import { NotFoundError,ValidationError } from '../lib/errors';
import { auditRequest } from '../lib/audit';
import { createTicket } from '../db/support-tickets';
import { createNotification } from '../services/notification-service';
import { decideSupportResponse,type EscalationReason } from '../services/ai-support-operator';

const id=z.string().uuid(); const email=z.string().trim().email().max(320);
const messageSchema=z.object({message:z.string().trim().min(1).max(10000)});
const hash=(token:string)=>createHash('sha256').update(token).digest('hex');
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ValidationError(result.error.issues.map(i=>i.message).join(', '));return result.data}
async function optionalAuth(request:FastifyRequest,env:Env,db:Queryable):Promise<AuthenticatedRequestContext|null>{if(!request.headers.authorization)return null;return authenticate(request,env,db)}
function visitorToken(request:FastifyRequest){return typeof request.headers['x-ai-conversation-token']==='string'?request.headers['x-ai-conversation-token']:''}
async function conversation(db:Queryable,request:FastifyRequest,env:Env,conversationId:string,staff=false){
 const auth=await optionalAuth(request,env,db); const result=await db.query<any>(`SELECT * FROM ai_support_conversations WHERE id=$1`,[parse(id,conversationId)]);const row=result.rows[0];if(!row)throw new NotFoundError('Conversation not found');
 const privileged=auth&&['staff','admin','super_admin'].includes(auth.role);
 if(!(staff&&privileged)&&row.user_id!==auth?.userId&&row.access_token_hash!==hash(visitorToken(request)))throw new NotFoundError('Conversation not found');
 return{row,auth};
}
async function addMessage(db:Queryable,conversationId:string,type:string,body:string,authorId:string|null=null,intent:string|null=null,confidence:number|null=null,sources:string[]=[]){
 const result=await db.query<any>(`INSERT INTO ai_support_messages(id,conversation_id,author_type,author_id,body,intent,confidence,knowledge_sources) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[randomUUID(),conversationId,type,authorId,body,intent,confidence,JSON.stringify(sources)]);await db.query(`UPDATE ai_support_conversations SET last_message_at=now(),updated_at=now() WHERE id=$1`,[conversationId]);return result.rows[0];
}
async function escalate(db:Queryable,row:any,reason:EscalationReason){
 const available=await db.query<{user_id:string}>(`SELECT p.user_id FROM support_agent_presence p JOIN users u ON u.id=p.user_id WHERE p.status='ONLINE' AND u.status='active' AND u.role IN ('staff','admin','super_admin') AND (SELECT count(*) FROM ai_support_conversations c WHERE c.assigned_agent_id=p.user_id AND c.status IN ('ASSIGNED','IN_PROGRESS'))<p.capacity ORDER BY p.updated_at DESC LIMIT 1`);
 const agent=available.rows[0]?.user_id??null;let ticketId:string|null=row.support_ticket_id;
 if(!agent&&row.user_id&&!ticketId){
   const first=await db.query<{body:string}>(`SELECT body FROM ai_support_messages WHERE conversation_id=$1 AND author_type='CUSTOMER' ORDER BY created_at LIMIT 1`,[row.id]);
   ticketId=randomUUID();await createTicket(db,{id:ticketId,userId:row.user_id,subject:`AI support escalation: ${reason.replaceAll('_',' ').toLowerCase()}`,priority:reason==='SECURITY_RELATED'?'high':'normal',firstMessage:{id:randomUUID(),authorId:row.user_id,authorRole:'customer',body:first.rows[0]?.body??'Please review the attached AI support conversation.'}});
 }
 const status=agent?'ASSIGNED':'WAITING_FOR_HUMAN';
 await db.query(`UPDATE ai_support_conversations SET status=$2,escalation_reason=$3,assigned_agent_id=$4,support_ticket_id=$5,updated_at=now() WHERE id=$1`,[row.id,status,reason,agent,ticketId]);
 const body=agent?'I’m transferring this conversation to CloudHost247 Support now. A support representative has been assigned.':'Our support team is currently unavailable. I have preserved this conversation in the support queue so the team can follow up. Please provide your name and email if they are not already attached.';
 await addMessage(db,row.id,'SYSTEM',body);
 if(agent)await createNotification(db,{userId:agent,type:'AI_SUPPORT_ASSIGNED',title:'AI support conversation assigned',message:`Escalation reason: ${reason}\nConversation: ${row.id}`,resourceType:'ai_support_conversation',resourceId:row.id});
 else {const admins=await db.query<{id:string}>(`SELECT id FROM users WHERE status='active' AND role IN ('admin','super_admin')`);for(const admin of admins.rows)await createNotification(db,{userId:admin.id,type:'AI_SUPPORT_ESCALATION',title:'New AI support escalation',message:`Reason: ${reason}\nConversation: ${row.id}`,resourceType:'ai_support_conversation',resourceId:row.id});}
 return{status,assignedAgentId:agent,ticketId,body};
}

export async function registerAiSupportRoutes(app:FastifyInstance,env:Env,override?:Queryable){const db=override??getPool(env);
 app.post('/api/v1/ai-support/conversations',async(request,reply)=>{const auth=await optionalAuth(request,env,db);const token=randomBytes(32).toString('base64url');const conversationId=randomUUID();await db.query(`INSERT INTO ai_support_conversations(id,user_id,access_token_hash) VALUES($1,$2,$3)`,[conversationId,auth?.userId??null,hash(token)]);await addMessage(db,conversationId,'AI','Hello! I’m the CloudHost247 AI Support assistant. I use verified CloudHost247 information. Ask a question, request a human, or subscribe to service updates.');await auditRequest(db,request,auth?.userId??null,{action:'AI_CONVERSATION_STARTED',resourceType:'ai_support_conversation',resourceId:conversationId});reply.code(201);return{conversationId,accessToken:token,status:'AI_ACTIVE'}});
 app.get<{Params:{id:string}}>('/api/v1/ai-support/conversations/:id',async(request)=>{const {row}=await conversation(db,request,env,request.params.id);const messages=await db.query(`SELECT id,author_type,body,created_at FROM ai_support_messages WHERE conversation_id=$1 ORDER BY created_at`,[row.id]);return{conversation:{...row,access_token_hash:undefined},messages:messages.rows}});
 app.post<{Params:{id:string}}>('/api/v1/ai-support/conversations/:id/messages',async(request)=>{const input=parse(messageSchema,request.body);const {row,auth}=await conversation(db,request,env,request.params.id);if(row.status!=='AI_ACTIVE'){if(['RESOLVED','CLOSED'].includes(row.status))throw new ValidationError('This conversation is closed');await addMessage(db,row.id,'CUSTOMER',input.message,auth?.userId??null);await db.query(`UPDATE ai_support_conversations SET status=CASE WHEN assigned_agent_id IS NULL THEN 'WAITING_FOR_HUMAN' ELSE 'IN_PROGRESS' END,updated_at=now() WHERE id=$1`,[row.id]);return{accepted:true,humanActive:true}}await addMessage(db,row.id,'CUSTOMER',input.message,auth?.userId??null);const decision=await decideSupportResponse(db,input.message);await auditRequest(db,request,auth?.userId??null,{action:decision.kind==='ESCALATE'?'AI_ESCALATION_TRIGGERED':'AI_RESPONSE_GENERATED',resourceType:'ai_support_conversation',resourceId:row.id,metadata:{intent:decision.intent,confidence:decision.confidence,reason:decision.reason}});if(decision.kind==='ESCALATE'){const transfer=await escalate(db,row,decision.reason!);return{decision,transfer}}const response=await addMessage(db,row.id,'AI',decision.body,null,decision.intent,decision.confidence,decision.sources);return{decision,response}});
 app.patch<{Params:{id:string}}>('/api/v1/ai-support/conversations/:id/contact',async(request)=>{const input=parse(z.object({name:z.string().trim().min(2).max(160),email}),request.body);const {row}=await conversation(db,request,env,request.params.id);await db.query(`UPDATE ai_support_conversations SET visitor_name=$2,visitor_email=$3,updated_at=now() WHERE id=$1`,[row.id,input.name,input.email.toLowerCase()]);return{saved:true}});
 app.post<{Params:{id:string}}>('/api/v1/ai-support/conversations/:id/newsletter',async(request)=>{const input=parse(z.object({name:z.string().trim().min(2).max(160),email}),request.body);const {row,auth}=await conversation(db,request,env,request.params.id);const result=await db.query<any>(`INSERT INTO newsletter_subscriptions(id,name,email,status,source) VALUES($1,$2,$3,'ACTIVE','ai_assistant') ON CONFLICT(lower(email)) DO UPDATE SET name=excluded.name,status='ACTIVE',updated_at=now() RETURNING id,status`,[randomUUID(),input.name,input.email.toLowerCase()]);await auditRequest(db,request,auth?.userId??null,{action:'NEWSLETTER_SUBSCRIPTION_COMPLETED',resourceType:'newsletter_subscription',resourceId:result.rows[0].id,metadata:{source:'ai_assistant'}});return{subscribed:true,status:result.rows[0].status}});
 app.get('/api/v1/ai-support/availability',async()=>{const online=await db.query<{count:string}>(`SELECT count(*)::text count FROM support_agent_presence p JOIN users u ON u.id=p.user_id WHERE p.status='ONLINE' AND u.status='active'`);return{status:Number(online.rows[0]?.count??0)>0?'ONLINE':'OFFLINE'}});
 app.get('/api/v1/admin/ai-support/conversations',async(request)=>{await requireRole(request,env,db,['staff','admin','super_admin']);const q=request.query as {status?:string;search?:string};const params:any[]=[];let where='WHERE 1=1';if(q.status){params.push(q.status);where+=` AND c.status=$${params.length}`}if(q.search){params.push(`%${q.search}%`);where+=` AND (c.visitor_name ILIKE $${params.length} OR c.visitor_email ILIKE $${params.length})`}const rows=await db.query(`SELECT c.*,u.email customer_account_email,a.email assigned_agent_email FROM ai_support_conversations c LEFT JOIN users u ON u.id=c.user_id LEFT JOIN users a ON a.id=c.assigned_agent_id ${where} ORDER BY c.updated_at DESC LIMIT 200`,params);return{conversations:rows.rows}});
 app.get<{Params:{id:string}}>('/api/v1/admin/ai-support/conversations/:id',async(request)=>{await requireRole(request,env,db,['staff','admin','super_admin']);const result=await db.query<any>(`SELECT * FROM ai_support_conversations WHERE id=$1`,[parse(id,request.params.id)]);if(!result.rows[0])throw new NotFoundError('Conversation not found');const messages=await db.query(`SELECT * FROM ai_support_messages WHERE conversation_id=$1 ORDER BY created_at`,[request.params.id]);return{conversation:result.rows[0],messages:messages.rows}});
 app.post<{Params:{id:string}}>('/api/v1/admin/ai-support/conversations/:id/reply',async(request)=>{const auth=await requireRole(request,env,db,['staff','admin','super_admin']);const input=parse(messageSchema,request.body);const found=await db.query<any>(`UPDATE ai_support_conversations SET assigned_agent_id=COALESCE(assigned_agent_id,$2),status='IN_PROGRESS',updated_at=now() WHERE id=$1 AND status NOT IN ('CLOSED','RESOLVED') RETURNING *`,[parse(id,request.params.id),auth.userId]);if(!found.rows[0])throw new NotFoundError('Conversation not found');return{message:await addMessage(db,request.params.id,'AGENT',input.message,auth.userId)}});
 app.patch<{Params:{id:string}}>('/api/v1/admin/ai-support/conversations/:id',async(request)=>{const auth=await requireRole(request,env,db,['staff','admin','super_admin']);const input=parse(z.object({status:z.enum(['AI_ACTIVE','WAITING_FOR_HUMAN','ASSIGNED','IN_PROGRESS','WAITING_FOR_CUSTOMER','RESOLVED','CLOSED']).optional(),assignedAgentId:z.string().uuid().nullable().optional(),priority:z.enum(['low','normal','high']).optional()}),request.body);const result=await db.query<any>(`UPDATE ai_support_conversations SET status=COALESCE($2,status),assigned_agent_id=CASE WHEN $3::boolean THEN $4 ELSE assigned_agent_id END,priority=COALESCE($5,priority),resolved_at=CASE WHEN $2 IN ('RESOLVED','CLOSED') THEN now() ELSE NULL END,updated_at=now() WHERE id=$1 RETURNING *`,[parse(id,request.params.id),input.status??null,input.assignedAgentId!==undefined,input.assignedAgentId??null,input.priority??null]);if(!result.rows[0])throw new NotFoundError('Conversation not found');await auditRequest(db,request,auth.userId,{action:input.status==='AI_ACTIVE'?'AI_HANDOFF_RETURNED':'AI_CONVERSATION_UPDATED',resourceType:'ai_support_conversation',resourceId:request.params.id,metadata:input});return{conversation:result.rows[0]}});
 app.put('/api/v1/admin/ai-support/presence',async(request)=>{const auth=await requireRole(request,env,db,['staff','admin','super_admin']);const input=parse(z.object({status:z.enum(['ONLINE','BUSY','OFFLINE']),capacity:z.number().int().min(1).max(20).optional()}),request.body);await db.query(`INSERT INTO support_agent_presence(user_id,status,capacity) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET status=excluded.status,capacity=excluded.capacity,updated_at=now()`,[auth.userId,input.status,input.capacity??3]);return{status:input.status}});
 app.get('/api/v1/admin/ai-support/overview',async(request)=>{await requireRole(request,env,db,['staff','admin','super_admin']);const counts=await db.query<{status:string;count:string}>(`SELECT status,count(*)::text count FROM ai_support_conversations GROUP BY status`);const news=await db.query<{count:string}>(`SELECT count(*)::text count FROM newsletter_subscriptions WHERE status='ACTIVE'`);return{counts:Object.fromEntries(counts.rows.map(r=>[r.status,Number(r.count)])),newsletterSubscriptions:Number(news.rows[0]?.count??0)}});
 app.get('/api/v1/admin/newsletter-subscriptions',async(request)=>{await requireRole(request,env,db,['admin','super_admin']);const rows=await db.query(`SELECT id,name,email,status,source,created_at,updated_at FROM newsletter_subscriptions ORDER BY created_at DESC LIMIT 500`);return{subscriptions:rows.rows}});
}
