-- Migration: 0077_create_logo_maker.sql
-- Purpose: CloudHost247 Logo Maker — design projects, generated concepts, editing revisions and
-- exports.
--
-- How concepts are produced (the honest part):
--   * The NATIVE engine (`vector`) composes real SVG from the platform's own layout registry,
--     typography presets and palettes (src/logo-maker/vector-engine.ts). It is deterministic
--     vector generation — it is labelled as such everywhere it is shown, and it needs no external
--     service.
--   * An OPTIONAL AI engine can suggest palettes/lockups via the same AI provider abstraction the
--     AI Website Builder uses. Without configured credentials the request fails closed with
--     CONFIGURATION_REQUIRED; the platform never presents template output as model output or the
--     reverse.
--
-- The SVG is stored as the *source of truth* for a concept — it is generated by this platform from
-- validated inputs (company name, palette, font preset, layout), and every variable that produced
-- it is stored alongside it, so a concept can always be re-derived and re-edited. User text is
-- XML-escaped before it enters the document, so a company name can never inject markup into an
-- exported SVG.

CREATE TABLE IF NOT EXISTS logo_projects (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  company_name varchar(160) NOT NULL,
  tagline varchar(200) NULL,
  industry varchar(80) NULL,
  style varchar(40) NOT NULL DEFAULT 'modern',
  -- Selected palette/typography presets by slug from the registry (src/logo-maker/catalog.ts).
  palette_slug varchar(40) NOT NULL DEFAULT 'ch247-blue',
  font_slug varchar(40) NOT NULL DEFAULT 'geometric-sans',
  brand_keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text NULL,
  status varchar(16) NOT NULL DEFAULT 'draft',
  selected_concept_id uuid NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT logo_projects_style_check CHECK (
    style IN ('modern', 'classic', 'minimal', 'bold', 'playful', 'luxury', 'tech', 'organic')
  ),
  CONSTRAINT logo_projects_status_check CHECK (status IN ('draft', 'generated', 'finalized', 'archived'))
);

CREATE INDEX IF NOT EXISTS logo_projects_user_idx ON logo_projects (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS logo_concepts (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES logo_projects (id) ON DELETE CASCADE,
  variant integer NOT NULL,
  engine varchar(24) NOT NULL DEFAULT 'vector',
  layout varchar(40) NOT NULL,
  mark_style varchar(40) NOT NULL,
  palette_slug varchar(40) NOT NULL,
  font_slug varchar(40) NOT NULL,
  svg text NOT NULL,
  is_selected boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT logo_concepts_engine_check CHECK (engine IN ('vector', 'ai')),
  CONSTRAINT logo_concepts_layout_check CHECK (
    layout IN ('mark_left', 'mark_above', 'mark_only', 'monogram_badge', 'emblem_round')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS logo_concepts_variant_unique_idx ON logo_concepts (project_id, variant);
CREATE INDEX IF NOT EXISTS logo_concepts_project_idx ON logo_concepts (project_id, variant);
-- One selected concept per project, enforced by the database.
CREATE UNIQUE INDEX IF NOT EXISTS logo_concepts_selected_unique_idx ON logo_concepts (project_id) WHERE is_selected;

-- Every edit is a new revision (append-only), so "undo" is a real restore and nothing a customer
-- made is ever silently destroyed.
CREATE TABLE IF NOT EXISTS logo_concept_revisions (
  id uuid PRIMARY KEY,
  concept_id uuid NOT NULL REFERENCES logo_concepts (id) ON DELETE CASCADE,
  revision integer NOT NULL,
  svg text NOT NULL,
  layout varchar(40) NOT NULL,
  mark_style varchar(40) NOT NULL,
  palette_slug varchar(40) NOT NULL,
  font_slug varchar(40) NOT NULL,
  note varchar(200) NULL,
  created_by uuid NULL REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS logo_concept_revisions_unique_idx ON logo_concept_revisions (concept_id, revision);

-- Exports. SVG is stored as text; PNG is rasterized server-side into `data` (bytea), the same
-- in-database blob strategy used for profile images and builder media.
CREATE TABLE IF NOT EXISTS logo_exports (
  id uuid PRIMARY KEY,
  concept_id uuid NOT NULL REFERENCES logo_concepts (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  format varchar(8) NOT NULL,
  width_px integer NULL,
  height_px integer NULL,
  background varchar(16) NOT NULL DEFAULT 'transparent',
  svg text NULL,
  data bytea NULL,
  byte_size integer NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT logo_exports_format_check CHECK (format IN ('svg', 'png')),
  CONSTRAINT logo_exports_payload_check CHECK (
    (format = 'svg' AND svg IS NOT NULL) OR (format = 'png' AND data IS NOT NULL)
  ),
  CONSTRAINT logo_exports_size_check CHECK (width_px IS NULL OR (width_px BETWEEN 64 AND 4096)),
  CONSTRAINT logo_exports_height_check CHECK (height_px IS NULL OR (height_px BETWEEN 64 AND 4096))
);

CREATE INDEX IF NOT EXISTS logo_exports_user_idx ON logo_exports (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS logo_exports_concept_idx ON logo_exports (concept_id);

-- AI usage metering, kept separate from the website-builder ledger so the free allowance of one
-- product can never silently consume the other's.
CREATE TABLE IF NOT EXISTS logo_ai_generations (
  id uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES logo_projects (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  engine varchar(24) NOT NULL,
  model varchar(120) NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  request jsonb NOT NULL,
  response jsonb NULL,
  error_code varchar(64) NULL,
  error_message text NULL,
  provider_reference varchar(160) NULL,
  duration_ms integer NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz NULL,
  CONSTRAINT logo_ai_generations_status_check CHECK (status IN ('pending', 'succeeded', 'failed', 'rejected'))
);

CREATE INDEX IF NOT EXISTS logo_ai_generations_user_idx ON logo_ai_generations (user_id, created_at DESC);
