<?php
namespace CloudHost247\Ovh\Services;use CloudHost247\Foundation\Support\AuditLogger;use CloudHost247\Foundation\Support\Logger;use WHMCS\Database\Capsule;use RuntimeException;
final class ServiceManager
{
 private$r;function __construct(ConnectionResolver$r){$this->r=$r;}private function binding($id){$s=Capsule::table('mod_cloudhost247_ovh_services')->where('whmcs_service_id',(int)$id)->first();if(!$s||!$s->remote_service_name)throw new RuntimeException('Service is not linked to a verified OVH service name.');return$s;}private function base($s){return$s->family==='vps'?'/vps/'.rawurlencode($s->remote_service_name):'/dedicated/server/'.rawurlencode($s->remote_service_name);}function details($id){$s=$this->binding($id);return$this->bounded($this->r->endpoint($s->endpoint_id)->get($this->base($s)));}function status($id){$s=$this->binding($id);$c=$this->r->endpoint($s->endpoint_id);return$this->bounded($s->family==='vps'?$c->get($this->base($s).'/status'):$c->get($this->base($s)));}function ips($id){$s=$this->binding($id);$raw=$this->r->endpoint($s->endpoint_id)->get($s->family==='vps'?$this->base($s).'/ips':'/ip?routedTo.serviceName='.rawurlencode($s->remote_service_name));return array('addresses'=>(new \CloudHost247\Ovh\Normalization\IpNormalizer())->normalize($raw));}
 function reboot($id){$s=$this->binding($id);return$this->mutate($s,'reboot',$this->base($s).'/reboot');}function power($id,$on){$s=$this->binding($id);if($s->family!=='vps')throw new RuntimeException('Power start/stop is only exposed for VPS mappings.');return$this->mutate($s,$on?'start':'stop',$this->base($s).($on?'/start':'/stop'));}function terminate($id,$confirmed=false){if(!$confirmed)throw new RuntimeException('Explicit termination confirmation is required.');$s=$this->binding($id);$result=$this->mutate($s,'terminate',$this->base($s).'/terminate');Capsule::table('mod_cloudhost247_ovh_services')->where('id',$s->id)->update(array('status'=>'terminating','updated_at'=>date('Y-m-d H:i:s')));return$result;}
 private function mutate($s,$action,$path,$method='POST',array $body=array()){$key=hash('sha256','service-action|'.$s->whmcs_service_id.'|'.$action.'|'.gmdate('YmdHi').($body?'|'.hash('sha256',json_encode($body)):''));$existing=Capsule::table('mod_cloudhost247_ovh_operations')->where('idempotency_key',$key)->first();if($existing)throw new RuntimeException('An identical service action is already recorded for this minute; its result must be checked before another attempt.');$now=date('Y-m-d H:i:s');$id=Capsule::table('mod_cloudhost247_ovh_operations')->insertGetId(array('whmcs_service_id'=>$s->whmcs_service_id,'operation'=>$action,'idempotency_key'=>$key,'status'=>'running','request_json'=>json_encode(array('intent'=>$action,'method'=>$method)),'attempts'=>1,'created_at'=>$now,'updated_at'=>$now));try{$c=$this->r->endpoint($s->endpoint_id);$result=$method==='PUT'?$c->put($path,$body):($method==='DELETE'?$c->delete($path):$c->post($path,$body));Capsule::table('mod_cloudhost247_ovh_operations')->where('id',$id)->update(array('status'=>'completed','response_json'=>json_encode($this->bounded($result)),'updated_at'=>date('Y-m-d H:i:s')));AuditLogger::record('cloudhost247_ovh','service.'.$action,'service',$s->whmcs_service_id,array('status'=>$s->status),array('operation'=>'completed'));return$result;}catch(\Throwable$e){Capsule::table('mod_cloudhost247_ovh_operations')->where('id',$id)->update(array('status'=>'reconciliation_required','error_message'=>substr(strip_tags($e->getMessage()),0,1000),'updated_at'=>date('Y-m-d H:i:s')));AuditLogger::record('cloudhost247_ovh','service.'.$action,'service',$s->whmcs_service_id,array(),array(),'failed',$e->getMessage());throw new RuntimeException('The provider result is uncertain. Reconciliation is required before any retry.');}}
 /** Linked OVH identity for a WHMCS service: family (vps|dedicated|eco) and remote service name. */
 function identity($id){$s=$this->binding($id);return array('family'=>(string)$s->family,'service_name'=>(string)$s->remote_service_name,'endpoint_id'=>(int)$s->endpoint_id);}
 /** Read-only GET beneath the linked service's own base path; the suffix is validated, never taken verbatim from a request. */
 function readSub($id,$suffix){$suffix=$this->safeSub($suffix,'service');$s=$this->binding($id);return$this->bounded($this->r->endpoint($s->endpoint_id)->get($this->base($s).$suffix));}
 /** Ledgered, idempotent, non-retried mutation beneath the linked service's base path. Caller owns validation and confirmation. */
 function performSub($id,$action,$method,$suffix,array $body=array()){if(!in_array($method,array('POST','PUT','DELETE'),true))throw new RuntimeException('Unsupported mutation method.');$suffix=$this->safeSub($suffix,'service');$s=$this->binding($id);return$this->mutate($s,$action,$this->base($s).$suffix,$method,$body);}
 /**
  * Address ownership: the only addresses a request may name are the ones OVH
  * itself reports for the linked service. A free-form IP would let an
  * administrator (or a forged request) address another customer's block, so an
  * address is verified against the provider's own list before any call is made.
  */
 function boundAddress($id,$ip){$ip=trim((string)$ip);if(!filter_var($ip,FILTER_VALIDATE_IP))throw new RuntimeException('A valid IP address is required.');$owned=array();foreach($this->ips($id)['addresses']as$address)$owned[]=$address['address'];if(!in_array($ip,$owned,true))throw new RuntimeException('The address is not one OVH reports for this service.');return array($this->binding($id),$ip);}
 /** Read-only GET beneath an address the service owns. Suffix is validated, never taken verbatim. */
 function ipSub($id,$ip,$suffix){$suffix=$this->safeSub($suffix,'address');list($s,$address)=$this->boundAddress($id,$ip);return$this->bounded($this->r->endpoint($s->endpoint_id)->get('/ip/'.rawurlencode($address).$suffix));}
 /** Ledgered, idempotent, non-retried mutation beneath an address the service owns. */
 function performIpSub($id,$ip,$action,$method,$suffix,array $body=array()){if(!in_array($method,array('POST','PUT','DELETE'),true))throw new RuntimeException('Unsupported mutation method.');$suffix=$this->safeSub($suffix,'address');list($s,$address)=$this->boundAddress($id,$ip);return$this->mutate($s,$action,'/ip/'.rawurlencode($address).$suffix,$method,$body);}
 /**
  * A sub-path is allowlisted and can never traverse: an address-scoped path
  * carries a dotted IPv4 (the address on the firewall), so dots are allowed,
  * but a `..` segment is refused outright.
  */
 private function safeSub($suffix,$context){$s=(string)$suffix;if(strpos($s,'..')!==false||!preg_match('#^(/[A-Za-z0-9._/-]+)?(\\?[A-Za-z0-9_=.-]+)?$#',$s))throw new RuntimeException('Unsafe '.$context.' sub-path.');return $s;}
 private function bounded($value){if(is_array($value))return array_slice($value,0,200,true);return$value;}
}
