<?php
namespace CloudHost247\Ovh\Services;use CloudHost247\Foundation\Support\AuditLogger;use CloudHost247\Foundation\Support\Logger;use WHMCS\Database\Capsule;use RuntimeException;
final class ServiceManager
{
 private$r;function __construct(ConnectionResolver$r){$this->r=$r;}private function binding($id){$s=Capsule::table('mod_cloudhost247_ovh_services')->where('whmcs_service_id',(int)$id)->first();if(!$s||!$s->remote_service_name)throw new RuntimeException('Service is not linked to a verified OVH service name.');return$s;}private function base($s){return$s->family==='vps'?'/vps/'.rawurlencode($s->remote_service_name):'/dedicated/server/'.rawurlencode($s->remote_service_name);}function details($id){$s=$this->binding($id);return$this->bounded($this->r->endpoint($s->endpoint_id)->get($this->base($s)));}function status($id){$s=$this->binding($id);$c=$this->r->endpoint($s->endpoint_id);return$this->bounded($s->family==='vps'?$c->get($this->base($s).'/status'):$c->get($this->base($s)));}function ips($id){$s=$this->binding($id);$raw=$this->r->endpoint($s->endpoint_id)->get($s->family==='vps'?$this->base($s).'/ips':'/ip?routedTo.serviceName='.rawurlencode($s->remote_service_name));return array('addresses'=>(new \CloudHost247\Ovh\Normalization\IpNormalizer())->normalize($raw));}
 function reboot($id){$s=$this->binding($id);return$this->mutate($s,'reboot',$this->base($s).'/reboot');}function power($id,$on){$s=$this->binding($id);if($s->family!=='vps')throw new RuntimeException('Power start/stop is only exposed for VPS mappings.');return$this->mutate($s,$on?'start':'stop',$this->base($s).($on?'/start':'/stop'));}function terminate($id,$confirmed=false){if(!$confirmed)throw new RuntimeException('Explicit termination confirmation is required.');$s=$this->binding($id);$result=$this->mutate($s,'terminate',$this->base($s).'/terminate');Capsule::table('mod_cloudhost247_ovh_services')->where('id',$s->id)->update(array('status'=>'terminating','updated_at'=>date('Y-m-d H:i:s')));return$result;}
 private function mutate($s,$action,$path){$key=hash('sha256','service-action|'.$s->whmcs_service_id.'|'.$action.'|'.gmdate('YmdHi'));$existing=Capsule::table('mod_cloudhost247_ovh_operations')->where('idempotency_key',$key)->first();if($existing)throw new RuntimeException('An identical service action is already recorded for this minute; its result must be checked before another attempt.');$now=date('Y-m-d H:i:s');$id=Capsule::table('mod_cloudhost247_ovh_operations')->insertGetId(array('whmcs_service_id'=>$s->whmcs_service_id,'operation'=>$action,'idempotency_key'=>$key,'status'=>'running','request_json'=>json_encode(array('intent'=>$action)),'attempts'=>1,'created_at'=>$now,'updated_at'=>$now));try{$result=$this->r->endpoint($s->endpoint_id)->post($path);Capsule::table('mod_cloudhost247_ovh_operations')->where('id',$id)->update(array('status'=>'completed','response_json'=>json_encode($this->bounded($result)),'updated_at'=>date('Y-m-d H:i:s')));AuditLogger::record('cloudhost247_ovh','service.'.$action,'service',$s->whmcs_service_id,array('status'=>$s->status),array('operation'=>'completed'));return$result;}catch(\Throwable$e){Capsule::table('mod_cloudhost247_ovh_operations')->where('id',$id)->update(array('status'=>'reconciliation_required','error_message'=>substr(strip_tags($e->getMessage()),0,1000),'updated_at'=>date('Y-m-d H:i:s')));AuditLogger::record('cloudhost247_ovh','service.'.$action,'service',$s->whmcs_service_id,array(),array(),'failed',$e->getMessage());throw new RuntimeException('The provider result is uncertain. Reconciliation is required before any retry.');}}
 private function bounded($value){if(is_array($value))return array_slice($value,0,200,true);return$value;}
}
