import React, { useEffect, useState } from 'react';
import { adminApi, describeError } from '../lib/api.js';

export default function AdminCloudflarePage() {
  const [data, setData] = useState(null); const [services, setServices] = useState(null); const [form, setForm] = useState({ accountName: '', cloudflareAccountId: '', apiToken: '', apiBaseUrl: '', defaultZoneType: 'full', defaultSslMode: 'strict', defaultProxied: true }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { const [overview, list] = await Promise.all([adminApi.cloudflareOverview(), adminApi.cloudflareServices()]); setData(overview); setServices(list.services ?? []); };
  useEffect(() => { load().catch(e => setError(describeError(e))); }, []);
  const run = async (fn, msg) => { setBusy(true); setError(''); setNotice(''); try { await fn(); await load(); setNotice(msg); } catch(e) { setError(describeError(e)); } finally { setBusy(false); } };
  const create = (e) => { e.preventDefault(); run(() => adminApi.createCloudflareAccount(form), 'Cloudflare account added.'); };
  const test = (id) => run(() => adminApi.testCloudflareAccount(id), 'Cloudflare connection test completed.');
  return <div className="page"><div className="page-head"><div><h1>Cloudflare</h1><p className="muted">Manage provider accounts and monitor customer Cloudflare services. API tokens are never displayed after submission.</p></div></div>{error && <div className="alert alert-error" role="alert">{error}</div>}{notice && <div className="alert alert-success" role="status">{notice}</div>}
    {data?.stats && <div className="grid-4">{[['Services', data.stats.total_services], ['Active zones', data.stats.active_zones], ['Provisioning', data.stats.provisioning], ['API errors (24h)', data.stats.api_errors_24h]].map(([label,value]) => <div className="card stat" key={label}><span className="muted">{label}</span><strong>{value}</strong></div>)}</div>}
    <div className="grid-2"><section className="card"><h2>Provider accounts</h2>{data?.accounts?.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Status</th><th>Credential</th><th /></tr></thead><tbody>{data.accounts.map(a => <tr key={a.id}><td>{a.accountName || a.account_name}<div className="muted small">{a.cloudflareAccountId || a.cloudflare_account_id}</div></td><td>{a.status}</td><td>{a.credentialState || 'stored'}</td><td><button type="button" className="linklike" onClick={() => test(a.id)} disabled={busy}>Test</button></td></tr>)}</tbody></table></div> : <p className="muted">No Cloudflare accounts configured.</p>}<form className="nested-form" onSubmit={create}><h3>Add account</h3><div className="field"><label htmlFor="cf-name">Account name</label><input id="cf-name" value={form.accountName} onChange={e=>setForm({...form,accountName:e.target.value})} required /></div><div className="field"><label htmlFor="cf-id">Cloudflare account ID</label><input id="cf-id" value={form.cloudflareAccountId} onChange={e=>setForm({...form,cloudflareAccountId:e.target.value})} required /></div><div className="field"><label htmlFor="cf-token">API token</label><input id="cf-token" type="password" value={form.apiToken} onChange={e=>setForm({...form,apiToken:e.target.value})} required /></div><button className="btn btn-primary" disabled={busy}>Save account</button></form></section>
    <section className="card"><h2>Customer services</h2>{services === null ? <p className="muted">Loading…</p> : <div className="table-wrap"><table className="table"><thead><tr><th>Zone</th><th>Plan</th><th>Status</th><th>Activation</th><th>Last sync</th></tr></thead><tbody>{services.length ? services.map(s => <tr key={s.id}><td><strong>{s.zoneName}</strong><div className="muted small">{s.zoneId || 'not provisioned'}</div></td><td>{s.cloudflarePlan || '—'}</td><td>{s.status}</td><td>{s.activationStatus || '—'}</td><td>{s.lastSyncedAt ? new Date(s.lastSyncedAt).toLocaleString() : '—'}</td></tr>) : <tr><td colSpan="5" className="muted">No Cloudflare services.</td></tr>}</tbody></table></div>}</section></div>
  </div>;
}
