import React, { useEffect, useState } from 'react';
import { adminApi, describeError } from '../lib/api.js';

export default function AdminInfrastructurePage() {
  const [providers, setProviders] = useState(null); const [plans, setPlans] = useState(null); const [regions, setRegions] = useState(null);
  const [provider, setProvider] = useState({ name: '', providerType: '', adapter: '', apiBaseUrl: '', credentialEnvPrefix: '' });
  const [plan, setPlan] = useState({ name: '', priceCents: 0, spec: '{}' }); const [region, setRegion] = useState({ name: '', code: '', providerId: '' });
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { const [p, s, r] = await Promise.all([adminApi.providers(), adminApi.serverPlans(), adminApi.regions()]); setProviders(p.providers ?? []); setPlans(s.plans ?? []); setRegions(r.regions ?? []); };
  useEffect(() => { load().catch(e => setError(describeError(e))); }, []);
  const run = async (fn, msg) => { setBusy(true); setError(''); setNotice(''); try { await fn(); await load(); setNotice(msg); } catch(e) { setError(describeError(e)); } finally { setBusy(false); } };
  const submitProvider = (e) => { e.preventDefault(); run(() => adminApi.createProvider({ ...provider, type: provider.providerType || undefined }), 'Provider created disabled. Validate it before activation.'); };
  const submitPlan = (e) => { e.preventDefault(); let spec; try { spec = JSON.parse(plan.spec || '{}'); } catch { setError('Plan specification must be valid JSON.'); return; } run(() => adminApi.createServerPlan({ name: plan.name, priceCents: Number(plan.priceCents), spec }), 'Server plan created.'); };
  const submitRegion = (e) => { e.preventDefault(); run(() => adminApi.createRegion({ ...region, providerId: region.providerId || undefined }), 'Region created.'); };
  const activate = (p) => run(() => adminApi.updateProvider(p.id, { status: p.active ? 'DISABLED' : 'ACTIVE' }), p.active ? 'Provider disabled.' : 'Provider activated.');
  return <div className="page"><div className="page-head"><div><h1>Infrastructure</h1><p className="muted">Manage provider records, deployment regions and server plans. Providers are created disabled and must pass configuration validation before activation.</p></div></div>{error && <div className="alert alert-error" role="alert">{error}</div>}{notice && <div className="alert alert-success" role="status">{notice}</div>}
    <div className="grid-2"><section className="card"><h2>Providers</h2>{providers === null ? <p className="muted">Loading…</p> : <div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Adapter</th><th>Status</th><th /></tr></thead><tbody>{providers.length ? providers.map(p => <tr key={p.id}><td><strong>{p.name}</strong><div className="muted small">{p.type || 'unspecified'}</div></td><td>{p.adapter || p.type || '—'}</td><td>{p.active ? 'active' : 'disabled'}</td><td><button type="button" className="linklike" onClick={() => activate(p)} disabled={busy}>{p.active ? 'Disable' : 'Activate'}</button></td></tr>) : <tr><td colSpan="4" className="muted">No providers configured.</td></tr>}</tbody></table></div>}
      <form className="nested-form" onSubmit={submitProvider}><h3>Add provider</h3><div className="field"><label htmlFor="infra-provider-name">Name</label><input id="infra-provider-name" value={provider.name} onChange={e => setProvider({...provider,name:e.target.value})} required /></div><div className="grid-2"><div className="field"><label htmlFor="infra-provider-type">Type</label><input id="infra-provider-type" placeholder="e.g. AWS" value={provider.providerType} onChange={e => setProvider({...provider,providerType:e.target.value})} /></div><div className="field"><label htmlFor="infra-provider-adapter">Adapter</label><input id="infra-provider-adapter" placeholder="e.g. aws" value={provider.adapter} onChange={e => setProvider({...provider,adapter:e.target.value})} /></div><div className="field"><label htmlFor="infra-provider-url">API base URL</label><input id="infra-provider-url" type="url" value={provider.apiBaseUrl} onChange={e => setProvider({...provider,apiBaseUrl:e.target.value})} /></div><div className="field"><label htmlFor="infra-provider-env">Credential env prefix</label><input id="infra-provider-env" value={provider.credentialEnvPrefix} onChange={e => setProvider({...provider,credentialEnvPrefix:e.target.value})} placeholder="AWS" /></div></div><button className="btn btn-primary" disabled={busy}>Create disabled provider</button></form></section>
      <section className="card"><h2>Regions</h2>{regions?.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Code</th><th>Provider</th></tr></thead><tbody>{regions.map(r => <tr key={r.id}><td>{r.name}</td><td>{r.code}</td><td>{providers?.find(p => p.id === r.providerId)?.name || '—'}</td></tr>)}</tbody></table></div> : <p className="muted">No regions configured.</p>}<form className="nested-form" onSubmit={submitRegion}><h3>Add region</h3><div className="grid-2"><div className="field"><label htmlFor="region-name">Name</label><input id="region-name" value={region.name} onChange={e => setRegion({...region,name:e.target.value})} required /></div><div className="field"><label htmlFor="region-code">Code</label><input id="region-code" value={region.code} onChange={e => setRegion({...region,code:e.target.value})} required /></div></div><div className="field"><label htmlFor="region-provider">Provider</label><select id="region-provider" value={region.providerId} onChange={e => setRegion({...region,providerId:e.target.value})}><option value="">Unassigned</option>{providers?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div><button className="btn btn-primary" disabled={busy}>Add region</button></form><h2 style={{ marginTop: 28 }}>Server plans</h2>{plans?.map(p => <div className="row" key={p.id}><strong>{p.name}</strong><span className="muted">{p.priceCents} cents · {p.active ? 'active' : 'inactive'}</span></div>)}<form className="nested-form" onSubmit={submitPlan}><h3>Add server plan</h3><div className="field"><label htmlFor="plan-name">Name</label><input id="plan-name" value={plan.name} onChange={e => setPlan({...plan,name:e.target.value})} required /></div><div className="field"><label htmlFor="plan-price">Price in cents</label><input id="plan-price" type="number" min="0" value={plan.priceCents} onChange={e => setPlan({...plan,priceCents:e.target.value})} required /></div><div className="field"><label htmlFor="plan-spec">Specification JSON</label><textarea id="plan-spec" rows="3" value={plan.spec} onChange={e => setPlan({...plan,spec:e.target.value})} /></div><button className="btn btn-primary" disabled={busy}>Add plan</button></form></section></div>
  </div>;
}
