/**
 * Seed data for the control-panel marketplace.
 *
 * Generated verbatim from
 * cloudhost247-node/database/migrations/0043_create_control_panels_and_plans.sql so the JSON
 * store starts from exactly the same catalogue the PostgreSQL migrations install.
 *
 * supported_os is a JSON array rather than a SQL TEXT[] because the pg backend serialises
 * structured columns as JSON (see toDriverValue in src/store/pg-store.js).
 */
'use strict';

const controlPanels = [
    {
      "id": "30000000-0000-0000-0000-000000000001",
      "name": "cPanel & WHM",
      "slug": "cpanel",
      "category": "SERVER_PANEL",
      "description": "Industry standard web hosting control panel with automated server management, multi-tier account administration, and comprehensive mail/DNS suites.",
      "logo_url": "/panel-logos/cpanel.svg",
      "website_url": "https://cpanel.net",
      "documentation_url": "https://docs.cpanel.net",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "CPANEL",
      "minimum_ram_mb": 2048,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 40,
      "supported_os": [
        "almalinux",
        "rocky-linux",
        "ubuntu",
        "cloudlinux"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": false,
        "reseller": true,
        "multi_user": true,
        "backups": true,
        "file_manager": true,
        "php_version_switch": true
      },
      "sort_order": 10
    },
    {
      "id": "30000000-0000-0000-0000-000000000002",
      "name": "Plesk Obsidian",
      "slug": "plesk",
      "category": "SERVER_PANEL",
      "description": "Leading WebOps hosting platform for building, securing, and running websites and applications in multi-cloud environments.",
      "logo_url": "/panel-logos/plesk.svg",
      "website_url": "https://www.plesk.com",
      "documentation_url": "https://docs.plesk.com",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "PLESK",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 20,
      "supported_os": [
        "ubuntu",
        "debian",
        "almalinux",
        "rocky-linux"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": true,
        "reseller": true,
        "multi_user": true,
        "backups": true,
        "git": true,
        "nodejs": true,
        "wordpress_toolkit": true
      },
      "sort_order": 20
    },
    {
      "id": "30000000-0000-0000-0000-000000000003",
      "name": "DirectAdmin",
      "slug": "directadmin",
      "category": "SERVER_PANEL",
      "description": "Fast, lightweight, and resource-efficient web hosting control panel offering complete domain, email, and database administration.",
      "logo_url": "/panel-logos/directadmin.svg",
      "website_url": "https://directadmin.com",
      "documentation_url": "https://docs.directadmin.com",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "DIRECTADMIN",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 20,
      "supported_os": [
        "almalinux",
        "rocky-linux",
        "debian",
        "ubuntu"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": false,
        "reseller": true,
        "multi_user": true,
        "backups": true
      },
      "sort_order": 30
    },
    {
      "id": "30000000-0000-0000-0000-000000000004",
      "name": "CyberPanel",
      "slug": "cyberpanel",
      "category": "SERVER_PANEL",
      "description": "Next-generation web hosting control panel powered by OpenLiteSpeed with built-in LSCache, staging, and container tools.",
      "logo_url": "/panel-logos/cyberpanel.svg",
      "website_url": "https://cyberpanel.net",
      "documentation_url": "https://community.cyberpanel.net/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "almalinux",
        "ubuntu"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": true,
        "reseller": false,
        "multi_user": true,
        "backups": true,
        "litespeed": true,
        "staging": true
      },
      "sort_order": 40
    },
    {
      "id": "30000000-0000-0000-0000-000000000005",
      "name": "Webmin",
      "slug": "webmin",
      "category": "SERVER_PANEL",
      "description": "Web-based system administration interface for Unix-like servers covering users, disks, firewalls, services, and packages.",
      "logo_url": "/panel-logos/webmin.svg",
      "website_url": "https://webmin.com",
      "documentation_url": "https://webmin.com/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 512,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 5,
      "supported_os": [
        "ubuntu",
        "debian",
        "almalinux",
        "rocky-linux",
        "fedora-cloud",
        "centos",
        "opensuse"
      ],
      "capabilities": {
        "domains": false,
        "databases": true,
        "email": false,
        "dns": true,
        "ssl": true,
        "docker": false,
        "multi_user": true,
        "system_admin": true,
        "firewall": true,
        "package_manager": true
      },
      "sort_order": 50
    },
    {
      "id": "30000000-0000-0000-0000-000000000006",
      "name": "HestiaCP",
      "slug": "hestiacp",
      "category": "SERVER_PANEL",
      "description": "Fast and clean open-source Linux web server control panel designed for easy administration of websites, email, and databases.",
      "logo_url": "/panel-logos/hestiacp.svg",
      "website_url": "https://hestiacp.com",
      "documentation_url": "https://hestiacp.com/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "debian",
        "ubuntu"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": false,
        "reseller": false,
        "multi_user": true,
        "backups": true,
        "php_version_switch": true
      },
      "sort_order": 60
    },
    {
      "id": "30000000-0000-0000-0000-000000000007",
      "name": "CloudPanel",
      "slug": "cloudpanel",
      "category": "SERVER_PANEL",
      "description": "High-performance server control panel built for PHP, Node.js, Python, and static apps with NGINX, MySQL, and Redis.",
      "logo_url": "/panel-logos/cloudpanel.svg",
      "website_url": "https://www.cloudpanel.io",
      "documentation_url": "https://www.cloudpanel.io/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 15,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": true,
        "multi_user": true,
        "nodejs": true,
        "python": true,
        "php_version_switch": true,
        "nginx_varnish": true
      },
      "sort_order": 70
    },
    {
      "id": "30000000-0000-0000-0000-000000000008",
      "name": "aaPanel",
      "slug": "aapanel",
      "category": "SERVER_PANEL",
      "description": "Modular web hosting control panel supporting one-click LNMP/LAMP stack installations and visual server management.",
      "logo_url": "/panel-logos/aapanel.svg",
      "website_url": "https://www.aapanel.com",
      "documentation_url": "https://doc.aapanel.com",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "ubuntu",
        "debian",
        "almalinux",
        "rocky-linux"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": true,
        "multi_user": false,
        "backups": true,
        "ftp": true,
        "file_manager": true
      },
      "sort_order": 80
    },
    {
      "id": "30000000-0000-0000-0000-000000000009",
      "name": "FASTPANEL",
      "slug": "fastpanel",
      "category": "SERVER_PANEL",
      "description": "Simple and fast web hosting control panel with intuitive site creation, multi-PHP switching, mail, and Let's Encrypt.",
      "logo_url": "/panel-logos/fastpanel.svg",
      "website_url": "https://fastpanel.direct",
      "documentation_url": "https://fastpanel.direct/wiki",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "INTERNAL",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "debian",
        "ubuntu",
        "almalinux",
        "rocky-linux"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": false,
        "multi_user": true,
        "backups": true,
        "multi_php": true,
        "web_terminal": true
      },
      "sort_order": 90
    },
    {
      "id": "30000000-0000-0000-0000-000000000010",
      "name": "Webuzo",
      "slug": "webuzo",
      "category": "SERVER_PANEL",
      "description": "Multi-user control panel offering automated web server provisioning, domain handling, and one-click Softaculous app installs.",
      "logo_url": "/panel-logos/webuzo.svg",
      "website_url": "https://webuzo.com",
      "documentation_url": "https://webuzo.com/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "WEBUZO",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "almalinux",
        "rocky-linux",
        "ubuntu"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": false,
        "multi_user": true,
        "backups": true,
        "softaculous": true
      },
      "sort_order": 100
    },
    {
      "id": "30000000-0000-0000-0000-000000000011",
      "name": "TinyCP",
      "slug": "tinycp",
      "category": "SERVER_PANEL",
      "description": "Lightweight Linux control panel for managing domains, databases, mail accounts, Samba shares, and VPN connections.",
      "logo_url": "/panel-logos/tinycp.svg",
      "website_url": "https://tinycp.com",
      "documentation_url": "https://tinycp.com/docs",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 512,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 5,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": false,
        "ssl": true,
        "docker": false,
        "multi_user": false,
        "samba": true,
        "openvpn": true
      },
      "sort_order": 110
    },
    {
      "id": "30000000-0000-0000-0000-000000000012",
      "name": "Kusanagi",
      "slug": "kusanagi",
      "category": "SERVER_PANEL",
      "description": "Ultra-fast WordPress and PHP execution environment by Prime Strategy optimized for enterprise web performance and caching.",
      "logo_url": "/panel-logos/kusanagi.svg",
      "website_url": "https://kusanagi.tokyo",
      "documentation_url": "https://kusanagi.tokyo/document",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 2048,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 20,
      "supported_os": [
        "almalinux",
        "rocky-linux",
        "centos"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": false,
        "multi_user": false,
        "wordpress_speed_stack": true,
        "page_cache": true
      },
      "sort_order": 120
    },
    {
      "id": "30000000-0000-0000-0000-000000000013",
      "name": "Dokploy",
      "slug": "dokploy",
      "category": "APPLICATION_DEPLOYMENT_PLATFORM",
      "description": "Open-source PaaS platform for deploying applications, databases, and Docker Compose projects with Traefik routing and SSL.",
      "logo_url": "/panel-logos/dokploy.svg",
      "website_url": "https://dokploy.com",
      "documentation_url": "https://docs.dokploy.com",
      "status": "ACTIVE",
      "installation_method": "DOCKER",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 2048,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 20,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": true,
        "docker_compose": true,
        "traefik": true,
        "git_deploy": true,
        "multi_user": true,
        "preview_deployments": true
      },
      "sort_order": 130
    },
    {
      "id": "30000000-0000-0000-0000-000000000014",
      "name": "Coolify",
      "slug": "coolify",
      "category": "APPLICATION_DEPLOYMENT_PLATFORM",
      "description": "Self-hostable, all-in-one developer PaaS alternative to Heroku/Netlify supporting Git deployments, Docker, and S3 backups.",
      "logo_url": "/panel-logos/coolify.svg",
      "website_url": "https://coolify.io",
      "documentation_url": "https://coolify.io/docs",
      "status": "ACTIVE",
      "installation_method": "DOCKER",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 2048,
      "minimum_cpu_cores": 2,
      "minimum_disk_gb": 30,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": true,
        "docker_compose": true,
        "traefik": true,
        "git_deploy": true,
        "s3_backups": true,
        "multi_user": true,
        "webhooks": true
      },
      "sort_order": 140
    },
    {
      "id": "30000000-0000-0000-0000-000000000015",
      "name": "Easypanel",
      "slug": "easypanel",
      "category": "APPLICATION_DEPLOYMENT_PLATFORM",
      "description": "Next-generation Docker management panel for full-stack apps, one-click databases, and automated SSL termination.",
      "logo_url": "/panel-logos/easypanel.svg",
      "website_url": "https://easypanel.io",
      "documentation_url": "https://easypanel.io/docs",
      "status": "ACTIVE",
      "installation_method": "DOCKER",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 20,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": true,
        "docker_compose": true,
        "traefik": true,
        "git_deploy": true,
        "app_templates": true
      },
      "sort_order": 150
    },
    {
      "id": "30000000-0000-0000-0000-000000000016",
      "name": "Cloudron",
      "slug": "cloudron",
      "category": "APPLICATION_DEPLOYMENT_PLATFORM",
      "description": "Turnkey server platform for self-hosting containerized smart applications with automated updates, DNS, and backups.",
      "logo_url": "/panel-logos/cloudron.svg",
      "website_url": "https://cloudron.io",
      "documentation_url": "https://docs.cloudron.io",
      "status": "ACTIVE",
      "installation_method": "SCRIPT",
      "requires_license": true,
      "license_provider": "CLOUDRON",
      "minimum_ram_mb": 2048,
      "minimum_cpu_cores": 2,
      "minimum_disk_gb": 20,
      "supported_os": [
        "ubuntu"
      ],
      "capabilities": {
        "domains": true,
        "databases": true,
        "email": true,
        "dns": true,
        "ssl": true,
        "docker": true,
        "smart_apps": true,
        "unified_auth": true,
        "automated_backups": true
      },
      "sort_order": 160
    },
    {
      "id": "30000000-0000-0000-0000-000000000017",
      "name": "Cosmos Cloud",
      "slug": "cosmos",
      "category": "APPLICATION_DEPLOYMENT_PLATFORM",
      "description": "Secure self-hosting operating platform featuring container management, integrated reverse proxy, 2FA, and app marketplace.",
      "logo_url": "/panel-logos/cosmos.svg",
      "website_url": "https://cosmos-cloud.io",
      "documentation_url": "https://cosmos-cloud.io/doc",
      "status": "ACTIVE",
      "installation_method": "DOCKER",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 1024,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 10,
      "supported_os": [
        "ubuntu",
        "debian"
      ],
      "capabilities": {
        "domains": true,
        "databases": false,
        "email": false,
        "dns": false,
        "ssl": true,
        "docker": true,
        "reverse_proxy": true,
        "app_store": true,
        "two_factor": true,
        "anti_bot": true
      },
      "sort_order": 170
    },
    {
      "id": "30000000-0000-0000-0000-000000000018",
      "name": "AdminBolt",
      "slug": "adminbolt",
      "category": "SERVER_MANAGEMENT",
      "description": "Centralized server management and telemetry agent providing automated health alerts, service tracking, and security monitoring.",
      "logo_url": "/panel-logos/adminbolt.svg",
      "website_url": "https://adminbolt.com",
      "documentation_url": "https://adminbolt.com/docs",
      "status": "ACTIVE",
      "installation_method": "AGENT",
      "requires_license": false,
      "license_provider": "NONE",
      "minimum_ram_mb": 512,
      "minimum_cpu_cores": 1,
      "minimum_disk_gb": 5,
      "supported_os": [
        "ubuntu",
        "debian",
        "almalinux",
        "rocky-linux"
      ],
      "capabilities": {
        "domains": false,
        "databases": false,
        "email": false,
        "dns": false,
        "ssl": false,
        "docker": false,
        "system_monitoring": true,
        "service_health": true,
        "remote_management": true,
        "security_audits": true
      },
      "sort_order": 180
    }
  ];

const controlPanelPlans = [
    {
      "id": "31000000-0000-0000-0000-000000000001",
      "control_panel_id": "30000000-0000-0000-0000-000000000001",
      "name": "cPanel Solo",
      "description": "1 cPanel Account / 1 Domain license",
      "billing_cycle": "monthly",
      "price": 17.49,
      "currency": "USD",
      "license_type": "SOLO",
      "included_domains": 1,
      "included_accounts": 1,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000002",
      "control_panel_id": "30000000-0000-0000-0000-000000000001",
      "name": "cPanel Admin (Up to 5 Accounts)",
      "description": "Up to 5 cPanel accounts for growing sites",
      "billing_cycle": "monthly",
      "price": 29.99,
      "currency": "USD",
      "license_type": "ADMIN",
      "included_domains": null,
      "included_accounts": 5,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000003",
      "control_panel_id": "30000000-0000-0000-0000-000000000001",
      "name": "cPanel Pro (Up to 30 Accounts)",
      "description": "Up to 30 cPanel accounts for agencies and VPS",
      "billing_cycle": "monthly",
      "price": 42.99,
      "currency": "USD",
      "license_type": "PRO",
      "included_domains": null,
      "included_accounts": 30,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000004",
      "control_panel_id": "30000000-0000-0000-0000-000000000002",
      "name": "Plesk Web Admin Edition",
      "description": "Up to 10 domains, optimized for basic web administration",
      "billing_cycle": "monthly",
      "price": 12.5,
      "currency": "USD",
      "license_type": "ADMIN",
      "included_domains": 10,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000005",
      "control_panel_id": "30000000-0000-0000-0000-000000000002",
      "name": "Plesk Web Pro Edition",
      "description": "Up to 30 domains with WordPress Toolkit and developer packs",
      "billing_cycle": "monthly",
      "price": 18.5,
      "currency": "USD",
      "license_type": "PRO",
      "included_domains": 30,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000006",
      "control_panel_id": "30000000-0000-0000-0000-000000000003",
      "name": "DirectAdmin Standard License",
      "description": "Unlimited domains and accounts with standard direct updates",
      "billing_cycle": "monthly",
      "price": 15,
      "currency": "USD",
      "license_type": "STANDARD",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000007",
      "control_panel_id": "30000000-0000-0000-0000-000000000004",
      "name": "CyberPanel Community Edition",
      "description": "Free OpenLiteSpeed edition with unlimited domains and cache",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000008",
      "control_panel_id": "30000000-0000-0000-0000-000000000005",
      "name": "Webmin Standard Interface",
      "description": "Open-source system administration suite with full server management",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000009",
      "control_panel_id": "30000000-0000-0000-0000-000000000006",
      "name": "HestiaCP Community Edition",
      "description": "Open-source free lightweight panel with unlimited domains",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000010",
      "control_panel_id": "30000000-0000-0000-0000-000000000007",
      "name": "CloudPanel Free Edition",
      "description": "Free high-performance PHP/Node/Python stack",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000011",
      "control_panel_id": "30000000-0000-0000-0000-000000000008",
      "name": "aaPanel Community Edition",
      "description": "Free modular Linux server control panel",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000012",
      "control_panel_id": "30000000-0000-0000-0000-000000000009",
      "name": "FASTPANEL Standard License",
      "description": "Free basic license for 1 server with multi-PHP",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000013",
      "control_panel_id": "30000000-0000-0000-0000-000000000010",
      "name": "Webuzo Free Trial / Single User",
      "description": "Webuzo server license for 1 domain",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": 1,
      "included_accounts": 1,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000014",
      "control_panel_id": "30000000-0000-0000-0000-000000000011",
      "name": "TinyCP Community Edition",
      "description": "Free lightweight Linux control panel",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000015",
      "control_panel_id": "30000000-0000-0000-0000-000000000012",
      "name": "Kusanagi High-Speed Edition",
      "description": "Ultra-fast WordPress environment optimized for Prime Strategy stacks",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000016",
      "control_panel_id": "30000000-0000-0000-0000-000000000013",
      "name": "Dokploy Community Edition",
      "description": "Open-source deployment platform for Docker and Traefik",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000017",
      "control_panel_id": "30000000-0000-0000-0000-000000000014",
      "name": "Coolify Self-Hosted Edition",
      "description": "Open-source all-in-one developer PaaS engine",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000018",
      "control_panel_id": "30000000-0000-0000-0000-000000000015",
      "name": "Easypanel Free Tier",
      "description": "Up to 3 projects with one-click app templates",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000019",
      "control_panel_id": "30000000-0000-0000-0000-000000000016",
      "name": "Cloudron Starter (2 Apps Free)",
      "description": "Free tier for up to 2 apps with full email/DNS automation",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000020",
      "control_panel_id": "30000000-0000-0000-0000-000000000017",
      "name": "Cosmos Community Edition",
      "description": "Open-source self-hosting and container management suite",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    },
    {
      "id": "31000000-0000-0000-0000-000000000021",
      "control_panel_id": "30000000-0000-0000-0000-000000000018",
      "name": "AdminBolt Agent & Monitoring",
      "description": "Automated server telemetry and health monitoring agent",
      "billing_cycle": "monthly",
      "price": 0,
      "currency": "USD",
      "license_type": "FREE",
      "included_domains": null,
      "included_accounts": null,
      "status": "ACTIVE"
    }
  ];

module.exports = { controlPanels, controlPanelPlans };
