/**
 * Phase 6 — HTTP client from the deployment worker to a CloudHost247 Server Agent (spec §30, §31).
 *
 * The agent base URL is resolved per server (servers.metadata.agent_url, admin-configured). All
 * requests are HMAC-signed per agent-protocol.ts. A small typed surface — deploy, teardown,
 * lifecycle, logs, health, backup, restore, metrics — is the ONLY Docker authority exposed to
 * the control plane; the agent never proxies arbitrary commands, and docker.sock never leaves
 * the server (spec §31).
 */
import { buildSignedHeaders } from './agent-protocol';
import { getKeyRing } from '../lib/keyring';
import { getCredential } from '../db/servers';
import type { Queryable } from '../db/types';

export class AgentUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'AgentUnavailableError';
  }
}

export interface AgentServerRef {
  id: string;
  agentId: string | null;
  agentUrl: string | null;
}

export interface AgentAppDeploymentRequest {
  /** Compose file content generated by src/deployments/compose-generator.ts. */
  composeYaml: string;
  /** Environment variables (secrets included) for this deployment. */
  environment: Record<string, string>;
  /** Traefik dynamic-config file content (router for the customer's domain), if any. */
  traefikDynamicYaml?: string | null;
}

export interface AgentContainerStatus {
  name: string;
  state: string;
  health?: string;
}

export interface AgentAppStatus {
  running: boolean;
  containers: AgentContainerStatus[];
}

export interface AgentHealthReport {
  healthy: boolean;
  detail: string;
}

export interface AgentSystemReport {
  cpuPercent: number | null;
  load1: number | null;
  load5: number | null;
  load15: number | null;
  memoryUsedMb: number | null;
  memoryTotalMb: number | null;
  diskUsedMb: number | null;
  diskTotalMb: number | null;
  networkInBytes: number | null;
  networkOutBytes: number | null;
  uptimeSeconds: number | null;
  dockerContainers: number | null;
  dockerContainersHealthy: number | null;
  agentVersion: string;
}

function requireAgentRef(server: AgentServerRef): { agentId: string; baseUrl: string } {
  if (!server.agentId) throw new AgentUnavailableError('Server has no agent registered');
  if (!server.agentUrl) throw new AgentUnavailableError('Server agent URL is not configured');
  return { agentId: server.agentId, baseUrl: server.agentUrl.replace(/\/$/, '') };
}

/**
 * Signed JSON request to an agent. `db` is only consulted for the agent secret (decrypted
 * in-memory for the lifetime of the call, never logged, never returned).
 */
export async function agentRequest<T>(
  db: Queryable,
  server: AgentServerRef,
  method: 'GET' | 'POST',
  path: string,
  body?: unknown
): Promise<T> {
  const { agentId, baseUrl } = requireAgentRef(server);
  const secret = await getCredential(db, getKeyRing(), server.id, 'agent_secret');
  if (!secret) throw new AgentUnavailableError('Server has no agent secret stored');

  const bodyText = body === undefined ? '' : JSON.stringify(body);
  const headers = buildSignedHeaders(agentId, secret, method, path, bodyText);

  let response: Response;
  try {
    response = await fetch(`${baseUrl}${path}`, {
      method,
      headers: { 'content-type': 'application/json', ...headers },
      body: method === 'GET' ? undefined : bodyText,
      signal: AbortSignal.timeout(120_000),
    });
  } catch (err) {
    throw new AgentUnavailableError(`Agent unreachable: ${(err as Error).message}`);
  }

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new AgentUnavailableError(`Agent responded ${response.status}: ${text.slice(0, 500)}`);
  }
  return (await response.json()) as T;
}

// --- Typed agent operations (the complete controlled surface, spec §31) --------------------------

export function agentDeployApp(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  request: AgentAppDeploymentRequest
): Promise<{ project: string; started: boolean }> {
  return agentRequest(db, server, 'POST', `/v1/apps/${encodeURIComponent(project)}/deploy`, request);
}

export function agentTearDownApp(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  removeVolumes: boolean
): Promise<{ project: string; removed: boolean }> {
  return agentRequest(db, server, 'POST', `/v1/apps/${encodeURIComponent(project)}/teardown`, { removeVolumes });
}

export function agentStartApp(db: Queryable, server: AgentServerRef, project: string) {
  return agentRequest<{ started: boolean }>(db, server, 'POST', `/v1/apps/${encodeURIComponent(project)}/start`, {});
}

export function agentStopApp(db: Queryable, server: AgentServerRef, project: string) {
  return agentRequest<{ stopped: boolean }>(db, server, 'POST', `/v1/apps/${encodeURIComponent(project)}/stop`, {});
}

export function agentRestartApp(db: Queryable, server: AgentServerRef, project: string) {
  return agentRequest<{ restarted: boolean }>(db, server, 'POST', `/v1/apps/${encodeURIComponent(project)}/restart`, {});
}

export function agentAppStatus(db: Queryable, server: AgentServerRef, project: string) {
  return agentRequest<AgentAppStatus>(db, server, 'GET', `/v1/apps/${encodeURIComponent(project)}/status`);
}

export function agentAppLogs(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  tail = 200
) {
  return agentRequest<{ logs: string }>(
    db,
    server,
    'GET',
    `/v1/apps/${encodeURIComponent(project)}/logs?tail=${tail}`
  );
}

export function agentRunHealthcheck(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  service: string,
  check: { type: string; path?: string; port?: number; command?: string[]; timeoutMs: number }
) {
  return agentRequest<AgentHealthReport>(
    db,
    server,
    'POST',
    `/v1/apps/${encodeURIComponent(project)}/healthcheck`,
    { service, check }
  );
}

export function agentRunBackup(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  options: { includeVolumes: boolean; includeDatabases: boolean }
) {
  return agentRequest<{ archivePath: string; sizeBytes: number; checksum: string }>(
    db,
    server,
    'POST',
    `/v1/apps/${encodeURIComponent(project)}/backup`,
    options
  );
}

export function agentRestoreBackup(
  db: Queryable,
  server: AgentServerRef,
  project: string,
  archivePath: string
) {
  return agentRequest<{ restored: boolean }>(
    db,
    server,
    'POST',
    `/v1/apps/${encodeURIComponent(project)}/restore`,
    { archivePath }
  );
}

export function agentSystemReport(db: Queryable, server: AgentServerRef) {
  return agentRequest<AgentSystemReport>(db, server, 'GET', '/v1/system/report');
}

export function agentPing(db: Queryable, server: AgentServerRef) {
  return agentRequest<{ ok: boolean; version: string }>(db, server, 'GET', '/v1/ping');
}
