<?php
if(PHP_SAPI!=='cli'){http_response_code(403);exit("CLI only\n");}
final class Ch247Staging
{
 public static function root($arg){if(getenv('CH247_STAGING_CONFIRM')!=='YES')self::fail('CH247_STAGING_CONFIRM=YES is required.');$root=realpath($arg?:'');if(!$root||!is_file($root.'/init.php')||!is_file($root.'/configuration.php'))self::fail('A valid WHMCS document root is required.');return$root;}
 public static function verifyEnvironment($root){$expected=trim((string)getenv('CH247_EXPECTED_STAGING_URL'));$identity=trim((string)getenv('CH247_STAGING_ID'));if($expected===''||$identity===''||!preg_match('/^[A-Za-z0-9._-]{3,100}$/',$identity))self::fail('Expected staging URL and staging identity are mandatory.');$url=(string)\WHMCS\Database\Capsule::table('tblconfiguration')->where('setting','SystemURL')->value('value');$expectedHost=strtolower((string)parse_url($expected,PHP_URL_HOST));$host=strtolower((string)parse_url($url,PHP_URL_HOST));if(!$host||!hash_equals($expectedHost,$host))self::fail('WHMCS SystemURL does not match the independently supplied staging URL.');$allowed=array_filter(array_map('trim',explode(',',strtolower((string)getenv('CH247_STAGING_HOST_ALLOWLIST')))));if(!$allowed||!in_array($host,$allowed,true))self::fail('Host is not in CH247_STAGING_HOST_ALLOWLIST.');if(preg_match('/(^|[.-])(www|prod|production)([.-]|$)/i',$host)||stripos($identity,'prod')!==false)self::fail('Production-looking environment rejected.');$database=(string)\WHMCS\Database\Capsule::selectOne('select database() as name')->name;$dbMarker=strtolower((string)getenv('CH247_STAGING_DB_MARKER'));if($dbMarker===''||strpos(strtolower($database),$dbMarker)===false)self::fail('Database does not contain the required staging marker.');return array('verified_non_production'=>true,'identity'=>$identity,'system_url'=>$url,'host'=>$host,'database_name_hash'=>hash('sha256',$database));}
 public static function write(array$data,$path){$data['generated_utc']=gmdate('c');$data['contains_customer_rows']=false;$json=json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";if($path){$dir=dirname($path);if(!is_dir($dir)||!is_writable($dir))self::fail('Evidence output directory is not writable.');file_put_contents($path,$json,LOCK_EX);chmod($path,0600);}else echo$json;}
 public static function fail($message){fwrite(STDERR,$message."\n");exit(2);}
}
