id: minio
name: MinIO
category: storage
description: S3-compatible high-performance object storage for your own private cloud.
website: https://min.io
repository: https://github.com/minio/minio
documentation: https://min.io/docs/minio/container/index.html
license: AGPL-3.0
featured: false
popularity: 730
deployment:
  engine: docker-compose
supportedHostingTypes:
- docker
- vps
- dedicated
- kubernetes
requirements:
  cpu: 1
  memory: 1024
  storage: 102400
  recommended:
    cpu: 2
    memory: 4096
    storage: 512000
services:
  app:
    image: minio/minio
    internal: false
    port: 9000
    command: server /data --console-address ":9001"
    volumes:
    - /data
environment:
  required:
  - key: MINIO_ROOT_USER
    default: ch247admin
  - key: MINIO_ROOT_PASSWORD
    secret: true
    generate: random_32
  optional: []
domain:
  enabled: true
  primaryRequired: false
healthcheck:
  type: http
  path: /minio/health/live
  port: 9000
ssl:
  enabled: true
backup:
  enabled: true
  includes:
  - volumes
update:
  strategy: pull-and-recreate
versions:
- version: '2025.1'
  image: minio/minio:RELEASE.2025-01-20T14-49-07Z
  stable: true
