<article class="ch247-tools__print">
<header>
<h1>CloudHost247 Network Tools report</h1>
<p>{$ch247Tools.tool.name|escape}{if $ch247Tools.print.rows} — {$ch247Tools.print.generated_at|escape}{/if}</p>
{if $ch247Tools.format == 'pdf'}<p class="ch247-tools__hint">Use your browser's Print dialog and choose “Save as PDF”. The report is laid out for A4/Letter.</p>{/if}
{if $ch247Tools.format == 'png' || $ch247Tools.format == 'svg'}<p class="ch247-tools__hint">This page is rendered as an image by your browser: use your device's screenshot or “Save as image” action. The CloudHost247 server does not bundle an image library.</p>{/if}
</header>
<p class="ch247-tools__message">{$ch247Tools.print.message|escape}</p>
{if $ch247Tools.print.warnings}
<ul class="ch247-tools__warnings">{foreach $ch247Tools.print.warnings as $warning}<li>{$warning|escape}</li>{/foreach}</ul>
{/if}
<dl class="ch247-tools__rows">
{foreach $ch247Tools.print.rows as $row}
<div class="ch247-tools__row"><dt>{$row.label|escape}</dt><dd>{$row.value|escape|nl2br}</dd></div>
{/foreach}
</dl>
{foreach $ch247Tools.print.sections as $section}
<section><h2>{$section.label|escape}</h2>
<dl class="ch247-tools__rows">{foreach $section.rows as $row}<div class="ch247-tools__row"><dt>{$row.label|escape}</dt><dd>{$row.value|escape|nl2br}</dd></div>{/foreach}</dl>
{foreach $section.tables as $table}{include file="cloudhost247-tools-table.tpl" table=$table}{/foreach}
</section>
{/foreach}
{foreach $ch247Tools.print.tables as $table}{include file="cloudhost247-tools-table.tpl" table=$table}{/foreach}
<footer><p>Generated by CloudHost247 Network Tools on {$ch247Tools.print.generated_at|escape}. Results describe the moment of the check; they are not a certification or a guarantee.</p></footer>
</article>
