<main id="main-content">{include file="cloudhost247/includes/product-hero.tpl"}
{* The platform pages render the same registry sections as every other product page, then the
   live catalogue block (or the honest "not connected" state) below. *}
{if $ch247Site.page.sections}{include file="cloudhost247/includes/product-sections.tpl"}{/if}
<section class="ch-section"><div class="ch-wrap">
{if $ch247Site.path == 'server-management.php'}<div class="ch-split"><div><p class="ch-kicker">Service-specific controls</p><h2>Manage the services<br>you actually own.</h2><p>Start, stop, reboot, logs, backups and other operations depend on your product and provider. Open the service details in your account to see which actions are supported.</p><a class="ch-btn ch-btn-dark" href="{$WEB_ROOT}/clientarea.php?action=services">Open My Services →</a></div><img src="{$WEB_ROOT}/assets/images/cloudhost247/management/server-control.svg" width="660" height="560" loading="lazy" alt="Conceptual server management diagram"></div>
{elseif $ch247Site.platform}
<div data-ch-catalog="{if $ch247Site.path == 'operating-systems.php'}os{else}apps{/if}" data-platform="{$ch247Site.platform|escape}"><p class="ch-kicker">Live platform catalog</p><h2>{if $ch247Site.path == 'operating-systems.php'}Verified image families{else}Configured applications{/if}</h2><p data-catalog-status role="status">Loading the connected platform catalog…</p><div class="ch-grid-3" data-catalog-results></div><noscript><p>Open the platform catalog to view current availability.</p></noscript><a class="ch-btn ch-btn-dark" href="{$ch247Site.platform|escape}/{if $ch247Site.path == 'operating-systems.php'}servers/new{else}apps{/if}">Open Platform →</a></div>
{else}<div class="ch-notice"><h2>Platform catalog not connected</h2><p>This website has not been connected to a verified platform catalog. No applications, operating-system images or deployment availability are being advertised here.</p><p>Contact the team to discuss current options for your project.</p><a class="ch-btn ch-btn-dark" href="{$WEB_ROOT}/contact.php">Contact Sales →</a></div>{/if}
</div></section>{if $ch247Site.path == 'operating-systems.php'}<section class="ch-section" id="families"><div class="ch-wrap"><p class="ch-kicker">Image families</p><h2>Families an operator can map.</h2><p>These names are catalogue families. A family is available only when the connected platform returns it. This list is not stock.</p><div class="ch-tool-related"><a id="ubuntu" href="#ubuntu">Ubuntu</a><a id="debian" href="#debian">Debian</a><a id="almalinux" href="#almalinux">AlmaLinux</a><a id="rocky" href="#rocky">Rocky Linux</a><a id="windows" href="#windows">Windows Server</a><a id="wordpress" href="#wordpress">WordPress</a><a id="docker" href="#docker">Docker</a><a id="lamp" href="#lamp">LAMP</a><a id="lemp" href="#lemp">LEMP</a><a id="cpanel" href="#cpanel">cPanel</a><a id="plesk" href="#plesk">Plesk</a></div></div></section>{/if}
{if $ch247Site.path == 'applications.php'}<section class="ch-section"><div class="ch-wrap"><p class="ch-kicker">Manifest catalog</p><h2>Applications with a deployment manifest.</h2><p>Joomla, Drupal, Magento, OpenCart and WooCommerce are not in the current manifest set, so they are not offered as one-click applications.</p><div class="ch-tool-related"><a id="wordpress" href="{$WEB_ROOT}/wordpress-hosting.php">WordPress</a><a id="ghost" href="#ghost">Ghost</a><a id="prestashop" href="#prestashop">PrestaShop</a></div></div></section>{/if}
{include file="cloudhost247/includes/site-cta.tpl"}</main>
