<main id="main-content">{include file="cloudhost247/includes/product-hero.tpl"}
{* The platform pages render the same registry sections as every other product page, then the
   live catalogue block (or the honest "not connected" state) below. *}
{if $ch247Site.page.sections}{include file="cloudhost247/includes/product-sections.tpl"}{/if}
<section class="ch-section"><div class="ch-wrap">
{if $ch247Site.path == 'server-management.php'}<div class="ch-split"><div><p class="ch-kicker">Service-specific controls</p><h2>Manage the services<br>you actually own.</h2><p>Start, stop, reboot, logs, backups and other operations depend on your product and provider. Open the service details in your account to see which actions are supported.</p><a class="ch-btn ch-btn-dark" href="{$WEB_ROOT}/clientarea.php?action=services">Open My Services →</a></div><img src="{$WEB_ROOT}/assets/images/cloudhost247/management/server-control.svg" width="660" height="560" loading="lazy" alt="Conceptual server management diagram"></div>
{elseif $ch247Site.platform}
<div data-ch-catalog="{if $ch247Site.path == 'operating-systems.php'}os{else}apps{/if}" data-platform="{$ch247Site.platform|escape}"><p class="ch-kicker">Live platform catalog</p><h2>{if $ch247Site.path == 'operating-systems.php'}Verified image families{else}Configured applications{/if}</h2><p data-catalog-status role="status">Loading the connected platform catalog…</p><div class="ch-grid-3" data-catalog-results></div><noscript><p>Open the platform catalog to view current availability.</p></noscript><a class="ch-btn ch-btn-dark" href="{$ch247Site.platform|escape}/{if $ch247Site.path == 'operating-systems.php'}servers/new{else}apps{/if}">Open Platform →</a></div>
{else}<div class="ch-notice"><h2>Platform catalog not connected</h2><p>This website has not been connected to a verified platform catalog. No applications, operating-system images or deployment availability are being advertised here.</p><p>Contact the team to discuss current options for your project.</p><a class="ch-btn ch-btn-dark" href="{$WEB_ROOT}/contact.php">Contact Sales →</a></div>{/if}
</div></section>{if $ch247Site.path == 'operating-systems.php'}<section class="ch-section" id="families"><div class="ch-wrap"><p class="ch-kicker">Image families</p><h2>Families an operator can map.</h2><p>These names are catalogue families. A family is available only when the connected platform returns it. This list is not stock.</p><div class="ch-tool-related"><a id="ubuntu" href="#ubuntu">Ubuntu</a><a id="debian" href="#debian">Debian</a><a id="almalinux" href="#almalinux">AlmaLinux</a><a id="rocky" href="#rocky">Rocky Linux</a><a id="windows" href="#windows">Windows Server</a><a id="wordpress" href="#wordpress">WordPress</a><a id="docker" href="#docker">Docker</a><a id="lamp" href="#lamp">LAMP</a><a id="lemp" href="#lemp">LEMP</a><a id="cpanel" href="#cpanel">cPanel</a><a id="plesk" href="#plesk">Plesk</a></div></div></section>{/if}
{if $ch247Site.path == 'applications.php'}<section class="ch-section"><div class="ch-wrap" data-ch-manifests><p class="ch-kicker">Application directory</p><h2>Explore the manifest catalogue.</h2><p>These are the application manifests shipped with CloudHost247, not a claim of deployment availability. An eligible service and a published live application version are required to install. Third-party names identify software; marks are neutral CloudHost247 monograms.</p><div class="ch-catalog-controls"><label>Search applications<input type="search" data-manifest-search maxlength="100" placeholder="Name, category or description"></label><label>Category<select data-manifest-category><option value="">All categories</option></select></label></div><p role="status" data-manifest-status></p><div class="ch-grid-3">{foreach $ch247Site.applicationManifests as $app}<article class="ch-plan" data-manifest-card data-category="{$app.category|escape}"><img src="{$WEB_ROOT}/assets/images/cloudhost247/{$app.mark|escape}" width="64" height="64" alt="" loading="lazy"><p class="ch-kicker">{$app.category|escape}</p><h3>{$app.name|escape}</h3><p>{$app.description|escape}</p><dl><dt>Manifest versions</dt><dd>{foreach $app.versions as $version}{$version|escape}{if !$version@last}, {/if}{/foreach}</dd><dt>Deployment method</dt><dd>{$app.deployment|escape}</dd><dt>Minimum resources</dt><dd>{$app.requirements.cpu|escape} CPU · {$app.requirements.memory|escape} MB RAM · {$app.requirements.storage|escape} MB storage</dd><dt>Compatible hosting types</dt><dd>{foreach $app.relatedHosting as $type}{$type|escape}{if !$type@last}, {/if}{/foreach}</dd></dl><p class="ch-note">Manifest available. Confirm eligibility with the live platform before deployment.</p>{if $ch247Site.platform}<a class="ch-text-link" href="{$ch247Site.platform|escape}/apps/{$app.slug|escape}">Versions &amp; deployment requirements →</a>{else}<a class="ch-text-link" href="{$WEB_ROOT}/contact.php">Discuss application hosting →</a>{/if}</article>{/foreach}</div></div></section>{/if}
{include file="cloudhost247/includes/site-cta.tpl"}</main>
