{*
    CloudHost247 - public product catalogue (cloudhost247-hosting.php).

    Data contract (assigned by cloudhost247-hosting.php, from PublicCatalog):
      $ch247Products      verified, visible, available products for the selected kind
      $ch247ProductKind   the `?type=` filter currently applied ('' | hosting | vps | dedicated)
      $ch247CatalogError  a safe display message when the catalogue could not be read

    Markup notes, because this page previously rendered an older system:
      * The grid and cards are the design system's (`ch-plan-grid`, `ch-plan`), the same components
        `includes/product-plans.tpl` and the application's plan lists use. This page used
        `ch247-product-grid` / `ch247-product-card__kind`, which were defined only in
        `css/custom.css` — a stylesheet the theme does not load — so the plans rendered as an
        unstyled stack, and the call to action was a Bootstrap `btn btn-primary`.
      * A price that WHMCS has not returned is published as NOT VERIFIED rather than omitted or
        guessed: a plan page that shows no price reads as free, and a made-up one is worse.
*}
<main id="main-content">{include file="cloudhost247/includes/product-hero.tpl"}<section id="catalog-plans" class="ch-section" aria-labelledby="catalog-title"><div class="ch-wrap"><div class="ch-section-heading"><div><p class="ch-kicker">Live product catalogue</p><h2 id="catalog-title">Cloud hosting plans</h2></div><p>Choose a verified, currently available CloudHost247 plan. Configuration and checkout remain securely handled by WHMCS.</p></div><nav class="ch-actions" aria-label="Product type"><a class="ch-btn ch-btn--sm{if $ch247ProductKind == ''} ch-btn--mint{else} ch-btn--outline{/if}"{if $ch247ProductKind == ''} aria-current="page"{/if} href="cloudhost247-hosting.php">All</a><a class="ch-btn ch-btn--sm{if $ch247ProductKind == 'hosting'} ch-btn--mint{else} ch-btn--outline{/if}"{if $ch247ProductKind == 'hosting'} aria-current="page"{/if} href="cloudhost247-hosting.php?type=hosting">Hosting</a><a class="ch-btn ch-btn--sm{if $ch247ProductKind == 'vps'} ch-btn--mint{else} ch-btn--outline{/if}"{if $ch247ProductKind == 'vps'} aria-current="page"{/if} href="cloudhost247-hosting.php?type=vps">VPS</a><a class="ch-btn ch-btn--sm{if $ch247ProductKind == 'dedicated'} ch-btn--mint{else} ch-btn--outline{/if}"{if $ch247ProductKind == 'dedicated'} aria-current="page"{/if} href="cloudhost247-hosting.php?type=dedicated">Dedicated servers</a></nav>{if $ch247CatalogError}<p class="ch-note ch-note--warn" role="alert">{$ch247CatalogError|escape}</p>{/if}{if $ch247Products}<div class="ch-plan-grid">{foreach $ch247Products as $product}<article class="ch-plan"><p class="ch-kicker">{if $product.featured}Featured · {/if}{$product.kind|capitalize|escape} · {$product.availability|capitalize|escape}</p><h3>{$product.name|escape}</h3><p class="ch-muted">{$product.description|escape}</p>{if $product.specifications}<h4>Specifications</h4><ul>{foreach $product.specifications as $label=>$value}{if $value}<li><strong>{$label|replace:'_':' '|capitalize|escape}</strong>: {$value|escape}</li>{/if}{/foreach}</ul>{/if}<h4>Pricing</h4>{if $product.pricing}<div class="ch-table-wrap"><table class="ch-table"><caption class="ch-visually-hidden">Verified {$product.currency|escape} pricing for {$product.name|escape}</caption><tbody>{foreach $product.pricing as $cycle=>$price}<tr><th scope="row">{$cycle|capitalize|escape}</th><td>{$product.prefix|escape}{$price|escape}{$product.suffix|escape} {$product.currency|escape}</td></tr>{/foreach}</tbody></table></div>{else}<p class="ch-muted"><strong>Pricing: NOT VERIFIED</strong> — WHMCS has not returned a price for this configuration.</p>{/if}<a class="ch-btn ch-btn-dark" href="{$product.cart_url|escape}">Configure in WHMCS</a></article>{/foreach}</div>{else}<p class="ch-notice">No verified available products match this selection. <a class="ch-text-link" href="cloudhost247-hosting.php">Show every plan</a></p>{/if}</div></section>{include file="cloudhost247/includes/site-cta.tpl"}</main>
