<?php
namespace CloudHost247\Ovh\Pricing;
use CloudHost247\Foundation\Support\AuditLogger;use CloudHost247\Foundation\Support\Logger;use WHMCS\Database\Capsule;use InvalidArgumentException;
final class PricingService
{
 private$calc;function __construct(PriceCalculator$c){$this->calc=$c;}
 function preview($mappingId,$currencyId,$cycle,$sourcePrice,$sourceCurrency,$rounding='nearest',$precision=2,$component='recurring'){$cycles=array('monthly','quarterly','semiannually','annually','biennially','triennially');if(!in_array($cycle,$cycles,true))throw new InvalidArgumentException('Unsupported billing cycle.');if(!in_array($component,array('recurring','setup','one_time'),true))throw new InvalidArgumentException('Unsupported price component.');$m=Capsule::table('mod_cloudhost247_ovh_product_mappings')->where('id',(int)$mappingId)->first();$target=Capsule::table('tblcurrencies')->where('id',(int)$currencyId)->first();$source=Capsule::table('tblcurrencies')->where('code',strtoupper($sourceCurrency))->first();if(!$m||!$target||!$source)throw new InvalidArgumentException('Mapping or currency is unavailable.');if((float)$source->rate<=0||(float)$target->rate<=0)throw new InvalidArgumentException('A verified positive source and target currency rate is required.');$column=$this->column($cycle,$component);$pricing=Capsule::table('tblpricing')->where('type','product')->where('relid',$m->whmcs_product_id)->where('currency',$target->id)->first();if(!$pricing)throw new InvalidArgumentException('WHMCS pricing row does not exist; a preview cannot create it silently.');$final=$this->calc->calculate($sourcePrice,$source->rate,$target->rate,$m->margin_percent,$precision,$rounding);$correlation=Logger::correlationId();$id=Capsule::table('mod_cloudhost247_ovh_price_previews')->insertGetId(array('mapping_id'=>$m->id,'whmcs_currency_id'=>$target->id,'billing_cycle'=>$cycle,'price_component'=>$component,'source_price'=>$sourcePrice,'source_currency'=>$source->code,'conversion_rate'=>$target->rate/$source->rate,'margin_percent'=>$m->margin_percent,'rounding_mode'=>$rounding,'precision_digits'=>(int)$precision,'current_price'=>$pricing->{$column},'final_price'=>$final,'status'=>'preview','correlation_id'=>$correlation,'admin_id'=>$_SESSION['adminid']??null,'created_at'=>date('Y-m-d H:i:s')));return array('id'=>$id,'component'=>$component,'source_price'=>(float)$sourcePrice,'source_currency'=>$source->code,'conversion_rate'=>$target->rate/$source->rate,'margin'=>(float)$m->margin_percent,'rounding'=>$rounding,'precision'=>(int)$precision,'current_price'=>(float)$pricing->{$column},'final_price'=>$final,'target_currency'=>$target->code,'billing_cycle'=>$cycle,'correlation_id'=>$correlation);}
 function apply($previewId,$confirmed){if(!$confirmed)throw new InvalidArgumentException('Explicit pricing confirmation is required.');return Capsule::connection()->transaction(function()use($previewId){$p=Capsule::table('mod_cloudhost247_ovh_price_previews')->where('id',(int)$previewId)->where('status','preview')->lockForUpdate()->first();if(!$p)throw new InvalidArgumentException('Unused preview not found; it may already have been applied.');$m=Capsule::table('mod_cloudhost247_ovh_product_mappings')->where('id',$p->mapping_id)->first();if(!$m)throw new InvalidArgumentException('Product mapping no longer exists.');$pricing=Capsule::table('tblpricing')->where('type','product')->where('relid',$m->whmcs_product_id)->where('currency',$p->whmcs_currency_id)->lockForUpdate()->first();if(!$pricing)throw new InvalidArgumentException('WHMCS pricing row does not exist; it will not be created silently.');$column=$this->column($p->billing_cycle,$p->price_component);$before=$pricing->{$column};if(abs((float)$before-(float)$p->current_price)>0.00000001)throw new InvalidArgumentException('Current WHMCS price changed after preview; generate a new preview.');Capsule::table('tblpricing')->where('id',$pricing->id)->update(array($column=>$p->final_price));Capsule::table('mod_cloudhost247_ovh_price_previews')->where('id',$p->id)->update(array('status'=>'applied','applied_at'=>date('Y-m-d H:i:s')));AuditLogger::record('cloudhost247_ovh','price.apply','product',$m->whmcs_product_id,array($column=>$before),array($column=>$p->final_price),'success',null,$_SESSION['adminid']??null);return$p->final_price;});}
 private function column($cycle,$component){if($component==='setup'){$map=array('monthly'=>'msetupfee','quarterly'=>'qsetupfee','semiannually'=>'ssetupfee','annually'=>'asetupfee','biennially'=>'bsetupfee','triennially'=>'tsetupfee');return$map[$cycle];}return$cycle;}
}
