<?php
require_once __DIR__.'/lib/staging-common.php';
$root=Ch247Staging::root(isset($argv[1])?$argv[1]:'');$output=$argv[2]??null;$mode=getenv('CH247_PREFLIGHT_MODE')?:'release-candidate';require$root.'/init.php';use WHMCS\Database\Capsule;
$environment=Ch247Staging::verifyEnvironment($root);$failures=array();$warnings=array();
$phpOk=version_compare(PHP_VERSION,'8.2.0','>=')&&version_compare(PHP_VERSION,'8.3.0','<');if(!$phpOk)$failures[]='Staging PHP must be an 8.2.x release.';
$extensions=array('curl','json','openssl','pdo_mysql','mbstring','dom','fileinfo','filter');$extensionState=array();foreach($extensions as$name){$extensionState[$name]=extension_loaded($name);if(!$extensionState[$name])$failures[]='Missing PHP extension: '.$name;}
$directories=array('templates_c','attachments','downloads');$directoryState=array();foreach($directories as$name){$path=realpath($root.'/'.$name);$directoryState[$name]=array('exists'=>(bool)$path,'writable'=>$path?is_writable($path):false);if(!$path||!is_writable($path))$failures[]='Required writable directory unavailable: '.$name;}
$requiredWhmcs=array('admin','includes','modules','templates','vendor');$whmcsDirs=array();foreach($requiredWhmcs as$name){$whmcsDirs[$name]=is_dir($root.'/'.$name);if(!$whmcsDirs[$name])$failures[]='Required WHMCS directory missing: '.$name;}
$components=array('modules/addons/cloudhost247_core/cloudhost247_core.php','modules/addons/cloudhost247_currency/cloudhost247_currency.php','modules/addons/cloudhost247_theme/cloudhost247_theme.php','modules/addons/cloudhost247_ovh/cloudhost247_ovh.php','modules/servers/cloudhost247_ovh/cloudhost247_ovh.php','templates/cloudhost247/theme.yaml','templates/orderforms/cloudhost247/theme.yaml');$componentState=array();foreach($components as$file){$componentState[$file]=is_file($root.'/'.$file);if($mode!=='baseline'&&!$componentState[$file])$failures[]='Release-candidate component missing: '.$file;}
$migrations=array('core'=>array('modules/addons/cloudhost247_core/lib/Database/CoreAuditMigration.php'),'currency'=>array('modules/addons/cloudhost247_currency/migrations/V100.php','modules/addons/cloudhost247_currency/migrations/V110.php'),'theme'=>array('modules/addons/cloudhost247_theme/migrations/V100.php','modules/addons/cloudhost247_theme/migrations/V110.php'),'ovh'=>array('modules/addons/cloudhost247_ovh/migrations/V100.php','modules/addons/cloudhost247_ovh/migrations/V110.php','modules/addons/cloudhost247_ovh/migrations/V120.php','modules/addons/cloudhost247_ovh/migrations/V130.php','modules/addons/cloudhost247_ovh/migrations/V140.php','modules/addons/cloudhost247_ovh/migrations/V150.php'));$migrationFiles=array();foreach($migrations as$module=>$files)foreach($files as$file){$migrationFiles[$file]=is_file($root.'/'.$file);if($mode!=='baseline'&&!$migrationFiles[$file])$failures[]='Migration missing: '.$file;}
$dbVersion=(string)Capsule::selectOne('select version() as version')->version;$requiredTables=array('tblconfiguration','tbladdonmodules','tblproducts','tblhosting','tblcurrencies','tblpricing');$dbTables=array();foreach($requiredTables as$table){$dbTables[$table]=Capsule::schema()->hasTable($table);if(!$dbTables[$table])$failures[]='Required WHMCS table missing: '.$table;}
$cloudTables=array();foreach(Capsule::select("show tables like 'mod_cloudhost247_%'")as$row)$cloudTables[]=array_values((array)$row)[0];sort($cloudTables);$migrationState=array();if(Capsule::schema()->hasTable('mod_cloudhost247_migrations'))foreach(Capsule::table('mod_cloudhost247_migrations')->select('module','version','applied_at')->orderBy('module')->orderBy('version')->get()as$row)$migrationState[]=array('module'=>$row->module,'version'=>$row->version,'applied_at'=>$row->applied_at);
$addons=array();foreach(Capsule::table('tbladdonmodules')->where('setting','version')->whereIn('module',array('cloudhost247_core','cloudhost247_currency','cloudhost247_theme','cloudhost247_ovh'))->select('module','value')->get()as$row)$addons[$row->module]=$row->value;
$config=array();foreach(array('Template','OrderFormTemplate','Version')as$key)$config[$key]=(string)Capsule::table('tblconfiguration')->where('setting',$key)->value('value');if($config['Version']==='')$warnings[]='WHMCS version setting is empty.';
$result=array('report_type'=>'staging_preflight','status'=>$failures?'FAIL':'PASS','mode'=>$mode,'environment'=>$environment,'commit'=>getenv('CH247_BUILD_COMMIT')?:'UNSET','runtime'=>array('whmcs_version'=>$config['Version'],'php_version'=>PHP_VERSION,'database_version'=>$dbVersion,'document_root'=>$root,'deployment_user'=>get_current_user()),'extensions'=>$extensionState,'whmcs_directories'=>$whmcsDirs,'writable_directories'=>$directoryState,'configuration_readable'=>is_readable($root.'/configuration.php'),'database_connected'=>true,'required_tables'=>$dbTables,'components'=>$componentState,'migration_files'=>$migrationFiles,'cloudhost247_tables'=>$cloudTables,'migration_state'=>$migrationState,'addon_activation'=>$addons,'presentation'=>array('client_theme'=>$config['Template'],'order_form'=>$config['OrderFormTemplate']),'failures'=>$failures,'warnings'=>$warnings);
Ch247Staging::write($result,$output);exit($failures?1:0);
