<?php
namespace CloudHost247\Rdp\Operations;use CloudHost247\Rdp\Contracts\Provider;use CloudHost247\Rdp\Contracts\Ledger;use CloudHost247\Rdp\Api\ProviderException;
final class LifecycleService
{
 private$p;$l;public function __construct(Provider$p,Ledger$l){$this->p=$p;$this->l=$l;}
 public function create($serviceId,$clientId,$productId){$existing=$this->l->binding($serviceId);if($existing)return array('status'=>$existing->status==='active'?'completed':'reconciliation_required','provider_service_id'=>$existing->provider_service_id);return$this->mutate('create',$serviceId,$clientId,function($key)use($serviceId,$productId){return$this->p->create(array('product_id'=>$productId,'client_reference'=>'whmcs-service-'.$serviceId),$key);},'active');}
 public function suspend($serviceId,$clientId){return$this->boundMutation('suspend',$serviceId,$clientId,'suspended');}public function unsuspend($serviceId,$clientId){return$this->boundMutation('unsuspend',$serviceId,$clientId,'active');}public function terminate($serviceId,$clientId){return$this->boundMutation('terminate',$serviceId,$clientId,'terminated');}
 private function boundMutation($op,$sid,$cid,$expected){$b=$this->ownedBinding($sid,$cid);return$this->mutate($op,$sid,$cid,function($key)use($op,$b){return$this->p->{$op}($b->provider_service_id,$key);},$expected,$b,(string)$b->updated_at);}
 private function mutate($op,$sid,$cid,callable$call,$expected,$binding=null,$generation='initial'){$key=hash('sha256','cloudhost247-rdp|'.$op.'|'.(int)$sid.'|'.$generation);$previous=$this->l->operation($key);if($previous){if($previous->status==='completed')return array('status'=>'completed','duplicate'=>true);if(in_array($previous->status,array('running','reconciliation_required','intervention_required'),true))return array('status'=>'reconciliation_required','duplicate'=>true);if($previous->status!=='failed')return array('status'=>'intervention_required');}$operationId=bin2hex(random_bytes(16));if(!$previous)$this->l->begin(array('service_id'=>$sid,'client_id'=>$cid,'operation'=>$op,'operation_id'=>$operationId,'idempotency_key'=>$key));else$this->l->retry($key);try{$r=$call($key);$status=(string)($r['status']??'');$providerId=isset($r['service']['id'])?(string)$r['service']['id']:($binding?$binding->provider_service_id:null);if($op==='create'&&!$providerId){$this->l->finish($key,'reconciliation_required',array('provider_operation_id'=>$r['operation_id']??null,'provider_status'=>$status),'missing_service_reference');return array('status'=>'reconciliation_required');}$evidence=array('provider_operation_id'=>$r['operation_id']??null,'provider_status'=>$status,'provider_service_id'=>$providerId);if($status!==$expected){$this->l->finish($key,'reconciliation_required',$evidence,'state_unconfirmed');if($op==='create'&&$providerId)$this->l->bind(array('service_id'=>$sid,'client_id'=>$cid,'provider_service_id'=>$providerId,'status'=>$status?:'unknown','details'=>$r['service']??array()));return array('status'=>'reconciliation_required');}if($op==='create'){$this->l->bind(array('service_id'=>$sid,'client_id'=>$cid,'provider_service_id'=>$providerId,'status'=>$status,'details'=>$r['service']));}else$this->l->updateBinding($sid,$status,$r['service']??array());$this->l->finish($key,'completed',$evidence);return array('status'=>'completed','provider_service_id'=>$providerId);}catch(ProviderException$e){$state=$e->uncertain()?'reconciliation_required':'failed';$this->l->finish($key,$state,array(),$e->kind());return array('status'=>$state,'error_code'=>$e->kind());}catch(\Throwable$e){$this->l->finish($key,'intervention_required',array(),'internal');return array('status'=>'intervention_required','error_code'=>'internal');}}
 public function reconcile($serviceId,$clientId){$b=$this->ownedBinding($serviceId,$clientId);try{$r=$this->p->service($b->provider_service_id);$remote=$r['service']['status']??'unknown';$local=$b->status;if($remote==='unknown')return array('status'=>'intervention_required','local'=>$local,'remote'=>'unknown');$match=$local===$remote;$this->l->updateBinding($serviceId,$remote,$r['service']);return array('status'=>$match?'matched':'mismatch','local'=>$local,'remote'=>$remote,'guidance'=>$match?'No action required.':'Administrator review required; no mutation was performed.');}catch(\Throwable$e){return array('status'=>'intervention_required','local'=>$b->status,'remote'=>'unknown','guidance'=>'Provider state could not be verified; do not retry a mutation.');}}
 private function ownedBinding($sid,$cid){$b=$this->l->binding($sid);if(!$b||(int)$b->client_id!==(int)$cid)throw new \RuntimeException('RDP service binding is unavailable or ownership does not match.');return$b;}
}
