<?php
namespace CloudHost247\Ovh\Operations;use WHMCS\Database\Capsule;
final class OperationsDashboard
{
 public function summary(array$f=array()){$page=max(1,(int)($f['ops_page']??1));$per=50;$ops=$this->query();$this->filters($ops,$f);$total=(clone$ops)->count();$rows=$ops->orderBy('o.id','desc')->offset(($page-1)*$per)->limit($per)->get()->all();$endpoints=Capsule::table('mod_cloudhost247_ovh_endpoints as e')->leftJoin('mod_cloudhost247_ovh_sync_runs as r','r.endpoint_id','=','e.id')->select('e.id','e.name','e.region','e.enabled','r.status as sync_status','r.started_at as last_sync','r.error_message')->orderBy('r.id','desc')->limit(100)->get()->all();$detail=null;if(!empty($f['operation_id'])){$detail=$this->query()->where('o.id',(int)$f['operation_id'])->first();}return array('operations'=>$rows,'endpoints'=>$endpoints,'reconciliation'=>$this->reconciliation($rows),'detail'=>$detail,'page'=>$page,'pages'=>max(1,(int)ceil($total/$per)),'total'=>$total,'counts'=>$this->counts());}
 private function query(){return Capsule::table('mod_cloudhost247_ovh_operations as o')->leftJoin('tblhosting as h','h.id','=','o.whmcs_service_id')->leftJoin('tblproducts as p','p.id','=','h.packageid')->leftJoin('mod_cloudhost247_ovh_services as s','s.whmcs_service_id','=','h.id')->leftJoin('mod_cloudhost247_ovh_endpoints as e','e.id','=','s.endpoint_id')->select('o.*','h.domain','h.domainstatus','p.name as product_name','s.status as provisioning_status','s.last_synced_at','e.region');}
 private function filters($q,array$f){if(!empty($f['region']))$q->where('e.region',substr($f['region'],0,8));if(!empty($f['product']))$q->where('p.id',(int)$f['product']);if(!empty($f['service']))$q->where('h.id',(int)$f['service']);if(!empty($f['status']))$q->where('o.status',substr($f['status'],0,32));if(!empty($f['operation']))$q->where('o.operation',substr($f['operation'],0,64));if(!empty($f['ops_q'])){$term='%'.substr(strip_tags((string)$f['ops_q']),0,100).'%';$q->where(function($x)use($term){$x->where('h.domain','like',$term)->orWhere('o.idempotency_key','like',$term)->orWhere('o.remote_id','like',$term);});}if(!empty($f['date'])&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$f['date']))$q->where('o.created_at','like',$f['date'].'%');}
 private function counts(){$out=array('pending'=>0,'running'=>0,'failed'=>0,'completed'=>0,'reconciliation_required'=>0,'intervention_required'=>0);foreach(Capsule::table('mod_cloudhost247_ovh_operations')->select('status',Capsule::raw('COUNT(*) as aggregate'))->groupBy('status')->get()as$r)if(isset($out[$r->status]))$out[$r->status]=(int)$r->aggregate;return$out;}
 private function reconciliation(array$rows){$out=array();foreach($rows as$r)if(in_array($r->status,array('running','failed','reconciliation_required','completed','intervention_required'),true)){$request=json_decode($r->request_json?:'{}',true);$response=json_decode($r->response_json?:'{}',true);$out[]=array('operation_id'=>$r->id,'service'=>$r->domain?:$r->whmcs_service_id,'correlation_id'=>$r->idempotency_key,'idempotency_key'=>$r->idempotency_key,'intent'=>$r->operation,'cart_id'=>$request['cart_id']??null,'item_id'=>$request['item_id']??null,'order_id'=>$r->remote_id,'state'=>strtoupper($r->status),'remote_state'=>is_array($response)?($response['status']??null):null,'failure'=>$r->error_message,'created_at'=>$r->created_at,'updated_at'=>$r->updated_at,'recovery'=>in_array($r->status,array('reconciliation_required','intervention_required'),true)?'Review evidence and explicitly bind a verified remote result; never repeat the mutation.':($r->status==='failed'?'Retry only after proving the prior mutation did not reach OVH.':'No recovery action required.'));}return$out;}
}
