<?php
namespace CloudHost247\Currency\Services;
use CloudHost247\Foundation\Security\AdminGuard;use CloudHost247\Foundation\Support\AuditLogger;use CloudHost247\Currency\Support\HttpClient;use InvalidArgumentException;
final class AdminController
{
 private$repo;public function __construct(CurrencyRepository$r){$this->repo=$r;}
 public function handle(){AdminGuard::requireAdmin();$notice='';$error='';try{if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){AdminGuard::requirePostToken();$op=$_POST['operation']??'';AdminGuard::requireCapability('cloudhost247_currency',$op==='update'?'rates.update':'settings.manage');if(in_array($op,array('settings','currency','update'),true)&&empty($_POST['confirm']))throw new InvalidArgumentException('Explicit financial-operation confirmation is required.');if($op==='settings'){$before=$this->repo->settings();$this->repo->saveSettings($_POST);AuditLogger::record('cloudhost247_currency','settings.update','currency-settings','global',$before,$this->repo->settings());$notice='Settings saved.';}elseif($op==='currency'){$before=$this->find($this->repo->currencies(),(int)$_POST['id']);$this->repo->saveCurrency($_POST);AuditLogger::record('cloudhost247_currency','policy.update','currency',(int)$_POST['id'],(array)$before,(array)$this->find($this->repo->currencies(),(int)$_POST['id']));$notice='Currency policy saved.';}elseif($op==='provider'){$key=(string)$_POST['provider_key'];$this->repo->toggleProvider($key,!empty($_POST['enabled']),$_POST['priority']??null);AuditLogger::record('cloudhost247_currency','provider.update','provider',$key,array(),array('enabled'=>!empty($_POST['enabled']),'priority'=>(int)($_POST['priority']??100)));$notice='Provider status and priority saved.';}elseif($op==='update'){$result=(new UpdateEngine($this->repo,new HttpClient()))->run('manual');AuditLogger::record('cloudhost247_currency','rates.update','currency-run',$result['run_id'],array(),array('count'=>$result['count']));$notice='Updated '.$result['count'].' currencies in run '.$result['run_id'].'.';}else throw new InvalidArgumentException('Unknown operation.');}}catch(\Throwable$e){$error=$e->getMessage();}$history=$this->repo->history(50,$_GET['history_page']??1,$_GET['run_status']??'');$allHistory=$this->repo->history(100,1,'');return array('settings'=>$this->repo->settings(),'currencies'=>$this->repo->currencies(),'providers'=>$this->repo->providers(),'history'=>$history,'rates'=>$this->repo->latestRates($_GET['currency']??''),'comparison'=>$this->repo->comparison(),'last_success'=>$this->last($allHistory,'success'),'last_failure'=>$this->last($allHistory,'failed'),'notice'=>$notice,'error'=>$error,'token'=>function_exists('generate_token')?generate_token('plain'):'');}
 private function find(array$rows,$id){foreach($rows as$r)if((int)$r->id===$id)return$r;return null;}private function last(array$rows,$status){foreach($rows as$r)if($r->status===$status)return$r;return null;}
}
