<?php
namespace CloudHost247\Currency\Services;
use WHMCS\Database\Capsule; use InvalidArgumentException;
final class CurrencyRepository
{
 public function settings(){ $out=array();foreach(Capsule::table('mod_cloudhost247_currency_settings')->get() as $r)$out[$r->setting_key]=(string)$r->setting_value;return $out; }
 public function saveSettings(array $in){$base=strtoupper(trim((string)$in['base_currency']));if(!preg_match('/^[A-Z]{3}$/',$base))throw new InvalidArgumentException('Invalid base currency.');if(!Capsule::table('tblcurrencies')->where('code',$base)->exists())throw new InvalidArgumentException('Base currency must exist in WHMCS.');$freq=(int)$in['update_frequency_minutes'];if($freq<15||$freq>43200)throw new InvalidArgumentException('Frequency must be 15–43200 minutes.');$keys=array();foreach(Capsule::table('mod_cloudhost247_currency_providers')->where('enabled',1)->orderBy('priority')->get() as $p)$keys[]=$p->provider_key;if(!$keys)throw new InvalidArgumentException('At least one provider must be enabled.');foreach(array('base_currency'=>$base,'update_frequency_minutes'=>(string)$freq,'provider_order'=>implode(',',$keys)) as $k=>$v)Capsule::table('mod_cloudhost247_currency_settings')->updateOrInsert(array('setting_key'=>$k),array('setting_value'=>$v,'updated_at'=>date('Y-m-d H:i:s')));}
 public function syncCurrencies(){foreach(Capsule::table('tblcurrencies')->get() as $c)Capsule::table('mod_cloudhost247_currency_config')->updateOrInsert(array('whmcs_currency_id'=>$c->id),array('currency_code'=>strtoupper($c->code),'updated_at'=>date('Y-m-d H:i:s')));}
 public function currencies(){ $this->syncCurrencies();return Capsule::table('mod_cloudhost247_currency_config as c')->join('tblcurrencies as w','w.id','=','c.whmcs_currency_id')->select('c.*','w.rate as current_rate','w.prefix','w.suffix')->orderBy('c.currency_code')->get()->all(); }
 public function saveCurrency(array $in){$id=(int)$in['id'];$margin=(float)$in['margin_percent'];$precision=(int)$in['precision_digits'];$mode=(string)$in['rounding_mode'];if($margin < -99||$margin>1000)throw new InvalidArgumentException('Invalid margin.');if($precision<0||$precision>12)throw new InvalidArgumentException('Invalid precision.');if(!in_array($mode,array('nearest','up','down'),true))throw new InvalidArgumentException('Invalid rounding mode.');Capsule::table('mod_cloudhost247_currency_config')->where('id',$id)->update(array('enabled'=>!empty($in['enabled']), 'margin_percent'=>$margin,'precision_digits'=>$precision,'rounding_mode'=>$mode,'updated_at'=>date('Y-m-d H:i:s')));}
 public function providers(){return Capsule::table('mod_cloudhost247_currency_providers')->orderBy('priority')->get()->all();}
 public function toggleProvider($key,$enabled,$priority=null){if(!in_array($key,array('ecb','frankfurter'),true))throw new InvalidArgumentException('Unknown provider.');$values=array('enabled'=>$enabled?1:0,'updated_at'=>date('Y-m-d H:i:s'));if($priority!==null){$priority=(int)$priority;if($priority<1||$priority>1000)throw new InvalidArgumentException('Provider priority must be 1–1000.');$values['priority']=$priority;}Capsule::table('mod_cloudhost247_currency_providers')->where('provider_key',$key)->update($values);}
 public function history($limit=50,$page=1,$status=''){$limit=max(10,min(100,(int)$limit));$page=max(1,(int)$page);$q=Capsule::table('mod_cloudhost247_currency_runs');if(in_array($status,array('running','success','failed'),true))$q->where('status',$status);return$q->orderBy('id','desc')->offset(($page-1)*$limit)->limit($limit)->get()->all();}

 public function comparison(){ $rows=Capsule::table('mod_cloudhost247_currency_rates as r')->join('mod_cloudhost247_currency_runs as u','u.id','=','r.run_id')->where('u.status','success')->select('r.currency_code','r.effective_rate','r.observed_at','r.run_id')->orderBy('r.id','desc')->limit(500)->get();$out=array();foreach($rows as $r){if(!isset($out[$r->currency_code]))$out[$r->currency_code]=array('currency_code'=>$r->currency_code,'current'=>$r->effective_rate,'previous'=>null,'observed_at'=>$r->observed_at);elseif($out[$r->currency_code]['previous']===null)$out[$r->currency_code]['previous']=$r->effective_rate;}return array_values($out);}
 public function latestRates($currency=''){ $q=Capsule::table('mod_cloudhost247_currency_rates as r')->join('mod_cloudhost247_currency_runs as u','u.id','=','r.run_id')->where('u.status','success')->select('r.*');$currency=strtoupper(trim((string)$currency));if($currency!==''&&preg_match('/^[A-Z]{3}$/',$currency))$q->where('r.currency_code',$currency);return$q->orderBy('r.id','desc')->limit(250)->get()->all();}
}
