<?php
namespace CloudHost247\Currency\Services;
use CloudHost247\Currency\Providers\ProviderFactory; use CloudHost247\Currency\Support\HttpClient; use CloudHost247\Currency\Support\RateMath; use CloudHost247\Foundation\Support\Logger; use WHMCS\Database\Capsule; use RuntimeException;
final class UpdateEngine
{
 private $repo,$http; public function __construct(CurrencyRepository $r,HttpClient $h){$this->repo=$r;$this->http=$h;}
 public function run($trigger='manual'){$lock=new ExecutionLock('rate-update');if(!$lock->acquire(300))throw new RuntimeException('Another currency update is already running.');$runId=null;try{$settings=$this->repo->settings();$currencies=array_filter($this->repo->currencies(),function($c){return(bool)$c->enabled;});$base=strtoupper($settings['base_currency']);$codes=array_map(function($c){return$c->currency_code;},$currencies);$runId=Capsule::table('mod_cloudhost247_currency_runs')->insertGetId(array('trigger_type'=>$trigger,'status'=>'running','base_currency'=>$base,'rate_count'=>0,'started_at'=>date('Y-m-d H:i:s')));$rates=null;$errors=array();foreach($this->repo->providers() as $p){if(!$p->enabled)continue;for($try=1;$try<=2;$try++){try{$rates=ProviderFactory::make($p->provider_key,$this->http)->fetch($base,$codes);break 2;}catch(\Throwable $e){$errors[]=$p->provider_key.' attempt '.$try.': '.$e->getMessage();if($try<2)usleep(200000);}}}if(!$rates)throw new RuntimeException('All providers failed: '.implode(' | ',$errors));$count=0;Capsule::connection()->transaction(function()use($currencies,$rates,$base,$runId,&$count){foreach($currencies as $c){if(!isset($rates[$c->currency_code]))throw new RuntimeException('No rate returned for '.$c->currency_code);$effective=$c->currency_code===$base?1.0:RateMath::effective($rates[$c->currency_code],$c->margin_percent,$c->precision_digits,$c->rounding_mode);Capsule::table('mod_cloudhost247_currency_rates')->insert(array('run_id'=>$runId,'currency_code'=>$c->currency_code,'provider_rate'=>$rates[$c->currency_code],'effective_rate'=>$effective,'margin_percent'=>$c->margin_percent,'precision_digits'=>$c->precision_digits,'observed_at'=>date('Y-m-d H:i:s')));Capsule::table('tblcurrencies')->where('id',$c->whmcs_currency_id)->update(array('rate'=>$effective));$count++;}});Capsule::table('mod_cloudhost247_currency_runs')->where('id',$runId)->update(array('status'=>'success','rate_count'=>$count,'finished_at'=>date('Y-m-d H:i:s'),'error_message'=>$errors?implode(' | ',$errors):null));Logger::write('cloudhost247_currency','info','update.success',array('run_id'=>$runId,'count'=>$count));return array('run_id'=>$runId,'count'=>$count,'warnings'=>$errors);
 }catch(\Throwable $e){if($runId)Capsule::table('mod_cloudhost247_currency_runs')->where('id',$runId)->update(array('status'=>'failed','error_message'=>substr($e->getMessage(),0,65000),'finished_at'=>date('Y-m-d H:i:s')));Logger::write('cloudhost247_currency','error','update.failed',array('run_id'=>$runId,'message'=>$e->getMessage()));throw $e;}finally{$lock->release();}}
}
