<?php
namespace CloudHost247\Ovh\Api;use CloudHost247\Foundation\Support\Logger;
final class Client
{
 private $base,$credentials,$transport,$delta=null;public function __construct($region,Credentials $c,Transport $t){$this->base=Endpoint::forRegion($region);$this->credentials=$c;$this->transport=$t;}
 public function get($p){return$this->request('GET',$p);}public function post($p,array $d=array()){return$this->request('POST',$p,$d);}public function put($p,array $d=array()){return$this->request('PUT',$p,$d);}public function delete($p,array $d=array()){return$this->request('DELETE',$p,$d);}
 public function request($method,$path,array $data=null,$safeRetry=null){$path=Endpoint::path($path);$url=$this->base.$path;$body=$data===null?'':json_encode($data,JSON_UNESCAPED_SLASHES);if($body===false)throw new ApiException('Unable to encode OVH request.');$timestamp=time()+$this->timeDelta();$headers=array('Content-Type: application/json','X-Ovh-Application: '.$this->credentials->applicationKey(),'X-Ovh-Consumer: '.$this->credentials->consumerKey(),'X-Ovh-Timestamp: '.$timestamp,'X-Ovh-Signature: '.$this->credentials->signature($method,$url,$body,$timestamp));$safeRetry=$safeRetry===null?strtoupper($method)==='GET':(bool)$safeRetry;$attempts=$safeRetry?3:1;for($i=1;$i<=$attempts;$i++){try{$r=$this->transport->send(strtoupper($method),$url,$headers,$body,5,30,5000000);if($r['status']>=200&&$r['status']<300){$decoded=$r['body']===''?array():json_decode($r['body'],true);if($r['body']!==''&&json_last_error()!==JSON_ERROR_NONE)throw new ApiException('OVH returned malformed JSON.',$r['status']);Logger::write('cloudhost247_ovh','info','api.request',array('method'=>$method,'path'=>$path,'status'=>$r['status']));return$decoded;}if(in_array($r['status'],array(429,502,503,504),true)&&$i<$attempts){usleep(min(max((int)$r['retry_after'],1),5)*1000000);continue;}$msg='OVH API request failed';$decoded=json_decode($r['body'],true);if(is_array($decoded)&&isset($decoded['message']))$msg.=': '.substr(strip_tags($decoded['message']),0,500);throw new ApiException($msg,$r['status'],$r['retry_after']);}catch(ApiException $e){if($i===$attempts)throw$e;usleep(200000*$i);}}}
 private function timeDelta(){if($this->delta!==null)return$this->delta;$r=$this->transport->send('GET',$this->base.'/auth/time',array('Accept: application/json'),'',5,15,10000);if($r['status']!==200||!is_numeric(trim($r['body'])))throw new ApiException('Unable to synchronize OVH API time.',$r['status']);return$this->delta=(int)trim($r['body'])-time();}
}
