import { FormEvent,useEffect,useState } from 'react';
import { getToken } from '../lib/auth';

type Message={id?:string;author_type:string;body:string;created_at?:string};
const SESSION_KEY='ch247_ai_support_session';
function headers(token?:string){const auth=getToken();return{'Content-Type':'application/json',...(auth?{Authorization:`Bearer ${auth}`}:{ }),...(token?{'X-AI-Conversation-Token':token}:{})}}
export default function AiSupportWidget(){
 const[open,setOpen]=useState(false),[session,setSession]=useState<{conversationId:string;accessToken:string}|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showSubscribe,setShowSubscribe]=useState(false),[contact,setContact]=useState({name:'',email:''}),[status,setStatus]=useState('AI_ACTIVE');
 useEffect(()=>{try{const raw=localStorage.getItem(SESSION_KEY);if(raw)setSession(JSON.parse(raw));}catch{localStorage.removeItem(SESSION_KEY)}},[]);
 useEffect(()=>{if(!session||!open)return;let active=true;const refresh=()=>fetch(`/api/v1/ai-support/conversations/${session.conversationId}`,{headers:headers(session.accessToken)}).then(async r=>{if(!r.ok)throw new Error('Session expired');return r.json()}).then(data=>{if(active){setMessages(data.messages);setStatus(data.conversation.status)}}).catch(()=>{if(active){localStorage.removeItem(SESSION_KEY);setSession(null)}});void refresh();const timer=window.setInterval(()=>void refresh(),10000);return()=>{active=false;window.clearInterval(timer)}},[session,open]);
 async function start(){setBusy(true);setError('');try{const r=await fetch('/api/v1/ai-support/conversations',{method:'POST',headers:headers()});if(!r.ok)throw new Error('Could not start support');const data=await r.json();const next={conversationId:data.conversationId,accessToken:data.accessToken};localStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);setMessages([{author_type:'AI',body:'Hello! I’m the CloudHost247 AI Support assistant. I use verified CloudHost247 information. Ask a question, request a human, or subscribe to service updates.'}])}catch(e){setError(e instanceof Error?e.message:'Could not start support')}finally{setBusy(false)}}
 async function send(e:FormEvent){e.preventDefault();if(!session||!text.trim())return;const body=text.trim();setText('');setMessages(v=>[...v,{author_type:'CUSTOMER',body}]);setBusy(true);try{const r=await fetch(`/api/v1/ai-support/conversations/${session.conversationId}/messages`,{method:'POST',headers:headers(session.accessToken),body:JSON.stringify({message:body})});const data=await r.json();if(!r.ok)throw new Error(data.message??'Message failed');if(data.decision?.kind==='NEWSLETTER')setShowSubscribe(true);if(data.transfer){setStatus(data.transfer.status);setMessages(v=>[...v,{author_type:'SYSTEM',body:data.transfer.body}])}else if(data.response)setMessages(v=>[...v,data.response])}catch(e){setError(e instanceof Error?e.message:'Message failed')}finally{setBusy(false)}}
 async function subscribe(e:FormEvent){e.preventDefault();if(!session)return;setBusy(true);try{const r=await fetch(`/api/v1/ai-support/conversations/${session.conversationId}/newsletter`,{method:'POST',headers:headers(session.accessToken),body:JSON.stringify(contact)});if(!r.ok)throw new Error('Subscription failed');setShowSubscribe(false);setMessages(v=>[...v,{author_type:'SYSTEM',body:'You are subscribed to CloudHost247 updates. Newsletter subscription is separate from support requests.'}])}catch(e){setError(e instanceof Error?e.message:'Subscription failed')}finally{setBusy(false)}}
 return <div className="ch247-ai-support"><button className="ch247-ai-launch" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Support</button>{open&&<section className="ch247-ai-panel" aria-label="CloudHost247 AI Support"><header><div><strong>CloudHost247 AI Support</strong><small>{status==='AI_ACTIVE'?'AI Assistant':status.replace(/_/g,' ')}</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="ch247-ai-messages">{messages.map((m,i)=><div key={m.id??i} className={`ch247-ai-message ch247-ai-message--${m.author_type.toLowerCase()}`}><small>{m.author_type==='CUSTOMER'?'You':m.author_type==='AGENT'?'CloudHost247 Support':m.author_type==='AI'?'AI Assistant':'Support status'}</small><p>{m.body}</p></div>)}{!session&&<div className="ch247-ai-welcome"><p>Get answers from verified CloudHost247 knowledge or ask for a human representative.</p><button disabled={busy} onClick={()=>void start()}>Start conversation</button></div>}</div>{error&&<p className="ch247-status-error">{error}</p>}{showSubscribe&&<form className="ch247-ai-subscribe" onSubmit={subscribe}><strong>Newsletter subscription</strong><input required minLength={2} placeholder="Full name" value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><input required type="email" placeholder="Email address" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/><button disabled={busy}>Subscribe</button></form>}{session&&!['RESOLVED','CLOSED'].includes(status)&&<form className="ch247-ai-compose" onSubmit={send}><input aria-label="Support message" maxLength={10000} placeholder="Ask CloudHost247…" value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy||!text.trim()}>Send</button></form>}{session&&status!=='AI_ACTIVE'&&<p className="ch247-ai-handoff">A CloudHost247 support representative is handling this conversation. The AI will not reply unless support explicitly returns it.</p>}</section>}</div>
}
